#!/usr/bin/perl

#
# Check the hash tables and meta data for consistency issues.
#

$PDP8 = "$ENV{'HOME'}/pdp8";
$DB = "$PDP8/shadb";

chdir $DB || die "$DB: $!";

#
# Initializing Referenced here suppressed warnings about our
# favorite orphaned metadata files below.  These are typically
# script generated, so just pretend they are referenced.
%referenced = (
  "src/dec/digital-8-12-s/digital-8-12-s-pb", 1,
);

#
# Check the hashtable.
# Errors here usually mean an indexed file was moved (or removed).
foreach $h (<[0-9a-f]*>) {
  # Look up the hashed file.
  open(HASH, $h) || die "$h: $!";
  $name = <HASH>; chop $name;
  # It must exist in the $PDP8 hierarchy.
  # In addition, it must hash to $h.
  ($hash) = split(/\s+/, `sha256sum '$PDP8/$name'`);
  unless ($h eq $hash) {
    warn "$h: $name: Wrong hashcode\n" if $hash;
    warn "$h: $name: Removed\n" unless $hash;
    print "rm $h\n";
# BUGBUG: Possible hashcode collision with new hash!
    print "echo '$name' >$hash\n" if $hash;
  }
  # Remember that the metadata file was referenced.
  $referenced{$name} = 1;
}

#
# Check for orpan metadata files.
# Errors here usually mean an indexed file was moved (or removed).
# Other errors relate to the "true name" mythology.  That is, identical
# files which have multiple names and we want to keep it that way.
# For example, digital-8-12-s-l-pb (ODT low) and digital-8-12-s-pb
# (the default ODT).
#
foreach $d (<*/.>) {
  $d =~ s:/[.]::;
  open(INPUT, "find $d -type f -print |") || die "$d: $!";
  while (<INPUT>) {
    $md = <INPUT>; chop $md;
#warn "$md ok\n" if $referenced{$md};
    next if $referenced{$md};
    # Metadata for files that don't exist (yet) is expected.
    next unless -f "$PDP8/$md";
    # The file corresponding to the metadata exists, but wasn't hashed.
    # Hashed under another name?
    ($hash) = split(/\s+/, `sha256sum '$PDP8/$md'`);
    if (open(HASH, $hash)) {
      $name = <HASH>; chop $name;
      # It hashed to a used hashcode, so it should be identical.
      die "$md vs $name: hashcode collision!\n"
        if system "cmp $PDP8/$md $PDP8/$name";
      # Warn the user that the hashdata won't be found!
      warn "$md: aliases $name\n";
      if (-f $name) {
        warn "$name metadata also exists!\n";
        next;
      }
    }
    # It suffices to redirect the hash.
    print "echo $md >$hash\n";
  }
}
