// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: cpol_use 
// c2: cpol_use 
// c3: c_us 
// c4: c_us 
// c5: c_us 
// c6: c_us 
// c7: c_us 
// c8: cpol_use 
// c9: cpol_use 
// c10: cpol_use 
// c11: cpol_use 
// c12: c_us 
// c13: c_us 
// c14: c_us 
// c15: c_us 
// c16: c_us 
// c17: c_us 
// c18: c_us 
// c19: c_us 
// c20: cpol_use 
// e1: sn7400 
module m715x (ac9, bdata2, n2_8v, n3v, n_t_18x, n_t_20x, n_t_26x, n_t_27x, , a1, b1, b_bot, b_last_brk, b_set, b_stop, be, bh, catch, cfmk_l, clear_y, clk_l, clock, clock_1, clock_enable, clock_iot, clrce_l, crcs_l, crd0_l, crd1_l, crd2_l, crd3_l, crd4_l, crd5_l, crd6_l, crd7_l, crdp_l, crds_l, ctur_l, e2, ebot_l, enable_l, f1, feed_sw_l, flag, flag_buffer, fmk_l, h2, inh_strobe_l, initialize, io_irq_l, io_skip_l, iop1, iop1_l, iop2, iop2_l, iop4, iop4_l, irq_enb, j1, light_pen, load_counter, load_x, m1, mb10, mb10=1, mb11, mb11=1, mb3=0, mb3_l, mb4_l, mb5, mb5=0, mb6_l, mb7, mb7=1, mb8, mb8=0, mb9, mb9_l, motor_on_ch, n15v, n_t_10x, n_t_11x, n_t_12x, n_t_14x, n_t_15x, n_t_1x, n_t_24x, n_t_35x, n_t_36x, n_t_38x, n_t_39x, n_t_42x, n_t_50x, n_t_5x, n_t_8x, n_t_9x, overflow, pb2, pb3, power_clear_l, rds_l, rsdwn_l, rtur_l, run_l, shift, shift_l, stop_complete, stop_delay, strobe, tb3_h, tp_av, tp_bm, u1, v_clamp, xrd0_l, xrd2_l, xrd4_l, xrdp_l, z_axis);
output ac9;
output bdata2;
output n2_8v;
output n3v;
input n_t_18x;
output n_t_20x;
input n_t_26x;
output n_t_27x;
output ;
output a1;
output b1;
output b_bot;
output b_last_brk;
output b_set;
output b_stop;
output be;
output bh;
input catch;
output cfmk_l;
output clear_y;
inout clk_l;
output clock;
output clock_1;
output clock_enable;
output clock_iot;
output clrce_l;
output crcs_l;
output crd0_l;
output crd1_l;
output crd2_l;
output crd3_l;
output crd4_l;
output crd5_l;
output crd6_l;
output crd7_l;
output crdp_l;
output crds_l;
output ctur_l;
output e2;
output ebot_l;
input enable_l;
output f1;
input feed_sw_l;
output flag;
output flag_buffer;
output fmk_l;
output h2;
output inh_strobe_l;
output initialize;
output io_irq_l;
output io_skip_l;
output iop1;
output iop1_l;
output iop2;
output iop2_l;
output iop4;
output iop4_l;
output irq_enb;
output j1;
output light_pen;
output load_counter;
output load_x;
output m1;
output mb10;
output mb10=1;
output mb11;
output mb11=1;
output mb3=0;
output mb3_l;
output mb4_l;
output mb5;
output mb5=0;
output mb6_l;
output mb7;
output mb7=1;
output mb8;
output mb8=0;
output mb9;
output mb9_l;
input motor_on_ch;
output n15v;
inout n_t_10x;
inout n_t_11x;
inout n_t_12x;
output n_t_14x;
output n_t_15x;
inout n_t_1x;
output n_t_24x;
output n_t_35x;
output n_t_36x;
output n_t_38x;
output n_t_39x;
output n_t_42x;
output n_t_50x;
inout n_t_5x;
inout n_t_8x;
inout n_t_9x;
output overflow;
output pb2;
output pb3;
output power_clear_l;
output rds_l;
output rsdwn_l;
output rtur_l;
input run_l;
output shift;
inout shift_l;
output stop_complete;
input stop_delay;
input strobe;
output tb3_h;
input tp_av;
inout tp_bm;
output u1;
output v_clamp;
output xrd0_l;
output xrd2_l;
output xrd4_l;
output xrdp_l;
output z_axis;


wire ac7;
wire bdata7;
wire clocka;
wire clr_dsk_ad_l;
wire crc10;
wire data_enable;
wire feed_l;
wire n12th_carry;
wire n16_carry;
wire n_t_13x;
wire n_t_19x;
wire n_t_2x;
wire n_t_3x;
wire n_t_43x;
wire n_t_6x;
wire pb0;
wire pb1;
assign n_t_6x = ~(n_t_2x & stop_delay);
assign n_t_12x = ~(n_t_26x & pb0);
assign n_t_11x = ~(pb1 & n_t_26x);
assign shift = ~(shift_l & n_t_3x);
// e3: sn7400 
assign shift_l = ~(~n_t_11x & n_t_9x);
assign clk_l = ~(n_t_19x & n_t_10x);
assign n_t_12x = ~(n_t_10x & n_t_18x);
assign n_t_11x = ~(n_t_12x & n_t_13x);
// e4: sn7404 
assign n_t_14x = ~n_t_12x;
assign n_t_10x = ~tp_av;
assign n_t_9x = ~enable_l;
// e6: sn7400 
assign n_t_1x = ~(n_t_3x & n_t_2x);
assign n_t_2x = ~(n_t_1x & run_l);
assign stop_complete = ~(feed_sw_l & n_t_6x);
assign n_t_3x = ~(catch & n_t_43x);
// e7: sn7402 
assign feed_l = ~(ac7
                   | clocka);
assign tp_bm = ~(n_t_8x
                  | n_t_5x);
assign n_t_8x = ~(clk_l
                   | motor_on_ch);
assign n_t_5x = ~(tp_bm
                   | strobe);
// r1: r_us_ 
// r2: r_us_ 
// r3: r_us_ 
// r4: r_us_ 
// r5: r_us_ 
// r6: r_us_ 
// r7: r_us_ 
// r8: r_us_ 
// r10: r_us_ 
// r11: r_us_ 
// r12: r_us_ 
// r13: r_us_ 
// r14: r_us_ 
// r15: r_us_ 
// r16: r_us_ 
// r17: r_us_ 
// r20: r_us_ 
// r21: r_us_ 
// r23: r_us_ 
// open collector 'wire-or's 
endmodule
