PB	= $(GLOB:*-pb)
ALL	= dms.df32 dms.rf08 dms.tu56

all:	$(ALL)

dms.df32: install.df32 $(PB)
	./install.df32

dms.rf08: install.rf08 $(PB)
	./install.rf08

dms.tu56: install.tu56 $(PB)
	./install.tu56
