$JOB ASSEMBLE MACREL SOURCES WITHOUT LISTING
/MUST HAVE SYS:MACREL AND DSK:MGLOB.MA
$MSG (CONTROL C) OUT IF YOU HAVEN'T ASSIGNED DEV1: AND DEV2:
.R MACREL
*DEV1:PAS2<DEV2:PAS2
.R MACREL
*DEV1:OVRS<DEV2:OVRS
.R MACREL
*DEV1:OVRE<DEV2:OVRE
.R MACREL
*DEV1:MACEXP<DEV2:MACEXP
.R MACREL
*DEV1:EXPOVR<DEV2:EXPOVR
.R MACREL
*DEV1:FIN0<DEV2:FIN0
.R MACREL
*DEV1:OVRU<DEV2:OVRU
.R MACREL
*DEV1:OVRT<DEV2:OVRT
.R MACREL
*DEV1:OVRB<DEV2:OVRB
.R MACREL
*DEV1:MAC3R<DEV2:MAC3R
.R MACREL
*DEV1:OVRD<DEV2:OVRD
.R MACREL
*DEV1:OVRC<DEV2:OVRC
.R MACREL
*DEV1:MACRO<DEV2:MACRO
.R MACREL
*DEV1:MACOPN<DEV2:MACOPN
.R MACREL
*DEV1:MACMAC<DEV2:MACMAC
.R MACREL
*DEV1:MACRTH<DEV2:MACRTH
.R MACREL
*DEV1:MAC2<DEV2:MAC2
.R MACREL
*DEV1:MACORG<DEV2:MACORG
.R MACREL
*DEV1:MACLIT<DEV2:MACLIT
.R MACREL
*DEV1:OVRA<DEV2:OVRA
.R MACREL
*DEV1:MAC3O<DEV2:MAC3O
.R MACREL
*DEV1:OVRR<DEV2:OVRR
.R MACREL
*DEV1:MACTBL<DEV2:MACTBL
.R MACREL
*DEV1:FIN3<DEV2:FIN3
.R MACREL
*DEV1:MACINI<DEV2:MACINI
.R MACREL
*DEV1:MACERR<DEV2:MACERR
.R MACREL
*DEV1:OVRQ<DEV2:OVRQ
.R MACREL
*DEV1:MAC24<DEV2:MAC24
.R MACREL
*DEV1:MACIO<DEV2:MACIO
.R MACREL
*DEV1:FIN2<DEV2:FIN2
.R MACREL
*DEV1:MACLOD<DEV2:MACLOD
/MUST HAVE SYS:MACREL.SV AND DSK:LKNMAN.MA
.R MACREL
*DEV1:LNKCAL<DEV2:LNKCAL
.R MACREL
*DEV1:LNKLSD<DEV2:LNKLSD
.R MACREL
*DEV1:LNKCD<DEV2:LNKCD
.R MACREL
*DEV1:LNKALL<DEV2:LNKALL
.R MACREL
*DEV1:LNKMAP<DEV2:LNKMAP
.R MACREL
*DEV1:LNKBN1<DEV2:LNKBN1
.R MACREL
*DEV1:LNKBN2<DEV2:LNKBN2
.R MACREL
*DEV1:LNKMSG<DEV2:LNKMSG
/MUST HAVE SYS:MACREL.SV  AND DEV2:KREF.MA
.R MACREL
*DEV1:KREF<DEV2:KREF
$END
