$JOB LINK
.R LINK
*DEV:MACREL,LPT:<DEV:MACERR,MACINI,FIN3,PAS2,OVRS/K=6
*DEV:OVRE,MACEXP,EXPOVR,MACLOD/W=200
*DEV:FIN0,OVRU,OVRT,OVRQ,OVRB,MAC3R,MAC3O
*DEV:OVRD,OVRC,MACRO,MACOPN,MACRTH,MAC2,MACORG,MACLIT
*DEV:FIN2,OVRA,MAC24,OVRR,MACIO,MACMAC,MACTBL$
/NOW TO LINK LINK
.R LINK
*DEV:LINK,LPT:<DEV:LNKCAL/O
*DEV:LNKCD/C
*DEV:LNKLSD/C
*DEV:LNKALL/C
*DEV:LNKMAP/C
*DEV:LNKBN1/F/C
*DEV:LNKBN2/C
*DEV:LNKMSG$
.R LINK
*DEV:KREF,LPT:<DEV:KREF$
