$JOB TO ASSEMBLE AND SAVE EFOCAL, GW VERSION C
/THIS VERSION IS FOR ETOS USE AND INCLUDES FUNCTIONS TO
/UTILIZE TEKTRONIX 4010 GRAPHICS CAPABILITIES
.R PAL8
*EFOCLC,EFOCLC<EFOC0C,EFOC1C,EFLOTB,EFOCNC,DOLLAR
.R ABSLDR
/FIRST ZERO CORE (NOT NEEDED, BUT REMOVES ANY GARBAGE)
*ZERO
*/R
*EFOCLC,INITAL=10200$
.SAVE SYS EFOCAL
$MSG EFOCAL IS SAVED.  A CREF LISTING WILL NOW GO TO THE LINE PRINTER.
.R CREF
*LPT:<EFOCLC/M
$END
