$JOB TO ASSEMBLE AND SAVE PFOCAL, GW VERSION C
/THIS VERSION IS FOR STAND-ALONE USE AND INCLUDES FUNCTIONS TO
/UTILIZE TEKTRONIX 4010 GRAPHICS CAPABILITIES
.R PAL8
*PFOCLC,PFOCLC<PFOC0C,PFOC1C,PFLOTC,PFOCNC,DOLLAR
.R ABSLDR
/FIRST ZERO CORE (NOT NEEDED, BUT REMOVES ANY GARBAGE)
*ZERO
*/R
*PFOCLC,INITAL=10200$
.SAVE SYS PFOCAL
$MSG PFOCAL IS SAVED.  A CREF LISTING WILL NOW GO TO THE LINE PRINTER.
.R CREF
*LPT:<PFOCLC/M
$END
