$JOB OS/78 DEMONSTRATION
/ NOTES:
/ 1. DEMONP PRODUCES A DELAY
/ 2. DEMOC PRINTS A SINE WAVE
/ 3. DEMOG PRINTS A BAR GRAPH
/ 4. DEMOCH SHOWS GRAPHICS CAPABILITIES
.SET TTY ESC
.SET TTY NO ARROW
.TYPE DEMOM1.TX
.R DEMONP
.TYPE DEMOM2.TX
.DIR/F=5
.TYPE DEMOM3.TX
.TYPE DEMO1.PA
.PAL DEMO1/G
.TYPE DEMOM4.TX
.COMPAR DEMO1.PA,DEMO1.V2
.TYPE DEMOM5.TX
.COMPILE DEMOIN.BA
.R DEMONP
.R DEMOCH
.TYPE DEMOM6.TX
.R DEMONP
.TYPE DEMOM7.TX
.R DEMOC
.COMPILE DEMOG.BA
.TYPE DEMOMX.TX
.SET TTY NO ESC
.SET TTY ARROW
.SUBMIT DEMO/H
$END
