$JOB MOVE P?S/8 "B" SOURCES FROM DEVICE "FROM:" TO DEVICE "TO:"
/	LAST EDIT:	16-FEB-1988	23:00:00	CJL
.COPY TO:<FROM:RXBOOT.PA,RXBUT0.PA,RXBUT1.PA,RXINIT.PA/U
.COPY TO:<FROM:IPBOOT.PA,XEQUA.TE/U
.COPY TO:<FROM:DTAGEN.PA,IPBGEN.PA/U
.COPY TO:<FROM:COMGEN.DU,DTAGEN.DU,DSUGEN.DU,RKAGEN.DU,RXAGEN.DU/U
.COPY TO:<FROM:SUP4K.PA,SUP8K.PA/U
.COPY TO:<FROM:Z4K.PA,Z8K.PA,Z12K.PA,BLK400.PA/U
.COPY TO:<FROM:SYSHND.PA,DTAHND.PA,LTAHND.PA/U
.COPY TO:<FROM:LINHND.PA,L8MHND.PA,DL8HND.PA,DOL8.PA/U
.COPY TO:<FROM:DSUHND.PA,RKAHND.PA,RXAHND.PA,FLPHND.PA/U
.COPY TO:<FROM:FIXUP.PA
.COPY TO:<FROM:BSAVE.PA,SET.PA,CORE.PA,DATE.PA/U
.COPY TO:<FROM:CONSOL.PA,KL8.PA,KL8PCH.PA,VT8E.PA/U
.COPY TO:<FROM:ALLCAT.PA,PRINT.PA,FILMAN.PA/U
.COPY TO:<FROM:ODT.PA,DUMP.PA/U
.COPY TO:<FROM:FOCPQS.PA,BLKCPY.PA/U
.COPY TO:<FROM:SYSTAT.PA,DIRECT.PA/U
.COPY TO:<FROM:DT4PCH.PA,DTCPCH.PA,RKLPCH.PA/U
.COPY TO:<FROM:RX4MAT.PA,RXUTIL.PA/U
.COPY TO:<FROM:NPATCH.PA,4PATCH.PA,8PATCH.PA,DPATCH.PA/U
.COPY TO:<FROM:BPATCH.PA,VT8PCH.PA,OPATCH.PA/U
$END
