8/I FRONT PANEL DRIVER, E AND F CABLES (CENTER CONNECTORS)

; Declare the pins in the order we would like to light them.
PINS
 1 I AJ2 PC00
 2 I AS1 PC01
 3 I AP2 PC02
 4 I AN1 PC03
 5 I AC1 PC04
 6 I AD1 PC05
 7 I BJ2 PC06
 8 I BS1 PC07
 9 I BP2 PC08
10 I BN1 PC09
11 I BC1 PC10
12 I BD1 PC11
13 I AU2 MA00
14 I AR2 MA01
15 I AK2 MA02
16 I AE2 MA03
17 I AL1 MA04
18 I AE1 MA05
19 I BU2 MA06
20 I BR2 MA07
21 I BK2 MA08
22 I BE2 MA09
23 I BL1 MA10
24 I BE1 MA11
25 I AR1 MB00
26 I AP1 MB01
27 I AF2 MB02
28 I AD2 MB03
29 I AK1 MB04
30 I AA1 MB05
31 I BR1 MB06
32 I BP1 MB07
33 I BF2 MB08
34 I BD2 MB09
35 I BK1 MB10
36 I BA1 MB11
37 I AV2 AC00
38 I AT2 AC01
39 I AJ1 AC02
40 I AH2 AC03
41 I AM1 AC04
42 I AB1 AC05
43 I BV2 AC06
44 I BT2 AC07
45 I BJ1 AC08
46 I BH2 AC09
47 I BM1 AC10
48 I BB1 AC11
49 I AS2 MQ00
50 I AM2 MQ01
51 I AN2 MQ02
52 I AL2 MQ03
53 I AF1 MQ04
54 I AH1 MQ05
55 I BS2 MQ06
56 I BM2 MQ07
57 I BN2 MQ08
58 I BL2 MQ09
59 I BF1 MQ10
60 I BH1 MQ11

IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
111111111111111111111111111111111111111111111111111111111111
; All lights on -- smoke test
000000000000000000000000000000000000000000000000000000000000
; All lights off
111111111111111111111111111111111111111111111111111111111111
; PC0
0
; PC1
10
; PC2
 10
; PC3
  10
; PC4
   10
; PC5
    10
; PC6
     10
; PC7
      10
; PC8
       10
; PC9
        10
; PC10
         10
; PC11
          10
; MA0
           10
; MA1
            10
; MA2
             10
; MA3
              10
; MA4
               10
; MA5
                10
; MA6
                 10
; MA7
                  10
; MA8
                   10
; MA9
                    10
; MA10
                     10
; MA11
                      10
; MB0
                       10
; MB1
                        10
; MB2
                         10
; MB3
                          10
; MB4
                           10
; MB5
                            10
; MB6
                             10
; MB7
                              10
; MB8
                               10
; MB9
                                10
; MB10
                                 10
; MB11
                                  10
; AC0
                                   10
; AC1
                                    10
; AC2
                                     10
; AC3
                                      10
; AC4
                                       10
; AC5
                                        10
; AC6
                                         10
; AC7
                                          10
; AC8
                                           10
; AC9
                                            10
; AC10
                                             10
; AC11
                                              10
; MQ0
                                               10
; MQ1
                                                10
; MQ2
                                                 10
; MQ3
                                                  10
; MQ4
                                                   10
; MQ5
                                                    10
; MQ6
                                                     10
; MQ7
                                                      10
; MQ8
                                                       10
; MQ9
                                                        10
; MQ10
                                                         10
; MQ11
                                                          10
111111111111111111111111111111111111111111111111111111111111
END
