M203 8X SR flip flop Roland Huisman

PINS
 1 I AD2
 2 I AK2
 3 O AF2
 4 O AL1
 5 I AT2
 6 I AN2
 7 O AR2
 8 O AS2
 9 I AJ1
10 I AE2
11 O AH2
12 O AJ2
13 I AL2
14 I AU2
15 O AP2
16 O AM2
17 I AA1
18 I AE1
19 O AC1
20 O AH1
21 I AV2
22 I AM1
23 O AV1
24 O AR1
25 I AF1
26 I AB1
27 O AK1
28 O AD1
29 I AN1
30 I AS1
31 O AP1
32 O AU1

IIOOIIOOIIOOIIOOIIOOIIOOIIOOIIOO
10011001100110011001100110011001
1001                            
0110                            
0011                            
0110                            
1001                            
    1001                        
    0110                        
    0011                        
    0110                        
    1001                        
        1001                    
        0110                    
        0011                    
        0110                    
        1001                    
            1001                
            0110                
            0011                
            0110                
            1001                
                1001            
                0110            
                0011            
                0110            
                1001            
                    1001        
                    0110        
                    0011        
                    0110        
                    1001        
                        1001    
                        0110    
                        0011    
                        0110    
                        1001    
                            1001
                            0110
                            0011
                            0110
                            1001
END
