M611 14 INVERTERS USING 7 74H40 Roland Huisman
PINS
 1 I AA1
 2 O AB1
 3 I AD1
 4 O AE1
 5 I AF1
 6 O AH1
 7 I AE2
 8 O AF2
 9 I AJ1
10 O AK1
11 I AH2
12 O AJ2
13 I AL1
14 O AM1
15 I AK2
16 O AL2
17 I AN1
18 O AP1
19 I AR1
20 O AS1
21 I AP2
22 O AR2
23 I AV1
24 O AU1
25 I AS2
26 O AT2
27 I AU2
28 O AV2

IOIOIOIOIOIOIOIOIOIOIOIOIOIO
0101010101010101010101010101
01                          
10                          
01                          
  01                        
  10                        
  01                        
    01                      
    10                      
    01                      
      01                    
      10                    
      01                    
        01                  
        10                  
        01                  
          01                
          10                
          01                
            01              
            10              
            01              
              01            
              10            
              01            
                01          
                10          
                01          
                  01        
                  10        
                  01        
                    01      
                    10      
                    01      
                      01    
                      10    
                      01    
                        01  
                        10  
                        01  
                          01
                          10
                          01
0101010101010101010101010101
1010101010101010101010101010
01                          
10                          
  01                        
  10                        
    01                      
    10                      
      01                    
      10                    
        01                  
        10                  
          01                
          10                
            01              
            10              
              01            
              10            
                01          
                10          
                  01        
                  10        
                    01      
                    10      
                      01    
                      10    
                        01  
                        10  
                          01
                          10
1010101010101010101010101010
END
