// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: cpol_use 
// c2: cpol_use 
// c4: c_us 
// c5: c_us 
// c6: c_us 
// c7: c_us 
// c8: c_us 
// c9: cpol_use 
// c10: c_us 
// c11: c_us 
// c12: c_us 
// c13: c_us 
// c14: c_us 
// c15: c_us 
// c16: c_us 
// c17: c_us 
// c18: c_us 
// c19: c_us 
// c20: c_us 
// e1: sn7440 
module m514h (n_t_13x, n_t_18x, n_t_22x, n_t_24x, n_t_25x, n_t_27x, n_t_31x, n_t_41x, n_t_4x, n_t_5x, b_7ch, b_bot, b_den_5, b_dens, b_eot, b_rws, b_sel0, b_sel1, b_sel2, b_set, b_stop, blr_cc, bot_l, brec, c_strobe, clear_function_h, clear_function_l, den8_l, endpoint_l, local_l, lrcc_strobe_h, match1_h, match2_h, match4_h, mux_out_l, n15v, n2_4v, n3_3v, n7ch_h, n_t_1x, n_t_29x, n_t_33x, n_t_34x, n_t_35x, n_t_36x, n_t_6x, r_fwd, r_rew, r_rwe, rewind_status_l, select_remote_h, select_remote_l, set_function_l, set_pulse_h, set_pulse_l, sw1, sw2, sw4, v_clamp, write_strobe_h);
input n_t_13x;
input n_t_18x;
input n_t_22x;
input n_t_24x;
input n_t_25x;
input n_t_27x;
input n_t_31x;
input n_t_41x;
input n_t_4x;
output n_t_5x;
output b_7ch;
output b_bot;
output b_den_5;
output b_dens;
output b_eot;
output b_rws;
output b_sel0;
output b_sel1;
output b_sel2;
output b_set;
output b_stop;
output blr_cc;
output bot_l;
output brec;
output c_strobe;
output clear_function_h;
inout clear_function_l;
output den8_l;
output endpoint_l;
input local_l;
output lrcc_strobe_h;
inout match1_h;
inout match2_h;
inout match4_h;
inout mux_out_l;
output n15v;
output n2_4v;
output n3_3v;
input n7ch_h;
output n_t_1x;
output n_t_29x;
output n_t_33x;
output n_t_34x;
output n_t_35x;
output n_t_36x;
output n_t_6x;
output r_fwd;
output r_rew;
output r_rwe;
output rewind_status_l;
inout select_remote_h;
inout select_remote_l;
inout set_function_l;
output set_pulse_h;
output set_pulse_l;
input sw1;
input sw2;
input sw4;
output v_clamp;
output write_strobe_h;


assign select_remote_l = ~(match4_h & match2_h & match1_h & local_l);
assign select_remote_h = ~select_remote_l;
// e2: sn7400 
assign clear_function_l = ~n_t_25x;
assign set_function_l = ~(n_t_4x & select_remote_h);
assign mux_out_l = ~(set_function_l & select_remote_h);
// e4: sn7486 
assign match2_h = n_t_18x
                   ^ sw2;
assign match1_h = n_t_22x
                   ^ sw1;
assign match4_h = sw4
                   ^ n_t_13x;
assign clear_function_h = clear_function_l
                           ^ n_t_41x;
// e5: sp384n 
assign n_t_35x = n_t_31x
                  | mux_out_l;
assign n_t_33x = n_t_24x
                  | mux_out_l;
assign n_t_36x = select_remote_l
                  | ~n7ch_h;
assign n_t_34x = n_t_27x
                  | mux_out_l;
// open collector 'wire-or's 
endmodule
