$JOB (F5GEN.BI)  GENERATE MAST FIELD  -5-	30-AUG-91

.DEL RXA1:*.BN

.SQ RXA1:/O

.PAL RXA1:TTY<RXA1:MSTPAR,TTYCF,TTYM

.PAL RXA1:PRESF5<RXA1:MSTPAR,PRESF5,F5COMM

.PAL RXA1:GATEWY<RXA1:MSTPAR,GATEWY,F5COMM

.PAL RXA1:F5COMM<RXA1:MSTPAR,F5COMM

.SUB SYS:F5SAV.BI/T


$END

