// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: c_us 
// c2: c_us 
// c3: c_us 
// c4: cpol_use 
// e2: sn74h00 
module m628a (c1, e2, n3v, n_t_1x, aa1, ab1, ab2, ac1, ad00h, ad01h, ad02h, ad03h, ad04h, ad05h, ad06h, ad07h, ad08h, ad09h, ad1, ad10h, ad11h, ad2, adder3, adder4, adoneh, adonel, ae1, ae2, ae2w, af1, af1w, af2, aflagh, ah1, ah2, ainith, aj1, aj2, ak1, ak2, al1, al2, alt_mdl3_h, alt_mdl3_l, alt_mdl4_h, alt_mdl4_l, am1, am2, an1, an2, ap1, ap2, ar1, ar2, areadyh, areadyl, as1, as2, astrobeh, astrobel, at2, au1, au2, av1, av1w, av2, av2w, b2, ba1, bb2, bc1, bd00h, bd01h, bd02h, bd03h, bd04h, bd05h, bd06h, bd07h, bd08h, bd09h, bd10h, bd11h, bdoneh, bdonel, bflagh, bh1, binith, breadyh, breadyl, bstrobeh, bstrobel, c0_l, c1_l, d2, data0_l, data10_l, data11_l, data1_l, data2_l, data3_l, data4_l, data5_l, data6_l, data7_l, data8_l, data9_l, data_en, e1, f1, f2, h1, initialize, int_rqst_l, internal_io_l, io_pause_l, j1, m1, m2, mb3_h, md03_l, md04_l, md05_l, md06_l, md07_l, md08_l, md09_l, md10_l, md11_l, mdl3_h, mdl4_h, n1, n2, n_t_10x, n_t_11x, n_t_2x, n_t_3x, n_t_4x, n_t_5x, p1, p2, r, r1, r2, s1, s2, skip_l, t2, tck, tdo, tp3, u1, u2, v1, v2);
output c1;
output e2;
input n3v;
input n_t_1x;
output aa1;
output ab1;
output ab2;
output ac1;
output ad00h;
output ad01h;
output ad02h;
output ad03h;
output ad04h;
output ad05h;
output ad06h;
output ad07h;
output ad08h;
output ad09h;
output ad1;
output ad10h;
output ad11h;
output ad2;
output adder3;
output adder4;
output adoneh;
output adonel;
output ae1;
output ae2;
output ae2w;
output af1;
output af1w;
output af2;
output aflagh;
output ah1;
output ah2;
output ainith;
output aj1;
output aj2;
output ak1;
output ak2;
output al1;
output al2;
inout alt_mdl3_h;
output alt_mdl3_l;
inout alt_mdl4_h;
output alt_mdl4_l;
output am1;
output am2;
output an1;
output an2;
output ap1;
output ap2;
output ar1;
output ar2;
output areadyh;
output areadyl;
output as1;
output as2;
output astrobeh;
output astrobel;
output at2;
output au1;
output au2;
output av1;
output av1w;
output av2;
output av2w;
output b2;
output ba1;
output bb2;
output bc1;
output bd00h;
output bd01h;
output bd02h;
output bd03h;
output bd04h;
output bd05h;
output bd06h;
output bd07h;
output bd08h;
output bd09h;
output bd10h;
output bd11h;
output bdoneh;
output bdonel;
output bflagh;
output bh1;
output binith;
output breadyh;
output breadyl;
output bstrobeh;
output bstrobel;
output c0_l;
output c1_l;
output d2;
output data0_l;
output data10_l;
output data11_l;
output data1_l;
output data2_l;
output data3_l;
output data4_l;
output data5_l;
output data6_l;
output data7_l;
output data8_l;
output data9_l;
output data_en;
output e1;
output f1;
output f2;
output h1;
output initialize;
output int_rqst_l;
output internal_io_l;
output io_pause_l;
output j1;
output m1;
output m2;
output mb3_h;
output md03_l;
output md04_l;
output md05_l;
output md06_l;
output md07_l;
output md08_l;
output md09_l;
output md10_l;
output md11_l;
input mdl3_h;
input mdl4_h;
output n1;
output n2;
output n_t_10x;
output n_t_11x;
input n_t_2x;
input n_t_3x;
output n_t_4x;
input n_t_5x;
output p1;
output p2;
output r;
output r1;
output r2;
output s1;
output s2;
output skip_l;
output t2;
output tck;
output tdo;
output tp3;
output u1;
output u2;
output v1;
output v2;


wire ac3_h;
wire adder5;
wire aj1w;
wire al2w;
wire am1w;
wire am2w;
wire an1w;
wire ap1w;
wire ar2w;
wire at2w;
wire au2w;
wire bd2;
wire be2;
wire bf1;
wire bf2;
wire bh2;
wire bj1;
wire bl1;
wire bl2;
wire bm2;
wire bu2;
wire bv1;
wire bv2;
wire c3;
wire mb2_h;
wire mb2_l;
wire mb3_l;
wire n_t_15x;
wire n_t_6x;
wire n_t_7x;
assign alt_mdl3_l = ~(alt_mdl3_h & n3v);
assign alt_mdl4_l = ~(n3v & alt_mdl4_h);
assign n_t_7x = ~(n_t_3x & n3v);
assign n_t_6x = ~(n_t_5x & n3v);
// e3: sn7482 
assign alt_mdl4_h = n_t_1x
                     ^ mdl4_h;
assign gdollar_0 = n_t_1x & mdl4_h;
assign alt_mdl3_h = mdl3_h
                     ^ n_t_2x
                     ^ gdollar_0;
assign t2 = gdollar_0 & mdl3_h
             | mdl3_h & n_t_2x
             | n_t_2x & gdollar_0;
// r1: r_us_ 
// r2: r_us_ 
// r3: r_us_ 
// r4: r_us_ 
// r5: r_us_ 
// r6: r_us_ 
// open collector 'wire-or's 
endmodule
