# Instructions:
# Run 'pdp8' in this directory, and assuming socat and xterm are installed,
# the server should start automatically and the system should boot.
#br 7732; "e l; e ac; c"
set ttox0 8b
# We need a system disk, a couple of scratch media (RX01?),
# and a TC01 or some such destination for the bootable PQS8.
# Hopefully we don't need socat and SerialDisk.
at rk0 pqs8build.new
at rk1 ab.new
at rk2 scrtmp.new
!rm dt.out
at dt0 dt.out
#sh rk
echo Booting...
#set vc8 ena
b rk0
e l
e ac
