// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: c_us 
// c2: cpol_use 
// c3: cpol_use 
// c4: c_us 
// c5: cpol_use 
// c6: c_us 
// c7: c_us 
// c8: c_us 
// c9: c_us 
// e1: sn7440 
module m410a (n_t_6x, aa1, ab1, ac1, ad1, ad2, ae1, ae2, af1, af2, ah1, ah2, aj1, aj2, ak1, al1, al2, am1, am2, an1, an2, ap1, ap2, ar1, ar2, as1, as2, at2, au1, au2, av1, av2, ba1, bb1, bc1, bd1, bd2, be1, be2, bf1, bf2, bh1, bh2, bj1, bj2, bk1, bk2, bl1, bl2, bm1, bm2, bn1, bn2, bp1, bp2, br1, br2, bs1, bs2, bt2, bu1, bu2, bv1, bv2, n_t_10x, n_t_11x, n_t_12x, n_t_14x, n_t_15x, n_t_16x, n_t_1x, n_t_28x, n_t_2x, n_t_3x, n_t_5x, n_t_60x, n_t_66x, n_t_8x, n_t_9x);
input n_t_6x;
output aa1;
output ab1;
output ac1;
output ad1;
output ad2;
output ae1;
output ae2;
output af1;
output af2;
output ah1;
output ah2;
output aj1;
output aj2;
output ak1;
output al1;
output al2;
output am1;
output am2;
output an1;
output an2;
output ap1;
output ap2;
output ar1;
output ar2;
output as1;
output as2;
output at2;
output au1;
output au2;
output av1;
output av2;
output ba1;
output bb1;
output bc1;
output bd1;
output bd2;
output be1;
output be2;
output bf1;
output bf2;
output bh1;
output bh2;
output bj1;
output bj2;
output bk1;
output bk2;
output bl1;
output bl2;
output bm1;
output bm2;
output bn1;
output bn2;
output bp1;
output bp2;
output br1;
output br2;
output bs1;
output bs2;
output bt2;
output bu1;
output bu2;
output bv1;
output bv2;
inout n_t_10x;
inout reg n_t_11x;
output n_t_12x;
input n_t_14x;
output n_t_15x;
input n_t_16x;
output n_t_1x;
output n_t_28x;
input n_t_2x;
input n_t_3x;
output n_t_5x;
output n_t_60x;
output n_t_66x;
inout n_t_8x;
inout reg n_t_9x;


wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
assign n_t_12x = ~n_t_11x;
assign n_t_15x = ~n_t_14x;
// e2: sn7474 
always @(posedge n_t_14x)
  if (n_t_14x) begin
    n_t_9x <= n_t_8x;
  end
assign n_t_8x = ~n_t_9x;
always @(posedge n_t_9x)
  if (n_t_9x) begin
    n_t_11x <= n_t_10x;
  end
assign n_t_10x = ~n_t_11x;
// e3: sn7400 
assign n_t_7x = ~(~n_t_6x & n_t_16x);
assign n_t_1x = ~(n_t_3x & n_t_2x);
assign n_t_5x = n_t_6x;
// r1: r_us_ 
// r2: r_us_ 
// r3: r_us_ 
// r4: r_us_ 
// r5: r_us_ 
// r6: r_us_ 
// r7: r_us_ 
// r8: r_us_ 
// r9: r_us_ 
// r10: r_us_ 
// r11: r_us_ 
// r12: r_us_ 
// r13: r_us_ 
// r14: r_us_ 
// r15: r_us_ 
// r16: r_us_ 
// r17: r_us_ 
// r18: r_us_ 
// r19: r_us_ 
// r20: r_us_ 
// open collector 'wire-or's 
endmodule
