// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: c_us 
// c2: c_us 
// c3: c_us 
// c4: c_us 
// c5: cpol_use 
// c6: c_us 
// c7: c_us 
// c8: c_us 
// c9: c_us 
// c10: c_us 
// c11: c_us 
// c12: c_us 
// c13: c_us 
// c14: c_us 
// c15: c_us 
// c16: c_us 
// c17: c_us 
// c18: c_us 
// c19: c_us 
// c20: c_us 
// c21: c_us 
// c22: c_us 
// c23: c_us 
// c24: c_us 
// c25: c_us 
// c26: c_us 
// c27: c_us 
// e1: sn74h00 
module m420c (n3v3, n_t_15x, n_t_18x, n_t_24x, n_t_32x, n_t_33x, n_t_39x, n_t_41x, n_t_61x, n_t_64x, n_t_66x, n_t_69x, n_t_6x, q1, q2, q5, q6, w1_and_w5, a1, ab2, ac1, ac2_h, ac2_l, ac3_h, ac3_l, ad2, ae1, af1, af1w, af2, ah1, aj1, aj2, ak1, ak2, al1, al2, al2w, am1, am2, am2w, an1, an1w, an2, ap1, ap1w, ap2, ar2, as1, as2, at2, au1, av1, av1w, b1, b2, bb1, bb2, bc1, bd2, be1, be2, bf1, bf2, bh1, bh2, bj1, bj2, bk1, bl1, bl2, bm1, bm2, bn1, bp2, br1, br2, bs1, bs2, bt2, bu1, bu2, bv1, bv2, c1, c3, carry_in_l, d1, d2, e1, e2, f1, f2, h1, h2, j1, j2, k1, k2, l1, l2, load_tac, m1, m2, ma2_h, ma2_l, ma3_h, ma3_l, mb2_h, mb2_l, mb3_h, mb3_l, n1, n10v, n15v, n2, n21v, n_t_10x, n_t_17x, n_t_1x, n_t_20x, n_t_27x, n_t_28x, n_t_29x, n_t_2x, n_t_30x, n_t_34x, n_t_35x, n_t_38x, n_t_3x, n_t_4x, n_t_51x, n_t_5x, n_t_7x, n_t_8x, n_t_9x, p1, p2, pc2_h, pc3_h, pc3_l, r1, r2, s1, s2, t2, tac3_l, tb2_h, tb3_h, tma3, tmasu2, u1, u2, v1, v2);
input n3v3;
output n_t_15x;
output n_t_18x;
output n_t_24x;
input n_t_32x;
input n_t_33x;
output n_t_39x;
output n_t_41x;
output n_t_61x;
output n_t_64x;
output n_t_66x;
output n_t_69x;
output n_t_6x;
output q1;
output q2;
output q5;
output q6;
output w1_and_w5;
output a1;
output ab2;
output ac1;
output ac2_h;
output ac2_l;
output ac3_h;
output ac3_l;
output ad2;
output ae1;
output af1;
output af1w;
output af2;
output ah1;
output aj1;
output aj2;
output ak1;
output ak2;
output al1;
output al2;
output al2w;
output am1;
output am2;
output am2w;
output an1;
output an1w;
output an2;
output ap1;
output ap1w;
output ap2;
output ar2;
output as1;
output as2;
output at2;
output au1;
output av1;
output av1w;
output b1;
output b2;
output bb1;
output bb2;
output bc1;
output bd2;
output be1;
output be2;
output bf1;
output bf2;
output bh1;
output bh2;
output bj1;
output bj2;
output bk1;
output bl1;
output bl2;
output bm1;
output bm2;
output bn1;
output bp2;
output br1;
output br2;
output bs1;
output bs2;
output bt2;
output bu1;
output bu2;
output bv1;
output bv2;
output c1;
output c3;
output carry_in_l;
output d1;
output d2;
output e1;
output e2;
output f1;
output f2;
output h1;
output h2;
output j1;
output j2;
output k1;
output k2;
output l1;
output l2;
output load_tac;
output m1;
output m2;
output ma2_h;
output ma2_l;
output ma3_h;
output ma3_l;
output mb2_h;
output mb2_l;
output mb3_h;
output mb3_l;
output n1;
output n10v;
output n15v;
output n2;
output n21v;
input n_t_10x;
output n_t_17x;
input n_t_1x;
output n_t_20x;
output n_t_27x;
output n_t_28x;
output n_t_29x;
output n_t_2x;
inout n_t_30x;
inout n_t_34x;
output n_t_35x;
output n_t_38x;
output n_t_3x;
output n_t_4x;
output n_t_51x;
input n_t_5x;
output n_t_7x;
inout reg n_t_8x;
inout reg n_t_9x;
output p1;
output p2;
output pc2_h;
output pc3_h;
output pc3_l;
output r1;
output r2;
output s1;
output s2;
output t2;
output tac3_l;
output tb2_h;
output tb3_h;
output tma3;
output tmasu2;
output u1;
output u2;
output v1;
output v2;

reg n_t_8x_m;
reg n_t_9x_m;

wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
assign n_t_34x = ~(n_t_33x & n_t_32x);
assign n_t_29x = ~n_t_30x;
assign n_t_30x = ~(n_t_34x & n_t_31x);
assign n_t_31x = ~(n_t_30x & n_t_32x);
// e2: sn74h74 
always @(n_t_5x, n_t_1x, n3v3, n3v3)
  if (~n_t_1x) begin
    n_t_9x_m <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_9x_m <= 1'b1;
  end else
  if (~(n_t_5x)) begin
    n_t_9x_m <= n3v3;
  end
always @(n_t_5x, n_t_1x, n3v3, n_t_9x_m)
  if (~n_t_1x) begin
    n_t_9x <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_9x <= 1'b1;
  end else
  if (n_t_5x) begin
    n_t_9x <= n_t_9x_m;
  end
assign n_t_4x = ~n_t_9x;
always @(n_t_10x, n_t_1x, n3v3, n3v3)
  if (~n_t_1x) begin
    n_t_8x_m <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_8x_m <= 1'b1;
  end else
  if (~(n_t_10x)) begin
    n_t_8x_m <= n3v3;
  end
always @(n_t_10x, n_t_1x, n3v3, n_t_8x_m)
  if (~n_t_1x) begin
    n_t_8x <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_8x <= 1'b1;
  end else
  if (n_t_10x) begin
    n_t_8x <= n_t_8x_m;
  end
assign n_t_3x = ~n_t_8x;
// r1: r_us_ 
// r2: r_us_ 
// r3: r_us_ 
// r4: r_us_ 
// r5: r_us_ 
// r6: r_us_ 
// r7: r_us_ 
// r8: r_us_ 
// r9: r_us_ 
// r10: r_us_ 
// r11: r_us_ 
// r12: r_us_ 
// r13: r_us_ 
// r14: r_us_ 
// r15: r_us_ 
// r16: r_us_ 
// r17: r_us_ 
// r18: r_us_ 
// r19: r_us_ 
// r20: r_us_ 
// r21: r_us_ 
// r22: r_us_ 
// r23: r_us_ 
// r24: r_us_ 
// r26: r_us_ 
// open collector 'wire-or's 
endmodule
