$JOB COMPILE AND BUILD BIGSTAT
.COMP BIGSRC.FT/N
.COMP BIGINI.FT/N
.COMP BIGSTA.FT/N
.COMP BIGLIS.FT/N
.COMP BIGERR.FT/N
.COMP BIGONE.FT/N
.COMP BIGMAK.FT/N
.LOAD BIGSTAT,LPT:<BIGSTAT,BIGSRC,BIGINI,BIGLIS$
*BIGERR,BIGONE,BIGMAK$
$END
