$JOB
/^  DECEMBER   18    1974
.DATE
.COMP ,LPT:<STAT.FT /A -NB
.COMP ,LPT:<STAT0.FT /A -NB
.COMP ,LPT:<STAT1.FT /A -NB
.COMP ,LPT:<STAT13.FT /A -NB
.COMP ,LPT:<STAT14.FT /A -NB
.COMP ,LPT:<STAT15.FT/A -NB
.COMP ,LPT:<STAT16.FT /A -NB
.COMP ,LPT:<STAT17.FT /A -NB
.COMP ,LPT:<STAT18.FT /A -NB
.COMP ,LPT:<STAT19.FT /A -NB
.COMP ,LPT:<STAT2.FT /A -NB
.COMP ,LPT:<STAT20.FT /A
.COMP ,LPT:<STAT22.FT/A
.COMP ,LPT:<STAT3.FT /A -NB
.COMP ,LPT:<STAT4 /A
.COMP ,LPT:<STAT5.FT /A -NB
.COMP ,LPT:<STAT6.FT /A -NB
.COMP ,LPT:<STAT6A.FT /A -NB
.COMP ,LPT:<STAT7.FT /A -NB
.COMP ,LPT:<STAT8.FT /A -NB
.COMP ,LPT:<STAT97.FT /A -NB
.COMP ,LPT:<STAT98.FT /A -NB
.COMP ,LPT:<STAT99.FT /A -NB
.COMP ,LPT:<STATM1.FT /A -NB
.COMP ,LPT:<STATER.FT /A -NB
. COMP ,LPT:<STATSK/A
.COMP ,LPT:<STATSO/A
.COMP ,LPT:<STATMV/A
$END
