$JOB
/^  DECEMBER   18    1974
.DATE
.COMP DSK:<STAT.FT/N
.COMP DSK:<STAT0.FT/N
.COMP DSK:<STAT1.FT/N
.COMP DSK:<STAT13.FT/N
.COMP DSK:<STAT14.FT/N
.COMP DSK:<STAT15.FT/N
.COMP DSK:<STAT16.FT/N
.COMP DSK:<STAT17/N
.COMP DSK:<STAT18.FT/N
.COMP DSK:<STAT19.FT/N
.COMP DSK:<STAT20.FT/N
.COMP DSK:<STAT22.FT/N
.COMP DSK:<STAT2.FT/N
.COMP DSK:<STAT3.FT/N
.COMP DSK:<STAT4.FT/N
.COMP DSK:<STAT5.FT/N
.COMP DSK:<STAT6.FT/N
.COMP DSK:<STAT6A.FT/N
.COMP DSK:<STAT7.FT/N
.COMP DSK:<STAT8.FT/N
.COMP DSK:<STAT97.FT/N
.COMP DSK:<STAT98.FT/N
.COMP DSK:<STAT99.FT/N
.COMP DSK:<STATM1.FT/N
.COMP DSK:<STATER.FT/N
.COMP DSK:<STATSK.FT/N
.COMP DSK:<STATSO.FT/N
.COMP DSK:<STATMV.FT/N
/BESIDE THESE THE FOLLOWING SUBROUTINES RUTINES ARE NEEDED
/MPAIR,SRANK,RANK,TIE,UTEST,NDTR,NUMINT,TWOAV,FINV,ZINV,TINV
.SUBMIT STATB
$END
