// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: c_us 
// c2: c_us 
// c3: c_us 
// c4: c_us 
// c5: c_us 
// c6: c_us 
// c7: c_us 
// c8: c_us 
// c9: c_us 
// c10: c_us 
// c11: c_us 
// c12: c_us 
// c13: c_us 
// c14: c_us 
// c15: cpol_use 
// c16: cpol_use 
// c17: c_us 
// c18: c_us 
// e1: sn7401 
// n_t_71x = !(n_t_72x & n_t_27x); 
// n_t_71x = !(n_t_70x & n_t_69x); 
// n_t_71x = !(n_t_79x & n_t_49x); 
// n_t_71x = !(n_t_53x & n_t_52x); 
// e2: sn74h53 
// n_t_2x = !(!n_t_54x & n_t_7x
//       # n_t_67x & n_t_6x
//       # n_t_8x & n_t_9x & n3v3
//       # n_t_16x & n_t_5x); 
// n_t_1x = !n_t_2x; 
module m226x (n3v3, n_t_10x, n_t_11x, n_t_12x, n_t_13x, n_t_14x, n_t_15x, n_t_17x, n_t_19x, n_t_21x, n_t_22x, n_t_23x, n_t_24x, n_t_25x, n_t_26x, n_t_27x, n_t_28x, n_t_29x, n_t_30x, n_t_31x, n_t_32x, n_t_33x, n_t_34x, n_t_35x, n_t_37x, n_t_38x, n_t_39x, n_t_40x, n_t_41x, n_t_42x, n_t_43x, n_t_44x, n_t_45x, n_t_46x, n_t_47x, n_t_48x, n_t_49x, n_t_50x, n_t_52x, n_t_53x, n_t_54x, n_t_55x, n_t_56x, n_t_57x, n_t_58x, n_t_59x, n_t_5x, n_t_60x, n_t_62x, n_t_63x, n_t_65x, n_t_66x, n_t_67x, n_t_68x, n_t_69x, n_t_6x, n_t_70x, n_t_71x, n_t_72x, n_t_73x, n_t_74x, n_t_75x, n_t_76x, n_t_77x, n_t_79x, n_t_7x, n_t_8x, n_t_9x);
input n3v3;
input n_t_10x;
input n_t_11x;
input n_t_12x;
input n_t_13x;
input n_t_14x;
input n_t_15x;
inout n_t_17x;
input n_t_19x;
input n_t_21x;
input n_t_22x;
input n_t_23x;
input n_t_24x;
input n_t_25x;
input n_t_26x;
input n_t_27x;
inout n_t_28x;
inout n_t_29x;
input n_t_30x;
input n_t_31x;
input n_t_32x;
input n_t_33x;
input n_t_34x;
input n_t_35x;
input n_t_37x;
input n_t_38x;
input n_t_39x;
input n_t_40x;
input n_t_41x;
input n_t_42x;
input n_t_43x;
output n_t_44x;
inout n_t_45x;
input n_t_46x;
inout reg n_t_47x;
input n_t_48x;
input n_t_49x;
input n_t_50x;
inout n_t_52x;
input n_t_53x;
inout reg n_t_54x;
input n_t_55x;
input n_t_56x;
inout reg n_t_57x;
input n_t_58x;
input n_t_59x;
input n_t_5x;
input n_t_60x;
input n_t_62x;
inout reg n_t_63x;
output n_t_65x;
input n_t_66x;
inout n_t_67x;
input n_t_68x;
inout n_t_69x;
input n_t_6x;
input n_t_70x;
output n_t_71x;
input n_t_72x;
input n_t_73x;
input n_t_74x;
input n_t_75x;
input n_t_76x;
input n_t_77x;
input n_t_79x;
input n_t_7x;
input n_t_8x;
input n_t_9x;

reg n_t_20x_m;
reg n_t_36x_m;
reg n_t_47x_m;
reg n_t_54x_m;
reg n_t_57x_m;
reg n_t_63x_m;

reg n_t_20x;
reg n_t_36x;
wire n_t_16x;
wire n_t_61x;
assign n_t_69x = n_t_2x;
// e3: sn74h00 
assign n_t_16x = ~(n_t_66x & n_t_67x);
assign n_t_61x = ~(~n_t_63x & n_t_62x);
assign n_t_29x = ~(n3v3 & n_t_35x);
assign n_t_45x = ~(n3v3 & n_t_42x);
// e4: sn74h50 
assign n_t_28x = ~(n_t_17x & n3v3
                    | n_t_42x & n_t_43x);
assign n_t_17x = ~(n_t_28x & n3v3
                    | n_t_43x & n_t_45x);
// e5: sn7462 
// n_t_1x = !(n_t_12x & n_t_13x
//       # n_t_20x & n_t_15x & n3v3
//       # n_t_11x & n_t_10x & n_t_10x
//       # n_t_21x & n_t_14x); 
// n_t_2x = !n_t_1x; 
// e6: sn7474 
always @(n_t_58x, n3v3, n3v3, n_t_49x)
  if (~n3v3) begin
    n_t_63x_m <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_63x_m <= 1'b1;
  end else
  if (~(n_t_58x)) begin
    n_t_63x_m <= n_t_49x;
  end
always @(n_t_58x, n3v3, n3v3, n_t_63x_m)
  if (~n3v3) begin
    n_t_63x <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_63x <= 1'b1;
  end else
  if (n_t_58x) begin
    n_t_63x <= n_t_63x_m;
  end
always @(n_t_50x, n3v3, n3v3, n_t_49x)
  if (~n3v3) begin
    n_t_20x_m <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_20x_m <= 1'b1;
  end else
  if (~(n_t_50x)) begin
    n_t_20x_m <= n_t_49x;
  end
always @(n_t_50x, n3v3, n3v3, n_t_20x_m)
  if (~n3v3) begin
    n_t_20x <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_20x <= 1'b1;
  end else
  if (n_t_50x) begin
    n_t_20x <= n_t_20x_m;
  end
// e7: sn74h53 
// gdollar_0 = !(n_t_24x & !n_t_54x
//          # n_t_23x & n_t_17x
//          # n_t_25x & n_t_29x & n_t_28x
//          # n_t_28x & n_t_22x); 
// !gdollar_0 = !gdollar_0; 
assign n_t_52x = gdollar_0;
// e8: sn7401 
// n_t_71x = !(n_t_63x & n_t_74x); 
// n_t_71x = !(n_t_29x & n_t_77x); 
// n_t_71x = !(n_t_73x & n_t_20x); 
// n_t_71x = !(n_t_30x & n_t_57x); 
// e9: sn7474 
always @(n_t_46x, n3v3, n3v3, n_t_21x)
  if (~n3v3) begin
    n_t_47x_m <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_47x_m <= 1'b1;
  end else
  if (~(n_t_46x)) begin
    n_t_47x_m <= n_t_21x;
  end
always @(n_t_46x, n3v3, n3v3, n_t_47x_m)
  if (~n3v3) begin
    n_t_47x <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_47x <= 1'b1;
  end else
  if (n_t_46x) begin
    n_t_47x <= n_t_47x_m;
  end
always @(n_t_60x, n_t_61x, n_t_59x, n_t_49x)
  if (~n_t_61x) begin
    n_t_57x_m <= 1'b0;
  end else
  if (~n_t_59x) begin
    n_t_57x_m <= 1'b1;
  end else
  if (~(n_t_60x)) begin
    n_t_57x_m <= n_t_49x;
  end
always @(n_t_60x, n_t_61x, n_t_59x, n_t_57x_m)
  if (~n_t_61x) begin
    n_t_57x <= 1'b0;
  end else
  if (~n_t_59x) begin
    n_t_57x <= 1'b1;
  end else
  if (n_t_60x) begin
    n_t_57x <= n_t_57x_m;
  end
// e10: sn74h53 
// n_t_3x = !(n_t_33x & n_t_34x
//       # n_t_32x & n_t_47x
//       # n_t_17x & n_t_29x & n_t_26x
//       # n_t_31x & n_t_29x); 
// n_t_4x = !n_t_3x; 
assign n_t_67x = n_t_3x;
// e11: sn7401 
// n_t_71x = !(n_t_36x & n_t_76x); 
// n_t_71x = !(n_t_67x & n_t_68x); 
// n_t_71x = !(n_t_75x & n_t_28x); 
// n_t_71x = !(n_t_19x & !n_t_54x); 
// e12: sn7474 
always @(n_t_48x, n3v3, n3v3, n_t_27x)
  if (~n3v3) begin
    n_t_36x_m <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_36x_m <= 1'b1;
  end else
  if (~(n_t_48x)) begin
    n_t_36x_m <= ~n_t_27x;
  end
always @(n_t_48x, n3v3, n3v3, n_t_36x_m)
  if (~n3v3) begin
    n_t_36x <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_36x <= 1'b1;
  end else
  if (n_t_48x) begin
    n_t_36x <= n_t_36x_m;
  end
always @(n_t_56x, n_t_55x, n3v3, n_t_27x)
  if (~n_t_55x) begin
    n_t_54x_m <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_54x_m <= 1'b1;
  end else
  if (~(n_t_56x)) begin
    n_t_54x_m <= n_t_27x;
  end
always @(n_t_56x, n_t_55x, n3v3, n_t_54x_m)
  if (~n_t_55x) begin
    n_t_54x <= 1'b0;
  end else
  if (~n3v3) begin
    n_t_54x <= 1'b1;
  end else
  if (n_t_56x) begin
    n_t_54x <= n_t_54x_m;
  end
// e13: sn7462 
// n_t_4x = !(n_t_36x & n_t_39x
//       # n_t_28x & n_t_35x & n_t_26x
//       # n_t_37x & n_t_38x & n_t_38x
//       # n_t_41x & n_t_40x); 
// n_t_3x = !n_t_4x; 
// open collector 'wire-or's 
assign gdollar_0 = ~((n_t_24x & ~n_t_54x
                       | n_t_23x & n_t_17x
                       | n_t_25x & n_t_29x & n_t_28x
                       | n_t_28x & n_t_22x));
assign n_t_1x = ~(n_t_2x
                   | (n_t_12x & n_t_13x
                      | n_t_20x & n_t_15x & n3v3
                      | n_t_11x & n_t_10x & n_t_10x
                      | n_t_21x & n_t_14x));
assign n_t_2x = ~((~n_t_54x & n_t_7x
                    | n_t_67x & n_t_6x
                    | n_t_8x & n_t_9x & n3v3
                    | n_t_16x & n_t_5x)
                   | n_t_1x);
assign n_t_3x = ~((n_t_33x & n_t_34x
                    | n_t_32x & n_t_47x
                    | n_t_17x & n_t_29x & n_t_26x
                    | n_t_31x & n_t_29x)
                   | n_t_4x);
assign n_t_4x = ~(n_t_3x
                   | (n_t_36x & n_t_39x
                      | n_t_28x & n_t_35x & n_t_26x
                      | n_t_37x & n_t_38x & n_t_38x
                      | n_t_41x & n_t_40x));
assign n_t_71x = (n_t_72x & n_t_27x)
                  | (n_t_70x & n_t_69x)
                  | (n_t_79x & n_t_49x)
                  | (n_t_53x & n_t_52x)
                  | (n_t_63x & n_t_74x)
                  | (n_t_29x & n_t_77x)
                  | (n_t_73x & n_t_20x)
                  | (n_t_30x & n_t_57x)
                  | (n_t_36x & n_t_76x)
                  | (n_t_67x & n_t_68x)
                  | (n_t_75x & n_t_28x)
                  | (n_t_19x & ~n_t_54x)? 1'b0: 1'bz;
endmodule
