
$JOB INITIAL THE NUMBER 8 FINISHING SYSTEM

.TYPE SYS:SCRCLR.TX
.TYPE SYS:OPMSG1.TX
$MSG HIT "RETURN" WHEN READY TO CONTINUE
.TYPE SYS:SCRCLR.TX
.TYPE SYS:OPMSG2.TX
$MSG HIT "RETURN" WHEN FINISHED READING OPERATOR MESSAGES
.TYPE SYS:SCRCLR.TX
.R NO8

$END
