$JOB OS/78 DEMONSTRATION
/ NOTES:
/ 1. DEMONP PRODUCES A DELAY
/ 2. DEMOG PRINTS A BAR GRAPH
/ 3. DEMOCH SHOWS GRAPHICS CAPABILITIES
.SET TTY ESC
.SET TTY NO ARROW
.TYPE DEMOM1.TX
.R DELAY
.R DEMONP
.R DELAY
.TYPE DEMOM2.TX
.R DELAY
.DIR/F=5
.R DELAY
.TYPE DEMOM3.TX
.R DELAY
.TYPE DEMO1.PA
.R DELAY
.PAL DEMO1
.LOAD DEMO1
.SAVE SYS DEMO1;400
.R DEMO1
.R DELAY
.TYPE DEMOM4.TX
.R DELAY
.COMPAR DEMO1.PA,DEMO1.V2
.R DELAY
.TYPE DEMOM5.TX
.R DELAY
.EXECUTE DEMOIN.BA
.R DELAY
.R DEMONP
.R DELAY
.R DEMOCH
.R DELAY
.TYPE DEMOM6.TX
.R DELAY
.R DEMONP
.R DELAY
.TYPE DEMOM7.TX
.R DELAY
.EXECUTE DEMOG.BA
.R DELAY
.TYPE DEMOMX.TX
.R DELAY
.SUBMIT DEMO/H/T
$END
