// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: c_us 
// c2: c_us 
// c3: c_us 
// c4: c_us 
// c5: c_us 
// c6: c_us 
// c7: c_us 
// c8: c_us 
// c9: c_us 
// c10: c_us 
// c11: c_us 
// c12: c_us 
// c13: c_us 
// c14: c_us 
// c100: cpol_use 
// c101: cpol_use 
// c102: cpol_use 
// e1: n8881n 
// data3_l = !(d03 & !iot4l); 
// data2_l = !(d02 & !iot4l); 
// data1_l = !(d01 & !iot4l); 
// data0_l = !(d00 & !iot4l); 
// e2: ds8640n 
module m1703c (md03ok, md04ok, md05ok, md06ok, md07ok, md08ok, c0_l, c1_l, d00, d01, d02, d03, d04, d05, d06, d07, d08, d09, d10, d11, data0_l, data10_l, data11_l, data1_l, data2_l, data3_l, data4_l, data5_l, data6_l, data7_l, data8_l, data9_l, initialize, int_rqst_l, internal_io_l, io_pause_l, md03_l, md03h, md03l, md04_l, md04h, md04l, md05_l, md05h, md05l, md06_l, md06h, md06l, md07_l, md07h, md07l, md08_l, md08h, md08l, md09_l, md10_l, md11_l, rd_done_l, rd_rqst, skip_l);
input md03ok;
input md04ok;
input md05ok;
input md06ok;
input md07ok;
input md08ok;
output c0_l;
inout c1_l;
input d00;
input d01;
input d02;
input d03;
input d04;
input d05;
input d06;
input d07;
input d08;
input d09;
input d10;
input d11;
output data0_l;
output data10_l;
output data11_l;
output data1_l;
output data2_l;
output data3_l;
output data4_l;
output data5_l;
output data6_l;
output data7_l;
output data8_l;
output data9_l;
input initialize;
output int_rqst_l;
inout internal_io_l;
input io_pause_l;
input md03_l;
inout md03h;
output md03l;
input md04_l;
inout md04h;
output md04l;
input md05_l;
inout md05h;
output md05l;
input md06_l;
inout md06h;
output md06l;
input md07_l;
inout md07h;
output md07l;
input md08_l;
inout md08h;
output md08l;
input md09_l;
input md10_l;
input md11_l;
output rd_done_l;
input rd_rqst;
inout skip_l;


wire device_flag;
wire device_flag_l;
wire int_enable;
wire int_enable_l;
wire iot0l;
wire iot1l;
wire iot2l;
wire iot3l;
wire iot4l;
wire iotl;
wire n_t_13x;
wire n_t_26x;
assign md03h = ~md03_l;
// e3: ds8640n 
assign md07h = ~md07_l;
assign md06h = ~md06_l;
assign md04h = ~md04_l;
assign md05h = ~md05_l;
// e4: sn7404 
assign md08l = ~md08h;
assign md06l = ~md06h;
assign md07l = ~md07h;
assign md05l = ~md05h;
assign md04l = ~md04h;
assign md03l = ~md03h;
// e5b: n8881n 
// data7_l = !(d07 & !iot4l); 
// data6_l = !(d06 & !iot4l); 
// data4_l = !(d04 & !iot4l); 
// data5_l = !(d05 & !iot4l); 
// e6: sn7430 
assign iotl = ~(md08ok & md03ok & md04ok & md05ok & ~io_pause_l & md07ok & md06ok);
// e7: n8881n 
// internal_io_l = internal_io_l; 
// c1_l = c1_l; 
// c0_l = c1_l; 
// e8: sn7410 
assign rd_done_l = ~(iot4l & device_flag_l);
assign n_t_13x = ~(~initialize & iot0l & iot2l);
assign n_t_26x = ~(iot2l & ~initialize & iot4l);
// e9: n8881n 
// skip_l = skip_l; 
// int_rqst_l = !(device_flag & int_enable); 
// e10: sn7442 
assign iot0l = ~(~iotl & md09_l & md10_l & md11_l);
assign iot1l = ~(~iotl & md09_l & md10_l & ~md11_l);
assign iot2l = ~(~iotl & md09_l & ~md10_l & md11_l);
assign iot3l = ~(~iotl & md09_l & ~md10_l & ~md11_l);
assign iot4l = ~(~iotl & ~md09_l & md10_l & md11_l);
// e11: sn7400 
assign device_flag_l = ~(~n_t_26x & device_flag);
assign int_enable_l = ~(~n_t_13x & int_enable);
assign int_enable = ~(int_enable_l & iot1l);
assign device_flag = ~(device_flag_l & rd_rqst);
// e12: sn7404 
// e13b: n8881n 
// data11_l = !(d11 & !iot4l); 
// data10_l = !(d10 & !iot4l); 
// data9_l = !(d09 & !iot4l); 
// data8_l = !(d08 & !iot4l); 
// e14: ds8640n 
assign md08h = ~md08_l;
// r1: r_us_ 
// open collector 'wire-or's 
assign c0_l = ~c1_l? 1'b0: 1'bz;
assign c1_l = ~(~(~iot4l))? ~(~iot4l): 1'bz;
assign data0_l = (d00 & ~iot4l)? 1'b0: 1'bz;
assign data10_l = (d10 & ~iot4l)? 1'b0: 1'bz;
assign data11_l = (d11 & ~iot4l)? 1'b0: 1'bz;
assign data1_l = (d01 & ~iot4l)? 1'b0: 1'bz;
assign data2_l = (d02 & ~iot4l)? 1'b0: 1'bz;
assign data3_l = (d03 & ~iot4l)? 1'b0: 1'bz;
assign data4_l = (d04 & ~iot4l)? 1'b0: 1'bz;
assign data5_l = (d05 & ~iot4l)? 1'b0: 1'bz;
assign data6_l = (d06 & ~iot4l)? 1'b0: 1'bz;
assign data7_l = (d07 & ~iot4l)? 1'b0: 1'bz;
assign data8_l = (d08 & ~iot4l)? 1'b0: 1'bz;
assign data9_l = (d09 & ~iot4l)? 1'b0: 1'bz;
assign int_rqst_l = (device_flag & int_enable)? 1'b0: 1'bz;
assign internal_io_l = ~(~(~iotl))? ~(~iotl): 1'bz;
assign skip_l = ~(~(~iot3l))? ~(~iot3l): 1'bz;
endmodule
