$JOB (GENF0.BI)  CREATE   M A S T   FIELD -0- BINARY FILE	3/28/77

.DA

.DEL *.BN
.DEL SYS:MSTF0.BN,*.TM

.SQ DSK:/O
.SQ SYS:/O

.PAL RTS8<SYS:MSTPAR,RTS8
.PAL CLOCK<SYS:MSTPAR,CLOCK
.PAL PWRF<SYS:MSTPAR,PWRF
.PAL NULL<SYS:MSTPAR,NULL
.PAL TTY<SYS:MSTPAR,TTYCF,TTY
.PAL MCR<SYS:MSTPAR,MCR,MSTNAM

.R PIP
*SYS:MSTF0.BN<RTS8.BN,CLOCK.BN,PWRF.BN,NULL.BN,TTY.BN,MCR.BN/B

.MAP SYS:MSTF0.BN/S-L

.DEL *.BN
.SQ DSK:/O

$END

