$JOB (GENF1.BI)  CREATE   M A S T   FIELD -1- BINARY FILE	3/28/77

.DA

.DEL *.BN
.DEL SYS:MSTF1.BN,*.TM

.SQ DSK:/O
.SQ SYS:/O

.PAL SGATE<SYS:MSTPAR,F1COMM,SGATE
.PAL RGATE<SYS:MSTPAR,F1COMM,RGATE
.PAL PGATE<SYS:MSTPAR,F1COMM,PGATE

.R PIP
*SYS:MSTF1.BN<SGATE.BN,RGATE.BN,PGATE.BN/B

.MAP SYS:MSTF1.BN/S-L

.DEL *.BN
.SQ DSK:/O

$END

