$JOB (MSTGEN.BI)  ASSEMBLE ENTIRE   M A S T   SYSTEM	3/28/77

.DA

.DEL *.BN,MAST.SV
.DEL SYS:*.BN,*.TM,MAST.SV

.SQ DSK:/O
.SQ SYS:/O
/
/
/	CREATE MSTF0.BN			(GENF0.BI)
/
/
.PAL RTS8<SYS:MSTPAR,RTS8

.PAL CLOCK<SYS:MSTPAR,CLOCK

.PAL PWRF<SYS:MSTPAR,PWRF

.PAL NULL<SYS:MSTPAR,NULL

.PAL TTY<SYS:MSTPAR,TTYCF,TTY

.PAL MCR<SYS:MSTPAR,MCR,MSTNAM

.R PIP
*SYS:MSTF0.BN<RTS8.BN,CLOCK.BN,PWRF.BN,NULL.BN,TTY.BN,MCR.BN/B
/
/
/	CREATE MSTF1.BN			(GENF1.BI)
/
/
.PAL SGATE<SYS:MSTPAR,F1COMM,SGATE

.PAL RGATE<SYS:MSTPAR,F1COMM,RGATE

.PAL PGATE<SYS:MSTPAR,F1COMM,PGATE

.R PIP
*SYS:MSTF1.BN<SGATE.BN,RGATE.BN,PGATE.BN/B
/
/
/	CREATE MSTF5.BN			(GENF5.BI)
/
/
.PAL SNAP<SYS:MSTPAR,SNAP

.PAL LPT<SYS:MSTPAR,LPT

.R PIP
*SYS:MSTF5.BN<SNAP.BN,LPT.BN/B
/
/
/
/	LOAD AND SAVE MAST.SV		(MSTSAV.BI)
/
/
.R ABSLDR
*SYS:MSTF0,MSTF1,MSTF5/S$

.SAVE SYS:MAST.SV

.R BITMAP
*LPT:<SYS:MSTF0,MSTF1,MSTF5/S$

.DEL *.BN,BTCH??.*
.SQ DSK:/O
.SQ SYS:/O

$END
