// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: c_us 
// c2: c_us 
// c3: c_us 
// c4: c_us 
// c5: c_us 
// c6: c_us 
// c7: c_us 
// c8: c_us 
// c9: c_us 
// c10: c_us 
// c11: c_us 
// c12: c_us 
// c13: c_us 
// c14: c_us 
// c15: c_us 
// e1: sn7400 
module m503x (bu2, n3v3, n_t_19x, n_t_20x, n_t_27x, n_t_28x, n_t_43x, n_t_44x, n_t_52x, n_t_60x, n_t_6x, af1w, agnd, al2w, am2w, an1w, ap1w, av1w, b2, bc1, bd2, be2, bf1, bf2, bh2, bj1, bv1, bv2, c0_l, c1_l, c3, data0_l, data10_l, data11_l, data1_l, data2_l, data3_l, data4_l, data5_l, data6_l, data7_l, data8_l, data9_l, f1, initialize, int_rqst_l, internal_io_l, io_pause_l, j1, ma2_h, ma2_l, ma3_h, ma3_l, mb2_h, mb2_l, mb3_h, mb3_l, md03_l, md04_l, md05_l, md06_l, md07_l, md08_l, md09_l, md10_l, md11_l, n1, n15v, n_t_10x, n_t_11x, n_t_14x, n_t_15x, n_t_18x, n_t_1x, n_t_21x, n_t_23x, n_t_26x, n_t_2x, n_t_33x, n_t_34x, n_t_36x, n_t_38x, n_t_3x, n_t_42x, n_t_48x, n_t_49x, n_t_50x, n_t_51x, n_t_58x, n_t_5x, n_t_9x, p1, skip_l, tp3, tp_m, tp_n, u1);
output bu2;
output n3v3;
input n_t_19x;
output n_t_20x;
output n_t_27x;
output n_t_28x;
output n_t_43x;
output n_t_44x;
output n_t_52x;
output n_t_60x;
input n_t_6x;
output af1w;
output agnd;
output al2w;
output am2w;
output an1w;
output ap1w;
output av1w;
output b2;
output bc1;
output bd2;
output be2;
output bf1;
output bf2;
output bh2;
output bj1;
output bv1;
output bv2;
output c0_l;
output c1_l;
output c3;
output data0_l;
output data10_l;
output data11_l;
output data1_l;
output data2_l;
output data3_l;
output data4_l;
output data5_l;
output data6_l;
output data7_l;
output data8_l;
output data9_l;
output f1;
output initialize;
output int_rqst_l;
output internal_io_l;
output io_pause_l;
output j1;
output ma2_h;
output ma2_l;
output ma3_h;
output ma3_l;
output mb2_h;
output mb2_l;
output mb3_h;
output mb3_l;
output md03_l;
output md04_l;
output md05_l;
output md06_l;
output md07_l;
output md08_l;
output md09_l;
output md10_l;
output md11_l;
output n1;
output n15v;
inout n_t_10x;
inout n_t_11x;
input n_t_14x;
output n_t_15x;
output n_t_18x;
inout n_t_1x;
output n_t_21x;
output n_t_23x;
output n_t_26x;
inout n_t_2x;
output n_t_33x;
output n_t_34x;
output n_t_36x;
output n_t_38x;
output n_t_3x;
output n_t_42x;
output n_t_48x;
output n_t_49x;
output n_t_50x;
output n_t_51x;
output n_t_58x;
input n_t_5x;
output n_t_9x;
output p1;
output skip_l;
output tp3;
output tp_m;
output tp_n;
output u1;


wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
assign n_t_9x = ~n_t_1x;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
assign n_t_1x = ~(n_t_5x & n_t_2x);
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
assign n_t_2x = ~(n_t_1x & n_t_6x);
// e2: sn7400 
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
assign n_t_11x = ~(n_t_19x & n_t_10x);
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
assign n_t_10x = ~(n_t_11x & n_t_14x);
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
wire tdo;
assign n_t_18x = ~n_t_10x;
// r1: r_us_ 
// r2: r_us_ 
// r3: r_us_ 
// r4: r_us_ 
// r5: r_us_ 
// r6: r_us_ 
// r7: r_us_ 
// r8: r_us_ 
// r11: r_us_ 
// r14: r_us_ 
// r15: r_us_ 
// r16: r_us_ 
// r17: r_us_ 
// r18: r_us_ 
// r19: r_us_ 
// r20: r_us_ 
// r21: r_us_ 
// r22: r_us_ 
// r23: r_us_ 
// r24: r_us_ 
// r25: r_us_ 
// r28: r_us_ 
// r31: r_us_ 
// r32: r_us_ 
// r33: r_us_ 
// r34: r_us_ 
// r35: r_us_ 
// r36: r_us_ 
// r37: r_us_ 
// r38: r_us_ 
// r39: r_us_ 
// r40: r_us_ 
// r41: r_us_ 
// r42: r_us_ 
// r43: r_us_ 
// r44: r_us_ 
// r45: r_us_ 
// r46: r_us_ 
// r47: r_us_ 
// open collector 'wire-or's 
endmodule
