load whatami.bin
br 7600
#
#Display initial model
show cpu
g 200
#
set cpu pdp5
show cpu
g 200
#
set cpu pdp8s
show cpu
g 200
#
set cpu pdp8
show cpu
g 200
#
set cpu linc8
show cpu
g 200
#
set cpu pdp8l
show cpu
g 200
#
set cpu pdp8i
show cpu
g 200
#
set cpu pdp12
show cpu
g 200
#
set cpu pdp8e
show cpu
g 200
#
set cpu pdp8a
show cpu
g 200
#
set cpu vt78
show cpu
g 200
#
set cpu decmate1
show cpu
g 200
#
set cpu decmate2
show cpu
g 200
#
set cpu decmate3
show cpu
g 200
#
set cpu pdp12
show cpu
g 200
#q
