/OS/8 REMEMBERING REVEALER
/
/ALLOWS ONE TO INQUIRE WHAT OS/8 REMEMBERS OF THE CCL COMMANDS
/AND THE INIT (SET SYS INIT XXXXX) LINE
/
	.NOLIST ME,BE	/NO MACRO LISTING OR EXPANDED TEXT LINES
	.ENABLE ASCII

	.MACRO .EXIT
	JMP I	(7605
	.ENDM
	.MACRO .READ PAGES, BUFFER, BLOCK, ERROR
	JMS I	(7607		/CALL SYS HANDLER
	PAGES&37^100
	BUFFER
	BLOCK
	JMP	ERROR
	.ENDM
	.IF NDF BSW <
	.MACRO BSW
	CLL RTL
	RTL
	RTL
	.ENDM	>
/MAIN PROGRAM
	FIELD 0
	.RSECT	CCLBUF
	ZBLOCK 200

	.ASECT REMEM
	*10
CMDPTR,	0
	*200
	.START START		/START HERE.

START,	NOP		/FOR CHAIN
	TLS			/SET UP PRINTER
	JMS	PRINT
	INTRO
	.READ 2,CCLBUF,65,BADRD	/READ CCL REMINISCENCES BLOCK
	TAD	(CMDTBL-1	/INIT POINTER TO TABLE
	DCA	CMDPTR
CMDLP,	TAD I	CMDPTR		/GET NEXT COMMAND'S LOCATION
	SNA
	JMP	KMINIT		/END OF TABLE - DO KMON INIT
	DCA	CCLPTR		/SAVE POINTER TO SAVED COMMAND
	TAD I	CMDPTR		/GET TEXT POINTER
	DCA	1$		/SAVE FOR LATER
	TAD I	CCLPTR		/GET IN-USE FLAG. IS "1234" IF OK
	TAD	(-1234
	SZA CLA
	JMP	CMDLP		/NOT A VALID COMMAND. GET NEXT
	JMS	PRINT		/PRINT THE COMMAND NAME
1$:	0
	ISZ	CCLPTR		/POINT TO DATE WORD
	TAD I	CCLPTR
	JMS	DATE		/PRINT THE DATE
	JMS	PRINT
	CLOSEP			/FORMAT THE LINE WITH "):"
	ISZ	CCLPTR
	ISZ	CCLPTR
	ISZ	CCLPTR		/POINT TO START OF COMMAND
LOOP$:	TAD I	CCLPTR		/GET TWO SIXBIT CHARS
	AND	(7700
	SNA
	JMP	ENDCMD		/STOP WHEN HIT A ZERO
	BSW
	JMS	SIXBIT		/PRINT
	TAD I	CCLPTR		/GET SIXBIT PAIR BACK
	AND	(0077		/RIGHT HALF
	SNA
	JMP	ENDCMD		/QUIT WHEN = 0
	JMS	SIXBIT		/PRINT IT
	ISZ	CCLPTR		/POINT TO NEXT PAIR
	JMP	LOOP$
/END OF COMMAND, CRLF AND DO NEXT ONE

ENDCMD,	JMS	PRINT
	CRLF
	JMP	CMDLP

KMINIT,	.READ 2,CCLBUF,0,BADRD		/READ THE BOOT BLOCK
	TAD I	(CCLBUF+77	/GET THE "INIT" WORD
	TAD	(-400
	SNA CLA
	JMP	DONE		/IF 400, SET SYS NO INIT.
.READ 2,CCLBUF,11,BADRD	/READ THE KMON BLOCK
	JMS PRINT
	INITTX			/PRINT INIT & ETC.
	TAD	CCLBUF		/GET FIRST CHAR.
	SNA CLA
	JMP	NOINIT		/NO INIT, PRINT "NO INIT". (LOGICAL)
	TAD	(CCLBUF-1	/SET UP TO PRINT
	DCA	CMDPTR
	TAD	(-5		/MAX. 5 CHARS, UNLESS END WITH 0
	DCA	CTR
LOOP$:	TAD I	CMDPTR		/GET CHAR.
	SNA
	JMP	DONE
	JMS	TTYOUT		/PRINT IT
	ISZ	CTR
	JMP	LOOP$
NOINIT,
DONE,	JMS PRINT
	CRLF
	JMS	PRINT
	CRLF
	.EXIT

CCLPTR,	0
CTR,	0
	PAGE
/DATE PRINTING ROUTINE
/
DATE,	0
	DCA	DATEWD		/SAVE THE COMMAND'S DATE
	IAC
	TAD	DATEWD		/-1 IN DATEWD MEANS ANY DATE O.K.
	SNA CLA
	JMP	FOREVER		/PRINT "ANY DATE"
	TAD	DATEWD		/SPLIT OUT MONTH, DAY, YEAR
	SNA
	JMP	NODAT		/OOPS! NONE AT ALL!
	AND	(7400
	CLL RTL
	RTL
	RAL
	DCA	MONTH		/GET MONTH BITS
	TAD	DATEWD
	AND	(370
	CLL RTR
	RAR
	DCA	DAY		/DAY BITS
	TAD	DATEWD
	AND	(7
	DCA	YEAR		/AND YEAR BITS
	TAD I	(7777
	AND	(600		/GET OS/8 EXTENDED YEAR BITS
	CLL RAR
	BSW			/IN AC 10 & 11
	DCA	EXTEND		/SAVE THEM
	CDF 10
	TAD I	(7666		/OS/8 DATE WORD
	CDF 0
	SNA
	JMP	BADDAT		/NO OS/8 DATE!
	AND	(7
	CIA
	TAD	YEAR		/GET YEAR-OS8 YEAR
	SMA SZA CLA
	STA
	TAD	EXTEND		/IF > OS8 YEAR, BACK UP OFFSET.
	CLL RTL
	RAL			/GET REAL YEAR
ADD,	TAD	YEAR
	TAD	(70.		/PLUS 70
	DCA	YEAR		/AND SAVE IT.
	TAD	DAY		/PRINT THE DAY
	JMS	DECPRT
	STA
	TAD	MONTH		/CONVERT MONTH FROM 1-12 TO 0-11
	DCA	MONTH
	TAD	MONTH
	SPA CLA
	JMP	BADMO		/<0 IS A BAD MONTH
	TAD	MONTH
	TAD	(-12		/SO IS => 12
	SPA SNA CLA
	JMP	MONOK		/MONTH OK.
BADMO,	TAD	(12		/PRINT "BAD" FOR MONTH.
	DCA	MONTH
MONOK,	TAD	MONTH		/MULTIPLY BY SIZ FOR TEXT TABLE POINTER
	CLL RAL			/MONTH *2
	TAD	MONTH		/      *3
	CLL RAL			/      *6
	TAD	(MONLST
	DCA	1$

	JMS	PRINT		/PRINT THE MONTH NAME
1$:	0
	TAD	YEAR		/PRINT THE YEAR
	JMS	DECPRT
	JMP I	DATE
/FUNNY DATE ROUTINES

FOREVER,JMS	PRINT		/PRINT "ANY DATE"
	ANYDAY
	JMP I	DATE

NODAT,	JMS	PRINT		/NO DATE
	NODATE
	JMP I	DATE

BADDAT,	TAD	(10		/FUDGE YEAR
	JMP	ADD


DATEWD,	0
MONTH,	0
DAY,	0
YEAR,	0
EXTEND,	0
	PAGE
/TTY UTILITY ROUTINES

TTYOUT,	0
	TSF
	JMS	CHKKBD		/CHECK FOR ^S,^Q,^C.
	TLS
	CLA CLL
	JMP I	TTYOUT

DIGIT,	0
	AND	(17
	TAD	(260
	JMS	TTYOUT
	JMP I	DIGIT

SIXBIT,	0
	AND	(77		/PRINT SIXBIT CHARACTER
	TAD	(-40
	SPA
	TAD	(100
	TAD	(240
	JMS	TTYOUT
	JMP I	SIXBIT

DECPRT,	0
	DCA	T$		/TWO DIGIT DECIMAL PRINT
	DCA	DECDIG		/INIT HIGH DIGIT
	TAD	T$
LOOP$:	TAD	(-10.		/>10 STILL?
	SPA
	JMP	2$
	ISZ	DECDIG		/YES. INCREMENT DIGIT AND LOOP
	JMP	LOOP$
2$:	TAD	(10.		/RESTORE HIGH DIGIT
	DCA	T$
	TAD	DECDIG
	JMS	DIGIT		/PRINT HIGH DIGIT
	TAD	T$
	JMS	DIGIT		/AND LOW DIGIT
	JMP I	DECPRT

T$:	0
DECDIG,	0
/KEYBOARD CHECKING ROUTINE
/LOOKS FOR ^C, ^S, ^Q.

CHKKBD,	0
	DCA	SAVE		/SAVE CHAR. IN AC
	TAD	(200		/SET PARITY BIT
	KRS			/READ STATIC
	TAD	(-^"C		/^C??
	SNA
	JMP I	(7605		/RETURN TO MONITOR
	TAD	(^"C-^"S	/^S???
	SZA CLA
	JMP	RETURN		/NOPE. RETURN.
	KCF			/CLEAR CHAR
WAITLP,	KSF
	JMP	.-1		/WAIT FOR CHAR
	KRB
	AND	(177
	TAD	(200		/SET PARITY
	TAD	(-^"C		/^C AGAIN?
	SNA
	JMP I	(7605
	TAD	(^"C-^"Q	/^Q????
	SZA CLA
	JMP	WAITLP		/NOT YET.
RETURN,	TAD	CHKKBD	/SETUP RETURN
	TAD	(-2
	DCA	CHKKBD
	TAD	SAVE		/RESTORE CHAR
	JMP I	CHKKBD		/RETURN
SAVE,	0
/MESSAGE PRINTER

PRINT,	0
	TAD I	PRINT		/GET POINTER
	ISZ	PRINT
	DCA	1$
LOOP$:	TAD I	1$
	SNA
	JMP I	PRINT		/DONE!
	JMS	TTYOUT
	ISZ	1$
	JMP	LOOP$		/KEEP GOING
1$:	0

/BAD READ ERROR ROUTINE

BADRD,	JMS	PRINT
	BADIO
	JMS	PRINT
	CRLF
	.EXIT
	PAGE
/COMMAND TABLE

CMDTBL,	CCLBUF+0;	TECTXT
	CCLBUF+40;	EDITTX
	CCLBUF+100;	EXETXT
	CCLBUF+140;	UATXT
	CCLBUF+200;	UBTXT
	CCLBUF+240;	UCTXT
	CCLBUF+300;	USERTX
	0				/END OF TABLE

TECTXT,	TEXT "TECO ("
EDITTX,	TEXT "EDIT ("
EXETXT,	TEXT "EXEC ("
UATXT,	TEXT "UA   ("
UBTXT,	TEXT "UB   ("
UCTXT,	TEXT "UC   ("
USERTX,	TEXT "USER ("
CLOSEP,	TEXT "): "
CRLF,	TEXT <15> <12>
BADIO,	TEXT "System I/O Error"
INITTX,	TEXT "INIT (Any date ): "
NODATE,	TEXT " No date "
ANYDAY,	TEXT "Any date "
MONLST,	TEXT "-Jan-"
	TEXT "-Feb-"
	TEXT "-Mar-"
	TEXT "-Apr-"
	TEXT "-Mar-"
	TEXT "-Jun-"
	TEXT "-Jul-"
	TEXT "-Aug-"
	TEXT "-Sep-"
	TEXT "-Oct-"
	TEXT "-Nov-"
	TEXT "-Dec-"
	TEXT "-Bad-"

INTRO,	TEXT <15><12> "CCL Reminiscences:"<15><12><15><12>
$$$$$
