// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: c_us 
// c2: c_us 
// c3: c_us 
// c4: c_us 
// c5: c_us 
// c6: c_us 
// c7: c_us 
// c8: c_us 
// c9: c_us 
// c10: c_us 
// c11: c_us 
// c12: c_us 
// c13: c_us 
// c14: c_us 
// c15: c_us 
// c16: c_us 
// c17: c_us 
// c18: c_us 
// c19: c_us 
// e1: dec8242 
// e2: sn7475 
module m7065x (a1, b1, b2, c0_l, c1, c1_l, d1, d2, data0_l, data10_l, data11_l, data1_l, data2_l, data3_l, data4_l, data5_l, data6_l, data7_l, data8_l, data9_l, e1, e2, f1, f2, h1, h2, initialize, int_rqst_l, internal_io_l, io_pause_l, j1, j2, k1, k2, l1, l2, m1, m2, md03_l, md04_l, md05_l, md06_l, md07_l, md08_l, md09_l, md10_l, md11_l, n1, n2, p1, p2, r1, r2, s1, s2, skip_l, t2, tp3, u1, u2, v1, v2);
output reg a1;
output reg b1;
output b2;
output c0_l;
output c1;
output c1_l;
output d1;
inout reg d2;
output data0_l;
output data10_l;
output data11_l;
output data1_l;
output data2_l;
output data3_l;
output data4_l;
output data5_l;
output data6_l;
output data7_l;
output data8_l;
output data9_l;
input e1;
output reg e2;
input f1;
output f2;
output h1;
output h2;
output initialize;
output int_rqst_l;
output internal_io_l;
output io_pause_l;
input j1;
input j2;
input k1;
output k2;
output l1;
output l2;
output reg m1;
input m2;
output md03_l;
output md04_l;
output md05_l;
output md06_l;
output md07_l;
output md08_l;
output md09_l;
output md10_l;
output md11_l;
output reg n1;
input n2;
output reg p1;
output reg p2;
inout r1;
input r2;
inout reg s1;
output s2;
output skip_l;
output t2;
output tp3;
input u1;
output u2;
input v1;
inout reg v2;

reg a1_m;
reg b1_m;
reg d2_m;
reg e2_m;
reg m1_m;
reg n1_m;
reg n_t_120x_m;
reg n_t_16x_m;
reg n_t_19x_m;
reg n_t_1x_m;
reg n_t_27x_m;
reg n_t_29x_m;
reg n_t_2x_m;
reg n_t_37x_m;
reg n_t_38x_m;
reg n_t_3x_m;
reg p1_m;
reg p2_m;
reg s1_m;
reg v2_m;

wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
wire y_strobe;
always @(r1, n_t_2x, r1, n_t_2x, 1'b0)
  if (r1 & ~n_t_2x) begin
    a1_m <= 1'b0;
  end else
  if (r1 & n_t_2x) begin
    a1_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    a1_m <= 1'b0;
  end
always @(r1, n_t_2x, r1, n_t_2x, a1_m)
  if (r1 & ~n_t_2x) begin
    a1 <= 1'b0;
  end else
  if (r1 & n_t_2x) begin
    a1 <= 1'b1;
  end else
  if (1'b0) begin
    a1 <= a1_m;
  end
always @(r1, n_t_3x, r1, n_t_3x, 1'b0)
  if (r1 & ~n_t_3x) begin
    b1_m <= 1'b0;
  end else
  if (r1 & n_t_3x) begin
    b1_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    b1_m <= 1'b0;
  end
always @(r1, n_t_3x, r1, n_t_3x, b1_m)
  if (r1 & ~n_t_3x) begin
    b1 <= 1'b0;
  end else
  if (r1 & n_t_3x) begin
    b1 <= 1'b1;
  end else
  if (1'b0) begin
    b1 <= b1_m;
  end
always @(r1, n_t_1x, r1, n_t_1x, 1'b0)
  if (r1 & ~n_t_1x) begin
    d2_m <= 1'b0;
  end else
  if (r1 & n_t_1x) begin
    d2_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    d2_m <= 1'b0;
  end
always @(r1, n_t_1x, r1, n_t_1x, d2_m)
  if (r1 & ~n_t_1x) begin
    d2 <= 1'b0;
  end else
  if (r1 & n_t_1x) begin
    d2 <= 1'b1;
  end else
  if (1'b0) begin
    d2 <= d2_m;
  end
always @(r1, s1, r1, s1, 1'b0)
  if (r1 & ~s1) begin
    e2_m <= 1'b0;
  end else
  if (r1 & s1) begin
    e2_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    e2_m <= 1'b0;
  end
always @(r1, s1, r1, s1, e2_m)
  if (r1 & ~s1) begin
    e2 <= 1'b0;
  end else
  if (r1 & s1) begin
    e2 <= 1'b1;
  end else
  if (1'b0) begin
    e2 <= e2_m;
  end
// e3: dec8271 
always @(n_t_76x, n_t_23x, v1, m2, n_t_21x, m2)
  if (~n_t_23x) begin
    n_t_2x_m <= 1'b0;
  end else
  if (~(~n_t_76x)) begin
    n_t_2x_m <= v1 & m2
                   | ~n_t_21x & ~m2;
  end
always @(n_t_76x, n_t_23x, n_t_2x_m)
  if (~n_t_23x) begin
    n_t_2x <= 1'b0;
  end else
  if (~n_t_76x) begin
    n_t_2x <= n_t_2x_m;
  end
always @(n_t_76x, n_t_23x, n_t_2x, m2, n_t_51x, m2)
  if (~n_t_23x) begin
    n_t_3x_m <= 1'b0;
  end else
  if (~(~n_t_76x)) begin
    n_t_3x_m <= n_t_2x & m2
                   | ~n_t_51x & ~m2;
  end
always @(n_t_76x, n_t_23x, n_t_3x_m)
  if (~n_t_23x) begin
    n_t_3x <= 1'b0;
  end else
  if (~n_t_76x) begin
    n_t_3x <= n_t_3x_m;
  end
always @(n_t_76x, n_t_23x, n_t_3x, m2, n_t_49x, m2)
  if (~n_t_23x) begin
    n_t_1x_m <= 1'b0;
  end else
  if (~(~n_t_76x)) begin
    n_t_1x_m <= n_t_3x & m2
                   | ~n_t_49x & ~m2;
  end
always @(n_t_76x, n_t_23x, n_t_1x_m)
  if (~n_t_23x) begin
    n_t_1x <= 1'b0;
  end else
  if (~n_t_76x) begin
    n_t_1x <= n_t_1x_m;
  end
always @(n_t_76x, n_t_23x, n_t_1x, m2, n_t_1x, m2)
  if (~n_t_23x) begin
    s1_m <= 1'b0;
  end else
  if (~(~n_t_76x)) begin
    s1_m <= n_t_1x & m2
               | n_t_1x & ~m2;
  end
always @(n_t_76x, n_t_23x, s1_m)
  if (~n_t_23x) begin
    s1 <= 1'b0;
  end else
  if (~n_t_76x) begin
    s1 <= s1_m;
  end
// e4: sn7404 
// e5: sn7450 
// e6: sn7474 
always @(n_t_33x, v2, j2)
  if (v2) begin
    n_t_27x_m <= 1'b0;
  end else
  if (~(n_t_33x)) begin
    n_t_27x_m <= j2;
  end
always @(n_t_33x, v2, n_t_27x_m)
  if (v2) begin
    n_t_27x <= 1'b0;
  end else
  if (n_t_33x) begin
    n_t_27x <= n_t_27x_m;
  end
always @(n_t_33x, v2, n_t_34x)
  if (v2) begin
    n_t_29x_m <= 1'b1;
  end else
  if (~(n_t_33x)) begin
    n_t_29x_m <= n_t_34x;
  end
always @(n_t_33x, v2, n_t_29x_m)
  if (v2) begin
    n_t_29x <= 1'b1;
  end else
  if (n_t_33x) begin
    n_t_29x <= n_t_29x_m;
  end
assign l1 = ~n_t_29x;
// e7: sn7400 
assign n_t_7x = ~(n_t_19x & n_t_22x);
assign n_t_21x = ~(n_t_23x & n_t_19x);
assign n_t_24x = ~(j1 & n_t_24x);
assign iob_in_10 = ~(k1 & n_t_16x);
// e8: sn7400 
assign rfc_delayed_l = ~(j2 & n_t_34x);
assign n_t_33x = ~(n_t_27x & v2);
assign iot_012 = ~(f1 & e1);
// e9: dec8242 
// skip = !(!v2 & !r2
//     # v2 & r2); 
// e10: sn7475 
always @(r1, n_t_38x, r1, n_t_38x, 1'b0)
  if (r1 & ~n_t_38x) begin
    m1_m <= 1'b0;
  end else
  if (r1 & n_t_38x) begin
    m1_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    m1_m <= 1'b0;
  end
always @(r1, n_t_38x, r1, n_t_38x, m1_m)
  if (r1 & ~n_t_38x) begin
    m1 <= 1'b0;
  end else
  if (r1 & n_t_38x) begin
    m1 <= 1'b1;
  end else
  if (1'b0) begin
    m1 <= m1_m;
  end
always @(r1, n_t_120x, r1, n_t_120x, 1'b0)
  if (r1 & ~n_t_120x) begin
    n1_m <= 1'b0;
  end else
  if (r1 & n_t_120x) begin
    n1_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    n1_m <= 1'b0;
  end
always @(r1, n_t_120x, r1, n_t_120x, n1_m)
  if (r1 & ~n_t_120x) begin
    n1 <= 1'b0;
  end else
  if (r1 & n_t_120x) begin
    n1 <= 1'b1;
  end else
  if (1'b0) begin
    n1 <= n1_m;
  end
always @(r1, n_t_37x, r1, n_t_37x, 1'b0)
  if (r1 & ~n_t_37x) begin
    p1_m <= 1'b0;
  end else
  if (r1 & n_t_37x) begin
    p1_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    p1_m <= 1'b0;
  end
always @(r1, n_t_37x, r1, n_t_37x, p1_m)
  if (r1 & ~n_t_37x) begin
    p1 <= 1'b0;
  end else
  if (r1 & n_t_37x) begin
    p1 <= 1'b1;
  end else
  if (1'b0) begin
    p1 <= p1_m;
  end
always @(r1, v2, r1, v2, 1'b0)
  if (r1 & ~v2) begin
    p2_m <= 1'b0;
  end else
  if (r1 & v2) begin
    p2_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    p2_m <= 1'b0;
  end
always @(r1, v2, r1, v2, p2_m)
  if (r1 & ~v2) begin
    p2 <= 1'b0;
  end else
  if (r1 & v2) begin
    p2 <= 1'b1;
  end else
  if (1'b0) begin
    p2 <= p2_m;
  end
// e11: dec8271 
always @(n_t_76x, n_t_23x, s1)
  if (~n_t_23x) begin
    n_t_38x_m <= 1'b0;
  end else
  if (~(~n_t_76x)) begin
    n_t_38x_m <= s1;
  end
always @(n_t_76x, n_t_23x, n_t_38x_m)
  if (~n_t_23x) begin
    n_t_38x <= 1'b0;
  end else
  if (~n_t_76x) begin
    n_t_38x <= n_t_38x_m;
  end
always @(n_t_76x, n_t_23x, n_t_38x)
  if (~n_t_23x) begin
    n_t_120x_m <= 1'b0;
  end else
  if (~(~n_t_76x)) begin
    n_t_120x_m <= n_t_38x;
  end
always @(n_t_76x, n_t_23x, n_t_120x_m)
  if (~n_t_23x) begin
    n_t_120x <= 1'b0;
  end else
  if (~n_t_76x) begin
    n_t_120x <= n_t_120x_m;
  end
always @(n_t_76x, n_t_23x, n_t_120x)
  if (~n_t_23x) begin
    n_t_37x_m <= 1'b0;
  end else
  if (~(~n_t_76x)) begin
    n_t_37x_m <= n_t_120x;
  end
always @(n_t_76x, n_t_23x, n_t_37x_m)
  if (~n_t_23x) begin
    n_t_37x <= 1'b0;
  end else
  if (~n_t_76x) begin
    n_t_37x <= n_t_37x_m;
  end
always @(n_t_76x, n_t_23x, n_t_37x)
  if (~n_t_23x) begin
    v2_m <= 1'b0;
  end else
  if (~(~n_t_76x)) begin
    v2_m <= n_t_37x;
  end
always @(n_t_76x, n_t_23x, v2_m)
  if (~n_t_23x) begin
    v2 <= 1'b0;
  end else
  if (~n_t_76x) begin
    v2 <= v2_m;
  end
// e12: sn7416 
// !n_t_76x = !n_t_76x; 
// n_t_16x = n_t_16x; 
// !v2 = !v2; 
// !n_t_19x = !n_t_19x; 
// r1 = r1; 
// !n_t_19x = !n_t_19x; 
// e13: sn7400 
assign n_t_32x = ~(j2 & n_t_92x);
assign n_t_76x = ~(n_t_8x & n_t_21x);
// e14: sn7474 
always @(n_t_76x, n_t_92x, u1)
  if (~n_t_92x) begin
    n_t_16x_m <= 1'b0;
  end else
  if (~(~n_t_76x)) begin
    n_t_16x_m <= u1;
  end
always @(n_t_76x, n_t_92x, n_t_16x_m)
  if (~n_t_92x) begin
    n_t_16x <= 1'b0;
  end else
  if (~n_t_76x) begin
    n_t_16x <= n_t_16x_m;
  end
always @(r1, n2, v2, 1'b1)
  if (~n2) begin
    n_t_19x_m <= 1'b0;
  end else
  if (v2) begin
    n_t_19x_m <= 1'b1;
  end else
  if (~(~r1)) begin
    n_t_19x_m <= 1'b1;
  end
always @(r1, n2, v2, n_t_19x_m)
  if (~n2) begin
    n_t_19x <= 1'b0;
  end else
  if (v2) begin
    n_t_19x <= 1'b1;
  end else
  if (~r1) begin
    n_t_19x <= n_t_19x_m;
  end
assign enable_l = ~n_t_19x;
// r1: r_us_ 
// r2: r_us_ 
// r3: r_us_ 
// r4: r_us_ 
// r5: r_us_ 
// r6: r_us_ 
// r7: r_us_ 
// r8: r_us_ 
// r9: r_us_ 
// r10: r_us_ 
// r11: r_us_ 
// open collector 'wire-or's 
assign r1 = ~(~(~(n2 & n_t_22x)))? ~(~(n2 & n_t_22x)): 1'bz;
assign skip = ~((~v2 & ~r2
                  | v2 & r2));
endmodule
