<*> = ENTERPRISE
 *  = STAR
+++ = KLINGON
>!< = STARBASE

COMMAND 0 = WARP ENGINES.
  COURSE IS IN A CIRCULAR VECTOR AS SHOWN.         4  3  2
  REAL VALUES MAY BE USED. FOR EXAMPLE              \ ^ /
  1.2 WOULD BE HALF WAY BETWEEN 1 AND 2.         5 ------- 1
  A 'WARP FACTOR' IS THE SIZE OF ONE QUARDRANT.     / ^ \
                                                   6  7  8

COMMAND 1 = LONG RANGE SCAN.
  CODED IN THE FORM XXX, WHERE THE UNITS ARE THE NUMBER
  OF STARS, TENS THE NUMBER OF STARBASES, AND HUNDREDS
  THE NUMBER OF KLINGONS.

COMMAND 2 = PHASERS.
  YOU MAY DESTROY THE KLINGON BY USING ENOUGH PHASER
  POWER AS TO DEPLETE HIS SHIELDS. KEEP IN MIND THAT WHEN
  YOU FIRE AT HIM, HE WILL FIRE BACK!

COMMAND 3 = PHOTON TORPEDOES.
  COURSE IS THE SAME AS WITH WARP ENGINES. THE LIBRARY
  COMPUTER WILL COMPUTE TRAJECTORIES FOR YOU (OPTION 1).

COMMAND 4 = SHIELDS.
  DEFINES THE AMOUNT OF ENERGY TO BE ASSIGNED TO SHIELDS.

COMMAND 5 = LIBRARY COMPUTER.
  OPTION 0 = DAMMAGE REPORT.
    A STATE OF REPAIR OF LESS THAN ZERO INDICATES THAT
    THE DEVICE IS TEMPORARILY DISABLED.
  OPTION 1 = PHOTON TORPEDO DATA.
    GIVES DIRECTION TO ALL KLINGONS IN YOUR QUADRANT.
  OPTION 2 = SHORT RANGE SCAN.
    ALSO GIVEN AUTOMATICALLY AFTER SUCCESSFUL COMPLETION
    OF WARP ENGINE MANUVERS.

COMMAND 6 = RESIGNATION.
