$JOB COMPILE ADVENT STUFF
.COMPILE ADVENT/N/Q
.COMPILE A5TOA1.RA
.COMPILE BITSET.RA
.COMPILE BUG/N/Q
.COMPILE CARRY.RA
.COMPILE DARK.RA
.COMPILE DECODE/N/Q
.COMPILE DROP.RA
.COMPILE DS\ROY.RA
.COMPILE GETIN/N/Q
.COMPILE HERE.RA
.COMPILE INITAD/N/Q
.COMPILE IO/N/Q.COMPILE JUGGLE.RA
.COMPILE LIQ.RA
.COMPILE LIQLOC.RA
.COMPILE MOVE.RA
.COMPILE PCT.RA
.COMPILE PSPEAK.RA
.COMPILE PUT.RA
.COMPILE RKB.RA
.COMPILE RND/N/Q
.COMPILE RSPEAK.RA
.COMPILE SEED.RA
.COMPILE SPEAK.RA
.COMPILE TRVLOC.RA
.COMPILE VOCAB.RA
.COMPILE YES/N/Q
$END
