$JOB (F0SAV.BI)  CREATE BINARY LIBRARY FOR MAST FIELD  -0-   8-AUG-91

.DEL RXA1:MSTF0.BN

.R PIP
*RXA1:MSTF0.BN<RXA1:RTS8.BN,CLOCK.BN,PWRF.BN,MNULL.BN,MCR.BN/B

.SQ RXA1:/O

.COPY SYS:<RXA1:MSTF0.BN

$END

