$JOB (F1GEN.BI)  GENERATE MAST FIELD  -1-	8-AUG-91

.DEL RXA1:*.BN

.SQ RXA1:/O

.PAL RXA1:LINESP<RXA1:MSTPAR,LINESP,F1COMM

.PAL RXA1:SGATE<RXA1:MSTPAR,SGATE,F1COMM

.PAL RXA1:RGATE<RXA1:MSTPAR,RGATE,F1COMM

.PAL RXA1:PGATE<RXA1:MSTPAR,PGATE,F1COMM

.PAL RXA1:DEF2<RXA1:MSTPAR,DEF2,F1COMM

.PAL RXA1:MEMORY<RXA1:MSTPAR,MEMORY,F1COMM

.PAL RXA1:TRAYCK<RXA1:MSTPAR,TRAYCK,F1COMM

.PAL RXA1:BUILD<RXA1:MSTPAR,BUILD,F1COMM

.PAL RXA1:DIGINP<RXA1:MSTPAR,DIGINP,F1COMM

.PAL RXA1:F1COMM<RXA1:MSTPAR,F1COMM


.SUB SYS:F1SAV/T


$END

