	.TITLE	SYKES FLOPPY HANDLER
;
;
;B SCHOR	R LARKIN	JULY, 1978
;
;THIS PROGRAM IS WRITTEN TO MAKE THE PDP-11 AND ITS FLOPPY DISK LOOK LIKE
;A SYKES FLOPPY DISK PERIPHERAL TO THE PDP-8 (VIA THE PARALLEL INTERFACE)
;
;ON THE PDP-11 SIDE, THIS CONSISTS OF A DRV11
;
;
;TO USE, START THIS PROGRAM FIRST--THIS IS EQUIVALENT TO "TURNING ON" THE
;SYKES DISK AS AN OS/8 PERIPHERAL
;
;ALL DISK I/O VIA .SPFUN, TO ENABLE READING AND WRITING INDIVIDUAL SECTORS
;OS/8 WILL COMMUNICATE WHICH SECTORS TO READ OR WRITE
;IF MORE THAN ONE SECTOR'S WORTH OF DATA IS REQUESTED, THIS PROGRAM WILL
;AUTOMATICALLY READ IN SUCCESSIVE SECTORS
;
;
	.MCALL	.FETCH, .LOOKUP, .SPFUN
	.MCALL	.PRINT, .TTYOUT
	.MCALL	.EXIT
;
;DR11V DEFINITIONS
;
	DRCSR  =	167770	;CONTROL AND STATUS REGISTER
	DROUT  =	DRCSR+2	;OUTPUT REGISTER
	DRIN   =	DRCSR+4	;INPUT REGISTER
;
;DESCRIPTION OF THE DRV11 PARALLEL I/O DEVICE:
;
;BIT	R/W	NAME		FUNCTION
;
;15	R	REQ B	  INTERFACE FLAG WITH 8/L.
;			  SET WHEN 8/L SENDS TO 11, OR WHEN 8/L ACCEPTS FROM 11.
; 5	R/W	INT ENB B WHEN SET, ALLOWS AN INTERRUPT TO  INITIATED
;			  WHENEVER BIT 15 (REQ B) COMES UP.
;
;
;THE INTERFACE HAS ONLY ONE FLAG FOR EACH DEVICE, SO ASYNCHRONOUS I/O IS
;NOT POSSIBLE.  HOWEVER, SYNCHRONOUS I/O CAN BE ACCOMPLISHED, USING THE
;CONCEPT OF "MASTER" AND "SLAVE" DEVICE.
;
;	MASTER	WAITS FOR TRANSFER FROM SLAVE.
;		WHEN FLAG IS RAISED, MEANS SLAVE HAS DATA TO SEND
;	SLAVE	TRANSFERS DATA TO MASTER.
;		WHEN FLAG IS RAISED, MEANS MASTER HAS ACCEPTED OFFERING
;
;MASTER CAN "VOLUNTARILY" BECOME SLAVE BY WAITING FOR FLAG, BUT NOT
;ACCEPTING DATA, BUT IMMEDIATELY SWITCHING TO SLAVE STATUS AND DOING
;FIRST TRANSFER.
;SLAVE CAN "DEMAND" TO BE MASTER BY SENDING ANY DATA, THEN WAITING FOR
;FLAG WHICH SIGNALS THAT NEWLY-DEMOTED "SLAVE" HAS DATA TO SEND.
;
;NEEDLESS TO SAY, BOTH MASTER AND SLAVE HAVE TO BE SYNCHRONIZED--
;THE MASTER MUST KNOW WHEN TO IGNORE THE "DEMAND" FROM THE SLAVE WHICH
;SIGNALS THE CHANGE OF STATUS
;
;ASSUMING THAT THE PDP-11 PROGRAM RUNS FIRST, IT SHOULD START IN "SLAVE"
;MODE, BECAUSE PDP-8 ALWAYS GENERATES A FLAG IN THE PDP-11 WHEN "START"
;SWITCH PRESSED.
;
;
;IN ALL CASES, THE PDP-11 CAN TEST ITS FLAG BY THE LOOP
;
;	TST	@#DRCSR			;CHECK FLAG
;	BPL	.-4			;TIGHT LOOP UNTIL FLAG SET
;
;
;IN THE INTERESTS OF CLEANLINESS, WE WILL USE REGISTERS 1-4 FOR STORAGE
;WE WILL DEFINE THE STORED VARIABLES BELOW AS THESE REGISTERS
;THESE REGISTERS SHOULD BE PRESERVED BY ALL RT-11 ROUTINES
;
	TRACK	=	R1	;DISK TRACK
	SECTOR	=	R2	;DISK SECTOR
	RWBIT	=	R3	;READ/WRITE COMMAND BIT
	INDEX	=	R4	;INDEX TO BUFFER (BYTE OFFSET)
;
;
;
;
;START BY GETTING DISKETTE READY
;
START:	.FETCH	#SPACE, #DX1		;FETCH DISKETTE 1
	BCS	DXERR			;ERROR!!
	.LOOKUP	#EYEOWE, #0, #DX1	;SET UP DX1 AS NON-FILE DEVICE FOR I/O
	BCS	DXERR			;ERROR!!
;
	JSR	PC, RESET		;RESET ALL SOFTWARE FLAGS
;
;INITIALLY, WE ARE IN "SLAVE" MODE
;SWITCH TO "MASTER" BY WAITING FOR PDP-8 FLAG, THEN SENDING NULL
;
	JSR	PC, WAIT8		;WAIT FOR PDP-8 "START" SWITCH
	CLR	@#DROUT			;SEND NULL, SWITCHING TO "MASTER"
;
	JMP	FROM8			;GO WAIT FOR PDP-8 TO SEND US SOMETHING
;
;
;COME HERE ON FETCH, LOOKUP ERRORS
;
DXERR:	.PRINT	#MDXERR			;INFORM USER OF ERROR
	.EXIT				;AND QUIT
;
;
;
;ACTUAL ROUTINE STARTS LOOP HERE
;
;GETS BYTE FROM PDP-8, INTERPRETS IT AS COMMAND OR DATA SEND/REQUEST WORD
;DEPENDING ON THIS BYTE, APPROPRIATE ACTION TAKEN
;
;POSSIBILITIES:
;	7600	CMD	RESET, INITIALIZES SOFTWARE FLAGS
;	603	CMD	TERMINATE, (DUMP PARTIAL OUTPUT BUFFER, IF ANY)
;	4XX	CMD	TRACK/SECTOR, XX = 0-177
;	<400	DATA
;			READ MODE, TWO WORDS THEN SENT TO PDP-8
;			WRITE MODE, THIS WORD AND NEXT SENT TO PDP-11
;
;GET DATA FROM PDP-8
;
FROM8:	JSR	PC, WAIT8		;WAIT FOR PDP-8 TO SEND
	BPL	FROM8			;HANG UNTIL WE HAVE SOMETHING
	MOV	@#DRIN, R0		;GET DATA FROM INPUT REGISTER
	BIT	#177400, R0		;CHECK UPPER BYTE, SEE IF DATA OR COMMAND
	BEQ	DATA			;GO SET UP FOR DATA I/O
	CMP	R0, #177600		;SEE IF RESET
	BNE	1$			;SKIP IF NOT
	JSR	PC, RESET		;DO RESET
	BR	FROM8			;GET ANOTHER COMMAND/DATA WORD
;
1$:	CMP	R0, #603		;CHECK FOR TERMINATE COMMAND
	BNE	2$			;BRANCH IF TRACK/SECTOR
	TST	RWBIT			;CHECK IF READ OR WRITE
	BEQ	FROM8			;IGNORE IN READ
	TST	INDEX			;SEE IF PARTIAL BUFFER
	BEQ	FROM8			;NO, BUFFER JUST WRITTEN
;
	JSR	PC, WRITE		;DUMP OUT PARTIAL BUFFER
	CLR	INDEX			;RESET BUFFER INDEX
	BR	FROM8			;GET ANOTHER COMMAND/DATA WORD
;
;GOT TRACK/SECTOR COMMAND--SINCE THEY OCCUR IN PAIRS, THE FIRST IS TRACK
;	4XX	TRACK, IN BITS 0-6, FROM 0-77 (DECIMAL)
;
2$:	BIT	#200, R0		;INSURE TRACK/SECTOR COMMAND
	BNE	SYNERR			;SYNTAX ERROR
	BIC	#^C 177, R0		;SAVE ONLY TRACK BITS
	MOV	R0, TRACK		;SAVE TRACK
;
;GET ANOTHER BYTE, WHICH MUST BE COMMAND FOR SECTOR, READ/WRITE
;	4XX	SECTOR, IN BITS 0-4, FROM 0-26 (DECIMAL)
;			BIT 5 = 0, READ THIS SECTOR
;			BIT 5 = 1, WRITE THIS SECTOR
;
	JSR	PC, WAIT8		;WAIT FOR PDP-8 TO SEND
	MOV	@#DRIN, R0		;GET DATA FROM INPUT REGISTER
	BIT	#177400, R0		;CHECK UPPER BYTE FOR DATA/COMMAND
	BEQ	SYNERR			;SYNTAX ERROR, MUST HAVE SECTOR COMMAND
	BIT	#200, R0		;INSURE TRACK/SECTOR COMMAND
	BNE	SYNERR			;SYNTAX ERROR
	MOV	R0, SECTOR		;SAVE SECTOR (PLUS R/W BIT)
	MOV	R0, RWBIT		;SAVE R/W BIT (PLUS SECTOR)
	BIC	#^C 37, SECTOR		;KEEP ONLY SECTOR BITS
	BIC	#^C 40, RWBIT		;KEEP ONLY R/W BIT
	CLR	INDEX			;RESET BUFFER INDEX
	TST	RWBIT			;SEE IF READ OR WRITE
	BNE	FROM8			;WRITE COMMAND, START GETTING DATA
;
;READ COMMAND, SO INPUT SPECIFIED SECTION OF FLOPPY FIRST
;
	JSR	PC, READ		;READ IN SPECIFIED SECTOR OF THE FLOPPY
	BR	FROM8			;GET ANOTHER COMMAND/DATA WORD
;
;
;COME HERE IF TOP PDP-8 BYTE IS ZERO
;TRANSFER BYTE (PAIR) TO OR FROM PDP-8, DEPENDING ON STATUS OF R/W BIT
;
DATA:	TST	RWBIT			;SEE IF READ OR WRITE
	BEQ	TO8			;READ, SEND TO PDP-8
;
	MOVB	R0, BUFFER(INDEX)	;STORE BYTE FROM PDP-8 IN BUFFER
	INC	INDEX			;INCREMENT INDEX
	JSR	PC, WAIT8		;WAIT FOR PDP-8 TO SEND
	MOV	@#DRIN, R0		;GET DATA FROM INPUT REGISTER
	BIT	#177400, R0		;CHECK UPPER BYTE FOR DATA/COMMAND
	BNE	SYNERR			;SYNTAX ERROR, MUST HAVE DATA BYTE
	MOVB	R0, BUFFER(INDEX)	;STORE BYTE FROM PDP-8 IN BUFFER
	INC	INDEX			;INCREMENT INDEX
	CMP	INDEX, #200		;SEE IF STILL WITHIN BUFFER
	BLT	FROM8			;YEP, GO GET SOME MORE
;
;END OF BUFFER, WRITE ON FLOPPY BEFORE ACCEPTING MORE
;
	JSR	PC, WRITE		;WRITE OUT FULL BUFFER ONTO DISK
	JSR	PC, BUMP		;BUMP TO NEXT SECTOR
	CLR	INDEX			;RESET BUFFER INDEX
;
	BR	FROM8			;GET ANOTHER COMMAND/DATA WORD
;
;
;SYNTAX ERROR SOMEWHERE -- INFORM USER AND QUIT
;
SYNERR:	.PRINT	#SYNTAX
	.EXIT
;
;
;SEND BYTE PAIR TO PDP-8
;
;FIRST, WE HAVE TO BECOME SLAVE, BY PDP-8 "DEMANDING" TO BE MASTER
;
;
TO8:	JSR	PC, WAIT8		;WAIT FOR PDP-8 TO DEMAND MASTER STATUS
	MOVB	BUFFER(INDEX), R0	;GET PROPER BYTE
	MOV	R0, @#DROUT		;SEND TO PDP-8
	JSR	PC, WAIT8		;WAIT FOR PDP-8 TO ACCEPT
	INC	INDEX			;BUMP INDEX
	MOVB	BUFFER(INDEX), R0	;GET SECOND BYTE OF PAIR
	MOV	R0, @#DROUT		;SEND TO PDP-8
	JSR	PC, WAIT8		;WAIT FOR PDP-8 TO ACCEPT
	INC	INDEX			;BUMP INDEX
	CMP	INDEX, #200		;SEE IF STILL WITHIN BUFFER
	BLT	3$			;YEP, SKIP READ-IN
;
;END OF BUFFER, READ IN NEXT FLOPPY SECTOR
;
	JSR	PC, BUMP		;BUMP TO NEXT SECTOR
	JSR	PC, READ		;READ IN ANOTHER BUFFER'S WORTH
	CLR	INDEX			;RESET INDEX
;
;BEFORE RETURNING, REASSERT OUR "MASTER"-Y
;
3$:	CLR	@#DROUT			;DEMAND TO BE MASTER
	BR	FROM8			;GET ANOTHER COMMAND/DATA WORD
;
;
;WAIT FOR PDP-8 FLAG TO COME HIGH
;IF WE ARE MASTER, MEANS PDP-8 HAS DATA FOR US
;IF WE ARE SLAVE, MEANS PDP-8 HAS ACCEPTED DATA FROM US
;
WAIT8:	TST	@#DRCSR			;CHECK FLAG
	BPL	WAIT8			;HANG UNTIL IT COMES HIGH
	RTS	PC			;THEN EXIT
;
;
;
;SUBROUTINE TO BUMP DISK SECTOR
;
BUMP:	INC	SECTOR			;INCREMENT SECTOR
	CMP	SECTOR, #^D 26		;BE SURE STILL IN TRACK
	BGT	1$			;SKIP IF NOT SO
	RTS	PC			;ELSE EXIT
;
1$:	MOV	#1, SECTOR		;RESET SECTOR
	INC	TRACK			;BUMP TRACK
	CMP	TRACK, #^D 76		;BE SURE STILL ON DISKETTE
	BGT	2$			;SKIP IF NOT SO
	RTS	PC			;ELSE EXIT
;
;DISKETTE FULL -- OUTPUT WARNING AND QUIT
;
2$:	.PRINT	#DXFULL			;WARNING
	.EXIT				;QUIT
;
;
;RESET SOFTWARE FLAGS
;
RESET:	CLR	TRACK			;RESET TRACK
	MOV	#1, SECTOR		;AND SECTOR
	CLR	RWBIT			;RESET COMMAND TO READ FLOPPY
	CLR	INDEX			;RESET BUFFER INDEX
	RTS	PC			;RETURN
;
;
;SUBROUTINE TO READ SECTOR FROM DISKETTE
;
READ:	.SPFUN	#EYEOWE, #0, #377, #DXBUFF, TRACK, SECTOR, #0	;READ AND WAIT
	BCS	RDERR			;BRANCH IF READ ERROR
	RTS	PC			;RETURN
;
RDERR:	.PRINT	#MRDERR			;INFORM USER OF ERROR
	.PRINT	#TRK			;RETURN TRACK AND SECTOR NUMBER
	MOV	TRACK, R0
	JSR	PC, TYPER
	.PRINT	#SEC
	MOV	SECTOR, R0
	JSR	PC, TYPER
	.TTYOUT	#15
	.TTYOUT	#12
	RTS	PC			;AND RETURN, IGNORING ERROR
;
;SUBROUTINE TO WRITE SECTOR ON DISKETTE
;
WRITE:	.SPFUN	#EYEOWE, #0, #376, #DXBUFF, TRACK, SECTOR, #0	;WRITE AND WAIT
	BCS	WRERR			;BRANCH IF WRITE ERROR
	RTS	PC			;AND RETURN
;
WRERR:	.PRINT	#MWRERR			;INFORM USER OF ERROR
	.PRINT	#TRK			;RETURN TRACK AND SECTOR NUMBER
	MOV	TRACK, R0
	JSR	PC, TYPER
	.PRINT	#SEC
	MOV	SECTOR, R0
	JSR	PC, TYPER
	.TTYOUT	#15
	.TTYOUT	#12
1$:	RTS	PC			;AND RETURN
;
;
;OCTAL TYPE OUT ROUTINE FOR ERRORS
;
TYPER:	MOV	R1, -(SP)		;SAVE WORK REGISTER
	MOV	R0, R1			;SAVE DIVIDEND
	CLR	R0
	DIV	#10, R0			;DIVIDE BY 8
	BEQ	1$			;SKIP RECURSION IF FINISHED
	JSR	PC, TYPER		;RECURSION FOR NEXT DIGIT
1$:	ADD	#'0, R1			;MAKE REMAINDER ASCII DIGIT
	.TTYOUT	R1			;TYPE IT OUT
	MOV	(SP)+, R1		;RESTORE WORK REGISTER
	RTS	PC			;AND EXIT
;
;
;
;ERROR MESSAGES
;
MDXERR:	.ASCIZ	"CANNOT ACCESS DX1 -- FATAL!!"
;
SYNTAX:	.ASCIZ	"COMMAND/DATA SYNTAX ERROR -- FATAL!!"
;
DXFULL:	.ASCIZ	"DISKETTE FULL -- FATAL!!"
;
MRDERR:	.ASCIZ	"ERROR ON READ, IGNORED"
;
MWRERR:	.ASCIZ	"ERROR ON WRITE, IGNORED"
;
TRK:	.ASCII	"TRACK -- "
	.BYTE	200
;
SEC:	.ASCII	"  SECTOR -- "
	.BYTE	200
;
	.EVEN
;
;
;DATA STORAGE AREA
;
;
;
DXBUFF:	.WORD	0			;INITIAL ZERO WORD FOR .SPFUN
BUFFER:	.BLKB	200			;DISK BUFFER AREA, ONE SECTOR
	.EVEN
;
DX1:	.RAD50	"DX1"			;DX1
	.WORD	0			;NON-FILE STRUCTURED
;
EYEOWE:	.BLKW	6			;I/O EMT BLOCK
;
SPACE:					;HANDLER GOES HERE
;
	.END	START
