#!/bin/sh -x 
cc -O -o dumprk05 dumprk05.c
cc -O -o restrk05 restrk05.c
cc -O -o dumprx01 dumprx01.c
cc -O -o restrx01 restrx01.c
cc -O -o dumptd8e dumptd8e.c
cc -O -o resttd8e resttd8e.c
cc -O -o sendtape sendtape.c
cc -O -o dumbterm dumbterm.c
cc -O -o blkdectp blkdectp.c
