/5	MACREL ORIGIN CODE
/	17-AUG-78	FIXED UNKNOWN ORIGINS
	.INCLUDE MGLOB.MA
	.ASECT MACORG,LEVEL=1,OVERLAY=6
/
/
/
/
/
/
/
/
/
/COPYRIGHT  (C)  1977 BY DIGITAL EQUIPMENT CORPORATION
/
/
/
/
/
/
/
/
/
/
/THE INFORMATION IN THIS DOCUMENT IS SUBJECT TO CHANGE WITHOUT NOTICE
/AND SHOULD NOT BE CONSTRUED AS A COMMITMENT BY DIGITAL EQUIPMENT
/CORPORATION.  DIGITAL EQUIPMENT CORPORATION ASSUMES NO RESPONSIBILITY
/FOR ANY ERRORS THAT MAY APPEAR IN THIS DOCUMENT.
/
/THE SOFTWARE DESCRIBED IN THIS DOCUMENT IS FURNISHED TO THE PURCHASER
/UNDER A LICENSE FOR USE ON A SINGLE COMPUTER SYSTEM AND CAN BE COPIED
/(WITH INCLUSION OF DIGITAL'S COPYRIGHT NOTICE) ONLY FOR USE IN SUCH
/SYSTEM, EXCEPT AS MAY OTHERWISE BE PROVIDED IN WRITING BY DIGITAL.
/
/DIGITAL EQUIPMENT CORPORATION ASSUMES NO RESPONSIBILITY FOR THE USE
/OR RELIABILITY OF ITS SOFTWARE ON EQUIPMENT THAT IS NOT SUPPLIED BY
/DIGITAL.
/
/
/
/
/
/
/
/
/
/
	.EXTERNAL ASEMLV,BACKUP,BRANCH,CREF,CRLF,DPRINT,ENTER,EOS,ERROR,EXPR
	.EXTERNAL FSCHEK,GETCHR,GETKAR,GETSYM,LETTER,LISTER,LOOKUP,ORIG,OUT,PARSYM
	.EXTERNAL PASS3,POP,PUSH,PUNBIT,PUTBIT,PUTSYM,PUXBIN,READLN,ROTL6,SCAN
	.EXTERNAL PUTLC,PUTBIT
	FIELD 3
	.GLOBAL ORIGI

	*2000

	RELOC 2400

	7

ORIGI,	TAD PC
	AND QQ7600
	DCA LITPAG
	DCA I (EXTPC	/TEMPORARILY HAVE KNOWN ORIGIN
/	TAD CURSCT
/	DCA SYMNUM
/	JMS I QQGETSYM
/	TAD SYMSCT
/	IAC
/	SZA CLA
/	JMP NORG
/	TAD SYMVAL
/	TAD QM200
/	SNA CLA
/	JMP NORG	/BUT ONLY IF HIGH .NE. 200
/	TAD QQ200	/LOW OF -1 MEANS LOW WAS ACTUALLY 200
/	DCA SYMSCT
/	JMS I QQPUTSYM	/BUG IF FIRST DIRECTIVE IN ASECT IS PAGE ****
/NORG,	TAD SYMSCT	/GET OLD LOW
/	CLL CIA
/	TAD PC
/	SZL CLA
/	JMP .+4
/	TAD PC		/NEW LOW
/	DCA SYMSCT
/	JMS I QQPUTSYM	/WRITE IT BACK OUT
	TAD EXPCOD
	SZA CLA
	JMP LNKORG
	TAD EXPREL
	SNA
	JMP I (BYEP	/ORIGIN MAY BE ABSOLUTE
	CIA
	TAD CURSCT	/OR RELATIVE TO CURRENT SECT
	SNA CLA
	JMP I (BYEP
/ER58,	JMS I QQERROR	/BUT NOT ANYTHING ELSE
LNKORG,	TAD EXPCOD
	SPA CLA
	JMP LNKSTK
	TAD EXPABS	/PUSH IT ONTO STACK
	SZA CLA
	TAD (PSHVAL-PSHLSD
	TAD (PSHLSD
	DCA PSHT
	TAD EXPREL
	SZA
	JMS I (GETLSD
	TAD PSHT
	JMS I (PUTLC
	TAD EXPABS
	SZA
	JMS I (PUTBIT
LNKSTK,	TAD (STKORG	/ORIGIN IS ON TOP OF STACK
	JMS I (PUTLC
	ISZ I (EXTPC	/NOTE PRESENCE OF EXTERNAL ORIGIN
	JMP I (BYEB

/NEW HIGH PC MUST BE COMPUTED AT ODD HOURS IN CASE USER ORIGINS
/UP, THEN DOWN, THEN CHANGES SECT.
/I.E. LAST PC AINT NECESSARILY THE HIGHEST PC
PSHT,	0
	PAGE
	0
	PAGE
	RELOC
