$JOB COMPILE HANDLERS FOR SYKES FLOPPY DISK SYSTEM
/ DON'T KNOW EXACTLY WHERE FLPP: IS, OR IT WOULD HAVE BEEN INCLUDED.
.PAL SYS:<SYKES.PA
.PAL SYS:<AUXB.PA
.PAL SYS:<RF08NS.PA
.PAL SYS:<GT.PA
.PAL SYS:<LSPT33.PA
.PAL SYS:<TEXT.PA
$END
