$JOB COMPARE P?S/8 "A" SOURCES ON DEVICE "FROM:" AND DEVICE "TO:"
/	LAST EDIT:	23-FEB-1988	20:00:00	CJL
.R CMPARE
*TO:MOVEMA.BI,FROM:MOVEMA.BI
*TO:MOVEMB.BI,FROM:MOVEMB.BI
*TO:PQSASM.BI,FROM:PQSASM.BI
*TO:COMGEN.BI,FROM:COMGEN.BI
*TO:CMPARA.BI,FROM:CMPARA.BI
*TO:CMPARB.BI,FROM:CMPARB.BI
*TO:ASCODE.PA,FROM:ASCODE.PA
*TO:DTCOPY.PA,FROM:DTCOPY.PA
*TO:DTFRMT.PA,FROM:DTFRMT.PA
*TO:RKLFMT.PA,FROM:RKLFMT.PA
*TO:MARK12.12,FROM:MARK12.12
*TO:TC12F.12,FROM:TC12F.12
*TO:FOCALZ.ZM,FROM:FOCALZ.ZM
*TO:FLOATZ.ZM,FROM:FLOATZ.ZM
*TO:PHOCAL.PA,FROM:PHOCAL.PA
*TO:ASMBLR.PA,FROM:ASMBLR.PA
*TO:BIN.PA,FROM:BIN.PA
*TO:MAP.PA,FROM:MAP.PA
*TO:BLKODT.PA,FROM:BLKODT.PA
*TO:LTBODT.PA,FROM:LTBODT.PA
*TO:LTDUMP.PA,FROM:LTDUMP.PA
*TO:L6DCON.PA,FROM:L6DCON.PA
*TO:OS8CON.PA,FROM:OS8CON.PA
*TO:LAP6W.PA,FROM:LAP6W.PA
*TO:CPSCON.PA,FROM:CPSCON.PA
*TO:RT11.PA,FROM:RT11.PA
*TO:LSPTCH.PA,FROM:LSPTCH.PA
*TO:PQSDTA.PA,FROM:PQSDTA.PA
*TO:PQSLTA.PA,FROM:PQSLTA.PA
*TO:PQSDSU.PA,FROM:PQSDSU.PA
*TO:PQSRXA.PA,FROM:PQSRXA.PA
*TO:PQSRKA.PA,FROM:PQSRKA.PA
*TO:PQSFLP.PA,FROM:PQSFLP.PA
*TO:PQSMON.PA,FROM:PQSMON.PA
$END
