$JOB MOVE P?S/8 "A" SOURCES FROM DEVICE "FROM:" TO DEVICE "TO:"
/	LAST EDIT:	23-FEB-1988	20:00:00	CJL
.COPY TO:<FROM:MOVEMA.BI,MOVEMB.BI,PQSASM.BI/U
.COPY TO:<FROM:COMGEN.BI,CMPARA.BI,CMPARB.BI/U
.COPY TO:<FROM:ASCODE.PA
.COPY TO:<FROM:DTCOPY.PA,DTFRMT.PA/U
.COPY TO:<FROM:RKLFMT.PA
.COPY TO:<FROM:MARK12.12,TC12F.12/U
.COPY TO:<FROM:FOCALZ.ZM,FLOATZ.ZM/U
.COPY TO:<FROM:PHOCAL.PA/U
.COPY TO:<FROM:ASMBLR.PA,BIN.PA/U
.COPY TO:<FROM:MAP.PA,BLKODT.PA/U
.COPY TO:<FROM:LTBODT.PA,LTDUMP.PA,L6DCON.PA/U
.COPY TO:<FROM:OS8CON.PA,LAP6W.PA/U
.COPY TO:<FROM:CPSCON.PA,RT11.PA/U
.COPY TO:<FROM:LSPTCH.PA
.COPY TO:<FROM:PQSDTA.PA,PQSLTA.PA,PQSDSU.PA,PQSRXA.PA,PQSRKA.PA/U
.COPY TO:<FROM:PQSFLP.PA
.COPY TO:<FROM:PQSMON.PA
$END
