# Instructions:
# Run 'pdp8' in this directory, and assuming socat and xterm are installed,
# the server should start automatically and the system should boot.
#br 7732; "e l; e ac; c"
set ttox0 8b
set lpt disable
# We need a system disk, a couple of scratch media.
# Currently, we set up rk0 with our OS/8 build environment.
# The TMP: device should get aliased to RKB0:.
at rk0 pqs8build.new
# Currently, we set up rk1 with the A: and B: source code.
at rk1 ab.new
# We set up two DECtape units:  DT0 will become our new PQS8.
at dt0 dt.out
# DT1: will be the SCR: device, where the binaries are built.
at dt1 scr.dt
# Set up the paper tape reader and punch to share a file.
at ptr os8con.bn
at ptp os8con.bn
echo Booting...
#set vc8 ena
b rk0
e l
e ac
