#!/usr/bin/expect -f

# Set -h to emulate a human typist.
set send_human {.3 .3 75 .3 9}
set timeout -1

# Set this for a scratch build
set rebuild 1
#set rebuild 0

# Remove the old PQS8, for a clean start.
spawn rm -f dt.out
wait

# Fire up a PDP-8, then walk it through the build steps.
spawn pdp8
expect {
	{..$} { exp_continue }
        {.$} { send "DATE 30-JUL-99\r" }
}
expect -re {\n\.$}
send "ASSIGN RKB0 TMP\r"
expect -re {\n\.$}
send "ASSIGN RKA1 A\r"
expect -re {\n\.$}
send "ASSIGN RKB1 B\r"
expect -re {\n\.$}
send "ASSIGN DTA1 SCR\r"
if { $rebuild == 1 } {
  expect -re {\n\.$}
  send "ZERO TMP:\r"
  expect -re {\n\.$}
  send "SUBMIT PQSASM/T\r"
  expect -re {END BATCH\r\n\r\n\.$}
}
send "DIR TMP:/F\r"
expect -re {\n\.$}
if { $rebuild == 1 } {
  send "SUBMIT COMGEN/T\r"
  expect -re {END BATCH\r\n\r\n\.$}
  #
  # We will need "COMGEN.DU" and "DTAGEN.DU" later, and this seems
  # to be the only place to stash them.
  # Likewise the locally grown BYHAND.DU.
  send "COPY SCR:<B:COMGEN.DU/A\r"
  expect -re {\n\.$}
  send "COPY SCR:<B:DTAGEN.DU/A\r"
  expect -re {\n\.$}
  send "COPY SCR:<B:BYHAND.DU/A\r"
  expect -re {\n\.$}
  send "COPY SCR:<B:README.TX/A\r"
  expect -re {\n\.$}
  send "COPY SCR:<B:TCBOOT.TX/A\r"
  expect -re {\n\.$}
}
send "COPY PTP:<TMP:OS8CON.BN\r"
expect -re {\n\.$}
send "DIR SCR:/F\r"
expect -re {\n\.$}
send "EX TMP:Z12K,TMP:PQSMON,TMP:PQSDTA,TMP:BIN,TMP:ODT,TMP:DUMP\r"
expect -re {\nsim> }
send "D SR 0\r"
expect -re {\nsim> }
send "C\r"
expect -re {\nsim> }
send "B DT\r"
expect -re {\n\a\.$}
#
# BUGBUG: Why is PQS8 ignoring every other character? As a workaround, I'm
# using send -h as necessary.
#
#
# Here we have a problem.  We want to run DUMP with input from "comgen.du".
# The only copy available to PQS8 is on unit 1 (formerly SCR:), after all
# the binaries.
#
# OS8CON is in the high speed reader, so load it.
# /F Use HSR; /P Load BIN tape; /V Use virtual loader.
send -h "BIN %</F/P/V\r"
 expect -re {TAPES?}
 send -h "N\r"
expect -re {\n\a\.$}
send "\r"
expect -re {\n\.$}
send -h "GET %\r"
expect -re {\n\a.$}
# Now we can convert our DUMP command files.
# COMGEN.DU       1172    15      16-JUN-69
# DTAGEN.DU       1211    4       16-JUN-69
# BYHAND.DU       1215    4       16-JUN-69
# "RUN %" runs the program we just loaded.
# "COMGEN<COMGEN" says copy COMGEN. to COMGEN (input side ignored)
# "/1" says from OS/8 on unit 1
# =1172 says the file starts at block 1172 (BUGBUG)
send -h "RUN % COMGEN,COMG2</1=1172\r"
expect -re {\n\a\.$}
send -h "CAT\r"
expect -re {\n\.$}
#
# Invoke DUMP to upgrade the installation.
# BUGBUG: CORE command is not installed yet!!
#
#send -h "DUMP COMGEN,COMG2\r"
send -h "DUMP COMGEN,COMG2\r"
expect -re {\n\a\.$}
send -h "CORE ALL\r"
expect -re {\n\a\.$}
#
# At this point, OS8CON should have an official copy in the DIRectory.
# Run that to get DTAGEN into the CATalog.
send -h "RUN OS8CON DTAGEN</1=1211\r"
expect -re {\n\a\.$}
#
# Now run DUMP with DTAGEN to get the rest of the DECtape.
send -h "DUMP DTAGEN\r"
expect -re {\n\a\.$}
#
# Run OS8CON to get BYHAND into the CATalog.
send -h "RUN OS8CON BYHAND</1=1215\r"
expect -re {\n\a\.$}
#
# Now run DUMP with BYHAND to apply the patches.
send -h "DUMP BYHAND\r"
expect -re {\n\a\.$}
#
# Do a SET RUBOUT BACKUP to align the TTY system area.
send -h "SET RUBOUT BACKUP\r"
expect -re {\n\a\.$}
#
# Remove the build scripts
send -h "KILL COMGEN\r"
expect -re {\n\.$}
send -h "KILL COMG2\r"
expect -re {\n\.$}
send -h "KILL DTAGEN\r"
expect -re {\n\.$}
send -h "KILL BYHAND\r"
expect -re {\n\.$}
#
# Run OS8CON to get README and TCBOOT into the CATalog.
# BUGBUG: Fix these block numbers!
send -h "RUN OS8CON README</1=1223\r"
expect -re {\n\a\.$}
send -h "RUN OS8CON TCBOOT</1=1227\r"
expect -re {\n\a\.$}
#
# Close SIMH cleanly.
send -h "\005"
expect -re {\nsim> }
send -h "q\r"
expect -re {file\r}
expect -re {file\r}
close
exit 0
