// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: c_us 
// c2: c_us 
// c3: c_us 
// c4: cpol_use 
// e1: sn7402 
module m623x (a1, b1, c1, d1, d2, e1, e2, f1, f2, h1, h2, j1, j2, k1, k2, l1, l2, m1, m2, n1, n15v, n2, n_t_14x, n_t_16x, n_t_17x, n_t_18x, n_t_2x, p1, p2, r1, r2, s1, s2, t2, u2, v2);
input a1;
input b1;
input c1;
output d1;
input d2;
output e1;
input e2;
input f1;
input f2;
input h1;
output h2;
input j1;
output j2;
output k1;
input k2;
output l1;
input l2;
input m1;
input m2;
input n1;
output n15v;
output n2;
output n_t_14x;
output n_t_16x;
output n_t_17x;
output n_t_18x;
output n_t_2x;
input p1;
output p2;
output r1;
input r2;
output s1;
input s2;
input t2;
output u2;
output v2;


wire aa1;
wire ab1;
wire ab2;
wire ac1;
wire ac3_h;
wire ad1;
wire ad2;
wire adder3;
wire adder4;
wire adder5;
wire ae1;
wire ae2;
wire ae2w;
wire af1;
wire af1w;
wire af2;
wire ah1;
wire ah2;
wire aj1;
wire aj1w;
wire aj2;
wire ak1;
wire ak2;
wire al1;
wire al2;
wire al2w;
wire am1;
wire am1w;
wire am2;
wire am2w;
wire an1;
wire an1w;
wire an2;
wire ap1;
wire ap1w;
wire ap2;
wire ar1;
wire ar2;
wire ar2w;
wire as1;
wire as2;
wire at2;
wire at2w;
wire au1;
wire au2;
wire au2w;
wire av1;
wire av1w;
wire av2;
wire av2w;
wire b2;
wire ba1;
wire bb2;
wire bc1;
wire bd2;
wire be2;
wire bf1;
wire bf2;
wire bh1;
wire bh2;
wire bj1;
wire bl1;
wire bl2;
wire bm2;
wire bu2;
wire bv1;
wire bv2;
wire c3;
wire mb2_h;
wire mb2_l;
wire mb3_h;
wire mb3_l;
wire n_t_10x;
wire n_t_12x;
wire n_t_13x;
wire n_t_15x;
wire n_t_19x;
wire n_t_1x;
wire n_t_20x;
wire n_t_21x;
wire n_t_3x;
wire n_t_5x;
wire n_t_6x;
wire tck;
wire tdo;
assign n_t_13x = ~(f2
                    | e2);
assign n_t_3x = ~(f2
                   | d2);
assign n_t_12x = ~(c1
                    | b1);
assign n_t_1x = ~(c1
                   | a1);
// e2: sn7402 
assign n_t_16x = ~(m2
                    | l2);
assign n_t_14x = ~(m2
                    | k2);
assign n_t_17x = ~(j1
                    | h1);
assign n_t_15x = ~(j1
                    | f1);
// e3: sn7402 
assign n_t_20x = ~(t2
                    | s2);
assign n_t_18x = ~(t2
                    | r2);
assign n_t_21x = ~(p1
                    | n1);
assign n_t_19x = ~(p1
                    | m1);
// r1: r_us_ 
// r2: r_us_ 
// r3: r_us_ 
// r4: r_us_ 
// r5: r_us_ 
// r6: r_us_ 
// r7: r_us_ 
// r8: r_us_ 
// r9: r_us_ 
// r10: r_us_ 
// r11: r_us_ 
// r12: r_us_ 
// open collector 'wire-or's 
endmodule
