$JOB NP-8 SPUNLACED INSPECTION INSPECTION SYSTEM MANUAL
.R RUNOFF
*RXA1:TIPAG.RO,SMI.RO,SMII.RO,SMIII.RO,SMIV.RO,SMV.RO,SMVI.RO,SMVII.RO$
.R RUNOFF
*RXA1:HEAD.RO,SMVIII.RO$
.R RUNOFF
*RXA1:APDXI.RO
*RXA1:APDXII.RO
*RXA1:APDIII.RO
*RXA1:APDXIV.RO
$END
