$JOB    File Name = PROG
/       THIS JOB ASSEMBLES A SABR PROGRAM, PUTTING THE LISTING
/       ON DSK: AND THEN TYPESETTING THE LISTING TO LPT:
/       WITH PAGINATION AND A HEADER SHOWING NAME AND DATE.
/
/       TO USE, XEDIT THIS FILE BEFORE SUBMITTING IT, AND
/       CHANGE THE NAME OF THE SOURCE BEING ASSEMBLED.
/
/       .XEDIT FLIP:SABRTS.BI
/       < XEDIT 1.58 HRL >
/       >P
/       $JOB File Name = oldname
/       >C/oldname/newname/*
/       >E
/       .SU FLIP:SABRTS
/
.DEL DSK:TEMP.TM
.COMP ,DSK:TEMP.TM<FLIP:PROG.SB-NB/S
.TS BAT:,DSK:TEMP.TM/8-L
)P LM0 RM80
)H          PROG       
$END
