#!/bin/sh

LOGPATH=http://svn.so-much-stuff.com/svn/trunk

svn log -v -r "{2014-12-31}:{2014-1-1}" >y2014.txt $LOGPATH

# svn log -v -r "{2013-12-31}:{2013-1-1}" >y2013.txt $LOGPATH

# svn log -v -r "{2012-12-31}:{2012-1-1}" >y2012.txt $LOGPATH

# svn log -v -r "{2011-12-31}:{2011-1-1}" >y2011.txt $LOGPATH
