// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// e1: sn7400 
module m900d (n_t_10x, n_t_11x, n_t_12x, n_t_13x, n_t_14x, n_t_15x, n_t_16x, n_t_17x, n_t_18x, n_t_19x, n_t_1x, n_t_20x, n_t_21x, n_t_22x, n_t_23x, n_t_24x, n_t_25x, n_t_26x, n_t_27x, n_t_28x, n_t_29x, n_t_2x, n_t_30x, n_t_31x, n_t_32x, n_t_33x, n_t_34x, n_t_35x, n_t_36x, n_t_37x, n_t_38x, n_t_39x, n_t_3x, n_t_40x, n_t_41x, n_t_42x, n_t_43x, n_t_44x, n_t_45x, n_t_46x, n_t_47x, n_t_48x, n_t_49x, n_t_4x, n_t_50x, n_t_51x, n_t_52x, n_t_53x, n_t_54x, n_t_55x, n_t_56x, n_t_57x, n_t_58x, n_t_59x, n_t_5x, n_t_60x, n_t_6x, n_t_7x, n_t_8x, n_t_9x);
input n_t_10x;
input n_t_11x;
input n_t_12x;
input n_t_13x;
input n_t_14x;
input n_t_15x;
input n_t_16x;
input n_t_17x;
output n_t_18x;
output n_t_19x;
input n_t_1x;
output n_t_20x;
output n_t_21x;
output n_t_22x;
output n_t_23x;
output n_t_24x;
input n_t_25x;
input n_t_26x;
input n_t_27x;
input n_t_28x;
input n_t_29x;
output n_t_2x;
input n_t_30x;
output n_t_31x;
output n_t_32x;
output n_t_33x;
output n_t_34x;
output n_t_35x;
output n_t_36x;
output n_t_37x;
output n_t_38x;
output n_t_39x;
output n_t_3x;
output n_t_40x;
output n_t_41x;
output n_t_42x;
input n_t_43x;
input n_t_44x;
input n_t_45x;
input n_t_46x;
input n_t_47x;
input n_t_48x;
input n_t_49x;
output n_t_4x;
input n_t_50x;
input n_t_51x;
input n_t_52x;
input n_t_53x;
input n_t_54x;
output n_t_55x;
output n_t_56x;
output n_t_57x;
output n_t_58x;
output n_t_59x;
output n_t_5x;
output n_t_60x;
output n_t_6x;
input n_t_7x;
input n_t_8x;
input n_t_9x;


assign n_t_60x = ~n_t_50x;
assign n_t_21x = ~n_t_14x;
assign n_t_4x = ~n_t_7x;
assign n_t_41x = ~n_t_44x;
// e2: sn7400 
assign n_t_2x = ~n_t_1x;
assign n_t_22x = ~n_t_13x;
assign n_t_20x = ~n_t_15x;
assign n_t_35x = ~n_t_26x;
// e3: sn7400 
assign n_t_36x = ~n_t_27x;
assign n_t_59x = ~n_t_51x;
assign n_t_3x = ~n_t_11x;
assign n_t_42x = ~n_t_49x;
// e4: sn7400 
assign n_t_33x = ~n_t_29x;
assign n_t_57x = ~n_t_53x;
assign n_t_5x = ~n_t_10x;
assign n_t_40x = ~n_t_45x;
// e5: sn7400 
assign n_t_19x = ~n_t_16x;
assign n_t_39x = ~n_t_46x;
assign n_t_32x = ~n_t_25x;
assign n_t_6x = ~n_t_9x;
// e6: sn7400 
assign n_t_37x = ~n_t_47x;
assign n_t_55x = ~n_t_54x;
assign n_t_31x = ~n_t_30x;
assign n_t_23x = ~n_t_17x;
// e7: sn7400 
assign n_t_34x = ~n_t_28x;
assign n_t_56x = ~n_t_48x;
assign n_t_58x = ~n_t_52x;
// e8: sn7400 
assign n_t_24x = ~n_t_8x;
assign n_t_38x = ~n_t_43x;
assign n_t_18x = ~n_t_12x;
// open collector 'wire-or's 
endmodule
