// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
module m900d (aa1, ab1, ad1, ad2, ae1, ae2, af1, af2, ah1, ah2, aj1, aj2, ak1, ak2, al1, al2, am1, am2, an2, ap1, ap2, ar1, ar2, as1, as2, at2, au2, av2, ba1, bb1, bc1, bd1, bd2, be1, be2, bf1, bh1, bj1, bj2, bk1, bk2, bl1, bl2, bm2, br2, bs1, bs2, bu2, bv2, c1_l, cpma_disable_l, d_l, data10_l, data11_l, data2_l, data3_l, data4_l, data6_l, data7_l, data8_l, data9_l, f_l, f_set_l, ind1_l, ind2_l, init, int_in_progress_l, int_rqst_l, internal_io_l, io_pause_l, ir00_l, ir01_l, key_ctl_l, load_addr, load_cntl, md06_l, md07_l, md08_l, md09_l, md10_l, md11_l, n15v, n_t_10x, n_t_11x, n_t_12x, n_t_13x, n_t_14x, n_t_15x, n_t_16x, n_t_17x, n_t_1x, n_t_25x, n_t_26x, n_t_27x, n_t_28x, n_t_29x, n_t_30x, n_t_43x, n_t_44x, n_t_45x, n_t_46x, n_t_47x, n_t_48x, n_t_49x, n_t_50x, n_t_51x, n_t_52x, n_t_53x, n_t_54x, n_t_7x, n_t_8x, n_t_9x, rcra, rcrb, rcse, skip_l, tp1, tp2, tp3, tp4, ts1_l, user_mode_l);
output aa1;
output ab1;
output ad1;
output ad2;
output ae1;
output ae2;
output af1;
output af2;
output ah1;
output ah2;
output aj1;
output aj2;
output ak1;
output ak2;
output al1;
output al2;
output am1;
output am2;
output an2;
output ap1;
output ap2;
output ar1;
output ar2;
output as1;
output as2;
output at2;
output au2;
output av2;
output ba1;
output bb1;
output bc1;
output bd1;
output bd2;
output be1;
output be2;
output bf1;
output bh1;
output bj1;
output bj2;
output bk1;
output bk2;
output bl1;
output bl2;
output bm2;
output br2;
output bs1;
output bs2;
output bu2;
output bv2;
output c1_l;
output cpma_disable_l;
output d_l;
output data10_l;
output data11_l;
output data2_l;
output data3_l;
output data4_l;
output data6_l;
output data7_l;
output data8_l;
output data9_l;
output f_l;
output f_set_l;
output ind1_l;
output ind2_l;
output init;
output int_in_progress_l;
output int_rqst_l;
output internal_io_l;
output io_pause_l;
output ir00_l;
output ir01_l;
output key_ctl_l;
output load_addr;
output load_cntl;
output md06_l;
output md07_l;
output md08_l;
output md09_l;
output md10_l;
output md11_l;
output n15v;
output n_t_10x;
output n_t_11x;
output n_t_12x;
output n_t_13x;
output n_t_14x;
output n_t_15x;
output n_t_16x;
output n_t_17x;
output n_t_1x;
output n_t_25x;
output n_t_26x;
output n_t_27x;
output n_t_28x;
output n_t_29x;
output n_t_30x;
output n_t_43x;
output n_t_44x;
output n_t_45x;
output n_t_46x;
output n_t_47x;
output n_t_48x;
output n_t_49x;
output n_t_50x;
output n_t_51x;
output n_t_52x;
output n_t_53x;
output n_t_54x;
output n_t_7x;
output n_t_8x;
output n_t_9x;
output rcra;
output rcrb;
output rcse;
output skip_l;
output tp1;
output tp2;
output tp3;
output tp4;
output ts1_l;
output user_mode_l;


wire ac2_8_0;
wire ac2_h;
wire ac3_h;
wire ac3_l;
wire ac4_11_0;
wire ac_0;
wire ac_to_bus_l;
wire b1;
wire b_dixy_l;
wire bit11;
wire btp3;
wire c0_l;
wire c3;
wire cf1;
wire chan_l;
wire clk;
wire clock;
wire col_red_l;
wire color_l;
wire d1;
wire dad_or_dst_l;
wire data02_l;
wire data06_l;
wire data07_l;
wire data08_l;
wire data09_l;
wire data0_l;
wire data1_l;
wire data5_l;
wire del_1_l;
wire df_enable;
wire di02_l;
wire di03;
wire di04;
wire di05;
wire di06;
wire di07;
wire di08;
wire di09;
wire di10;
wire di11;
wire dly_done_l;
wire ema0_l;
wire ema1_l;
wire ema2_l;
wire erase_l;
wire f1;
wire gtf_or_ind;
wire initialize;
wire int_in_prog;
wire interrupt_l;
wire io19;
wire io21;
wire io22;
wire io23;
wire io24;
wire io25;
wire io26;
wire io27;
wire io28;
wire io29;
wire io30;
wire io31;
wire io32;
wire io33;
wire io34;
wire io35;
wire io36;
wire io37;
wire io38;
wire io39;
wire io40;
wire io42;
wire io59;
wire io70;
wire ir0_l;
wire ir1_l;
wire j1;
wire k1;
wire la_enable_l;
wire last_step_l;
wire ld_del_l;
wire link_l;
wire load_cont_l;
wire load_x_l;
wire load_y_l;
wire m2;
wire ma2_h;
wire ma3_h;
wire ma3_l;
wire md00_l;
wire md01_l;
wire md02_l;
wire md03_l;
wire md04_l;
wire md05_l;
wire md3_l;
wire md4_l;
wire md5_l;
wire md6_l;
wire md7_l;
wire md8_l;
wire md9_l;
wire modeb;
wire mq0_l;
wire mq_load;
wire n1;
wire n2;
wire n3v;
wire n3v3;
wire non_store_l;
wire p4_pclr;
wire p4_pclr_l;
wire pause_l;
wire pc3_h;
wire pc3_l;
wire power_ok;
wire r1;
wire red_delay;
wire restart;
wire rom_11_l;
wire rom_12_l;
wire rom_14_l;
wire rom_15_l;
wire rom_17_l;
wire rom_24_l;
wire rtf;
wire run_l;
wire set_done;
wire sgt_l;
wire tck;
wire tck2;
wire tdi;
wire tdo;
wire tdo2;
wire tms;
wire tms2;
wire tp2_d;
wire tp_aa1;
wire tp_ab1;
wire ts3_l;
wire ts4_l;
wire ts_disable_l;
wire write_thru_l;
wire x_analog;
wire y04;
// code nodes 
// equations 
// e1: sn7400 
// e2: sn7400 
// e3: sn7400 
// e4: sn7400 
// e5: sn7400 
// e6: sn7400 
// e7: sn7400 
assign n_t_15x = 1'b1;
// e8: sn7400 
assign n_t_7x = 1'b0;
// r1: r_us_ 
// r2: r_us_ 
// r3: r_us_ 
// r4: r_us_ 
// r5: r_us_ 
// r6: r_us_ 
// r7: r_us_ 
// r8: r_us_ 
// r9: r_us_ 
// r10: r_us_ 
// r11: r_us_ 
// r12: r_us_ 
// r13: r_us_ 
// r14: r_us_ 
// r15: r_us_ 
// r16: r_us_ 
// r17: r_us_ 
// r18: r_us_ 
// r19: r_us_ 
// r20: r_us_ 
// r21: r_us_ 
// r22: r_us_ 
// r23: r_us_ 
// r24: r_us_ 
// r25: r_us_ 
// r26: r_us_ 
// r27: r_us_ 
// r28: r_us_ 
// r29: r_us_ 
// r30: r_us_ 
// open collector 'wire-or's 
endmodule
