$JOB MULTI8 SYSTEM GENERATION FOR BOEING
.DEL SWPFIL.M8,MULTI8.SV,SPOOL.*
.PAL M,M<CONFIG,M1,M2,M3,M4,M5(NDG)
*/N$
.RU DSK:GLOBL
*MS.PA<SYMBLS.GS,M.LS
.PAL MS-NB,MONDUM/L
.SAVE SYS MONDUM
.DEL M.LS,MONDUM.BN
.PAL CD<MS,CD.TK
.PAL OD<MS,OD.TK
.PAL PA<MS,PA.TK
.PAL MA<MS,MA.TK
.PAL DI<MS,DI.TK
.PAL LI<MS,LI.TK
.PAL IT<MS,IT.TK
.PAL BS<MS,BS.TK
.PAL BE<MS,BE.TK
.PAL CB<MS,CB.TK
.PAL ST<MS,ST.TK
.PAL TA<MS,TA.TK
.PAL DS<MS,DS.TK
.R MULTI8
*CD,OD,PA,MA,DI,LI,IT,BS,CB
*BE,ST,TA,DS/N$

.PAL LP<MS,LP.TK
.PAL LE<MS,LE.TK
.R MULTI8
*LP,LE/N$

.PAL PP<MS,PP.TK
.PAL PE<MS,PE.TK
.R MULTI8
*PP,PE/N$

.PAL PR<MS,PR.TK
.PAL RE<MS,RE.TK
.R MULTI8
*PR,RE/N$

/.PAL ME<MS,ME.TK
/.R MULTI8
/*ME/N$

.PAL PL<MS,PL.TK
.PAL GE<MS,GE.TK
.R MULTI8
*PL,GE/N$

$END
