// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
module m516x (a1, b1, c0_l, c1, c1_l, d1, d2, data0_l, data10_l, data11_l, data1_l, data2_l, data3_l, data4_l, data5_l, data6_l, data7_l, data8_l, data9_l, e1, e2, f1, f2, h1, h2, initialize, int_rqst_l, internal_io_l, io_pause_l, j1, j2, k1, k2, l1, l2, m1, m2, md03_l, md04_l, md05_l, md06_l, md07_l, md08_l, md09_l, md10_l, md11_l, n1, n15v, n2, n_t_18x, p1, p2, r1, r2, s1, s2, skip_l, t2, tp3, u1, u2, v2);
input a1;
input b1;
output c0_l;
input c1;
output c1_l;
input d1;
input d2;
output data0_l;
output data10_l;
output data11_l;
output data1_l;
output data2_l;
output data3_l;
output data4_l;
output data5_l;
output data6_l;
output data7_l;
output data8_l;
output data9_l;
output e1;
input e2;
input f1;
input f2;
input h1;
input h2;
output initialize;
output int_rqst_l;
output internal_io_l;
output io_pause_l;
input j1;
output j2;
input k1;
input k2;
output l1;
input l2;
input m1;
input m2;
output md03_l;
output md04_l;
output md05_l;
output md06_l;
output md07_l;
output md08_l;
output md09_l;
output md10_l;
output md11_l;
input n1;
output n15v;
input n2;
output n_t_18x;
input p1;
output p2;
input r1;
input r2;
output s1;
input s2;
output skip_l;
input t2;
output tp3;
output u1;
input u2;
output v2;


wire aa1;
wire ab1;
wire ab2;
wire ac1;
wire ac3_h;
wire ad1;
wire ad2;
wire adder3;
wire adder4;
wire adder5;
wire ae1;
wire ae2;
wire ae2w;
wire af1;
wire af1w;
wire af2;
wire ah1;
wire ah2;
wire aj1;
wire aj1w;
wire aj2;
wire ak1;
wire ak2;
wire al1;
wire al2;
wire al2w;
wire am1;
wire am1w;
wire am2;
wire am2w;
wire an1;
wire an1w;
wire an2;
wire ap1;
wire ap1w;
wire ap2;
wire ar1;
wire ar2;
wire ar2w;
wire as1;
wire as2;
wire at2;
wire at2w;
wire au1;
wire au2;
wire au2w;
wire av1;
wire av1w;
wire av2;
wire av2w;
wire b2;
wire ba1;
wire bb2;
wire bc1;
wire bd2;
wire be2;
wire bf1;
wire bf2;
wire bh1;
wire bh2;
wire bj1;
wire bl1;
wire bl2;
wire bm2;
wire bu2;
wire bv1;
wire bv2;
wire c3;
wire e2rc;
wire mb2_h;
wire mb2_l;
wire mb3_h;
wire mb3_l;
wire mux_out_l;
wire n_t_10x;
wire n_t_2x;
wire n_t_4x;
wire n_t_5x;
wire n_t_6x;
wire select_remote_l;
wire tck;
wire tdo;
// code nodes 
// equations 
// c1: c_us 
// c2: c_us 
// c3: c_us 
// c4: c_us 
// c5: c_us 
// e1: sn7420 
assign e1 = ~(b1 & a1 & c1 & d1);
assign j2 = ~(h2 & f2 & e2 & d2);
// e2: sn7420 
assign l1 = ~(h1 & f1 & j1 & k1);
assign p2 = ~(n2 & m2 & l2 & k2);
// e3: sn7420 
assign s1 = ~(m1 & n1 & p1 & r1);
assign v2 = ~(u2 & t2 & s2 & r2);
// r1: r_us_ 
// r2: r_us_ 
// r3: r_us_ 
// r4: r_us_ 
// r5: r_us_ 
// r6: r_us_ 
// r7: r_us_ 
// r8: r_us_ 
// r9: r_us_ 
// r10: r_us_ 
// r11: r_us_ 
// r12: r_us_ 
// r13: r_us_ 
// r14: r_us_ 
// r15: r_us_ 
// r16: r_us_ 
// r17: r_us_ 
// r18: r_us_ 
// r19: r_us_ 
// open collector 'wire-or's 
endmodule
