$JOB (F1SAV.BI)  CREATE BINARY LIBRARY FOR MAST FIELD  -1-   8-AUG-91

.DEL RXA1:MSTF1.BN

.R PIP
*RXA1:MSTF1.BN<RXA1:LINESP.BN,SGATE.BN,RGATE.BN,PGATE.BN,DEF2.BN/B
*RXA1:MSTF1.BN<RXA1:MSTF1.BN,BUILD.BN,DIGINP.BN/B
*RXA1:MSTF1.BN<RXA1:MSTF1.BN,MEMORY.BN,TRAYCK.BN,F1COMM.BN/B

.SQ RXA1:/O

.COPY SYS:<RXA1:MSTF1.BN

$END

