$JOB (F3GEN.BI)  GENERATE MAST FIELD  -3-	8-AUG-91

.DEL RXA1:*.BN

.SQ RXA1:/O

.PAL RXA1:ROLLDT<RXA1:MSTPAR,ROLLDT,F3COMM,CRTTXT

.PAL RXA1:CRTCTR<RXA1:MSTPAR,CRTCTR,F3COMM,CRTTXT

.PAL RXA1:MARKER<RXA1:MSTPAR,MARKER,F3COMM,CRTTXT

.PAL RXA1:MISC1<RXA1:MSTPAR,MISC1,F3COMM,CRTTXT

.PAL RXA1:ENDROL<RXA1:MSTPAR,ENDROL,F3COMM,CRTTXT

.PAL RXA1:PRESF3<RXA1:MSTPAR,PRESF3,F3COMM,CRTTXT

.PAL RXA1:F3COMM<RXA1:MSTPAR,F3COMM,CRTTXT


.SUB SYS:F3SAV/T


$END

