$JOB (F5SAV.BI)  CREATE BINARY LIBRARY FOR MAST FIELD  -5-   30-AUG-91

.DEL RXA1:MSTF5.BN

.R PIP
*RXA1:MSTF5.BN<RXA1:TTY.BN,GATEWY.BN,PRESF5.BN,F5COMM.BN/B

.SQ RXA1:/O

.COPY SYS:<RXA1:MSTF5.BN

$END
