$JOB (F4GEN.BI)  GENERATE MAST FIELD  -4-	30-AUG-91

.DEL RXA1:*.BN

.SQ RXA1:/O

.PAL RXA1:CRT<RXA1:MSTPAR,CRT,CRTTXT

.PAL RXA1:RT01<RXA1:MSTPAR,RT01

.PAL RXA1:LPT<RXA1:MSTPAR,LPT

.PAL RXA1:PRESF4<RXA1:MSTPAR,PRESF4,F4COMM,CRTTXT

.PAL RXA1:STUFF1<RXA1:MSTPAR,STUFF1

.PAL RXA1:MOPCMD<RXA1:MSTPAR,MOPCMD,F4COMM

.PAL RXA1:USERCD<RXA1:MSTPAR,USERCD,F4COMM,CRTTXT

.PAL RXA1:FORMAT<RXA1:MSTPAR,FORMAT

.PAL RXA1:DIRTAL<RXA1:MSTPAR,DIRTAL,F4COMM

.PAL RXA1:F4COMM<RXA1:MSTPAR,F4COMM


.SUB SYS:F4SAV.BI/T


$END

