$JOB (F4SAV.BI)  CREATE BINARY LIBRARY FOR MAST FIELD  -4-   30-AUG-91

.DEL RXA1:MSTF4.BN

.R PIP
*RXA1:MSTF4.BN<RXA1:LPT.BN,RT01.BN,CRT.BN,USERCD.BN/B
*RXA1:MSTF4.BN<RXA1:MSTF4.BN,PRESF4.BN,STUFF1.BN,MOPCMD.BN,F4COMM.BN/B
*RXA1:MSTF4.BN<RXA1:MSTF4.BN,FORMAT.BN,DIRTAL.BN/B

.SQ RXA1:/O

.COPY SYS:<RXA1:MSTF4.BN

$END
