#!/bin/bash

HOME=/home/tester export HOME

echo cd $HOME
cd $HOME

/usr/bin/groups

exec /home/tester/sd/server -1 /home/tester/sd/sd0 -2 /home/tester/sd/sd1 -3 /home/tester/sd/sd2 -4 /home/tester/sd/sd3

