$JOB LOAD ADVENTURE
.R LOAD
*ADVENT,LOAD.LS<ADVENT,RND,GETIN,DECODE,BITSET,PCT,IO,SEED
*DSTROY,JUGGLE,MOVE,PUT,CARRY,DROP
*PSPEAK,SPEAK,RSPEAK,YES
*A5TOA1,VOCAB
*HERE,LIQ,LIQLOC,DARK,TRVLOC,BUG/O
*INITAD
*RKB
*$
$END
