$JOB (F2GEN.BI)  ASSEMBLE MAST FIELD 29-MAY-90

.DEL RXA1:MSTF2.BN

.PAL TALLEY<SYS:MSTPAR,RXA1:TALLEY,F2COMM,LPTTXT,CRTTXT

.PAL SAMPLE<SYS:MSTPAR,RXA1:SAMPLE,F2COMM,LPTTXT

.PAL EORSUM<SYS:MSTPAR,RXA1:EORSUM,F2COMM,LPTTXT

.PAL PRESF2<SYS:MSTPAR,RXA1:PRESF2,F2COMM,LPTTXT

.PAL F2COMM<SYS:MSTPAR,RXA1:F2COMM,LPTTXT

.R PIP
*RXA1:MSTF2.BN<TALLEY.BN,PRESF2.BN,SAMPLE.BN,EORSUM.BN,F2COMM.BN/B

.DEL TALLEY.BN,PRESF2.BN,SAMPLE.BN,EORSUM.BN,F2COMM.BN

.COPY SYS:<RXA1:MSTF2.BN

$END
