$JOB (F3GEN.BI) ASSEMBLE MAST FIELD 3	29-MAY-90

.DEL RXA1:MSTF3.BN

.PAL ROLLDT<SYS:MSTPAR,RXA1:ROLLDT,F3COMM,CRTTXT

.PAL CRTCTR<SYS:MSTPAR,RXA1:CRTCTR,F3COMM,CRTTXT

.PAL MARKER<SYS:MSTPAR,RXA1:MARKER,F3COMM,CRTTXT

.PAL FORMAT<SYS:MSTPAR,RXA1:FORMAT

.PAL MISC1<SYS:MSTPAR,RXA1:MISC1,F3COMM,CRTTXT

.PAL ENDROL<SYS:MSTPAR,RXA1:ENDROL,F3COMM,CRTTXT

.PAL PRESF3<SYS:MSTPAR,RXA1:PRESF3,F3COMM,CRTTXT

.PAL F3COMM<SYS:MSTPAR,RXA1:F3COMM,CRTTXT

.R PIP
*MSTF3.BN<ROLLDT.BN,CRTCTR.BN,MARKER.BN,FORMAT.BN,MISC1.BN/B
*RXA1:MSTF3.BN<MSTF3.BN,PRESF3.BN,ENDROL.BN,F3COMM.BN/B

.DEL ROLLDT.BN,CRTCTR.BN,MARKER.BN,FORMAT.BN,MISC1.BN
.DEL ENDROL.BN,PRESF3.BN,F3COMM.BN,MSTF3.BN

.COPY SYS:<RXA1:MSTF3.BN

$END
