// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: c_us 
// c2: c_us 
// c3: c_us 
// c4: c_us 
// c5: c_us 
// c6: c_us 
// c7: c_us 
// c8: c_us 
// c9: c_us 
// c10: c_us 
// c11: c_us 
// c12: c_us 
// c13: cpol_use 
// c14: cpol_use 
// c15: cpol_use 
// c16: cpol_use 
// e2: sn7401 
// n_t_3x = !(bf1 & an2); 
// n_t_7x = !ah1; 
// n_t_2x = !(n_t_1x & af1); 
// n_t_1x = !(ak1 & af1); 
// e4: sn7475 
module m7672x (bb2, clk_l, n3v, n_t_13x, n_t_14x, n_t_15x, n_t_17x, n_t_18x, n_t_19x, n_t_20x, n_t_6x, n_t_8x, aa1, ab1, ab2, ac1, ad1, ad2, ae1, ae2, ae2w, af1, af1w, af2, ah1, ah2, aj1, aj2, ak1, ak2, al1, al2, al2w, am1, am2, am2w, an1, an1w, an2, ap1, ap1w, ap2, ar1, ar2, as1, as2, at2, au1, au2, av1, av1w, av2, av2w, b2, ba1, bb1, bc1, bd1, bd2, be1, be2, bf1, bf2, bh1, bh2, bj1, bj2, bk1, bk2, bl1, bl2, bm1, bm2, bn1, bn2, bp1, bp2, br1, br2, bs1, bs2, bt2, bu1, bu2, bv1, bv2, c3, n15v, n_t_100x, n_t_104x, n_t_10x, n_t_11x, n_t_12x, n_t_16x, n_t_1x, n_t_23x, n_t_2x, n_t_34x, n_t_37x, n_t_56x, n_t_5x, n_t_65x, n_t_7x, n_t_9x, tck, tdo);
output bb2;
output clk_l;
inout n3v;
output n_t_13x;
output n_t_14x;
output n_t_15x;
output n_t_17x;
output n_t_18x;
output n_t_19x;
output n_t_20x;
output n_t_6x;
inout reg n_t_8x;
output aa1;
output ab1;
output ab2;
output ac1;
output ad1;
output ad2;
output ae1;
output ae2;
output ae2w;
input af1;
output af1w;
output af2;
input ah1;
output ah2;
output aj1;
output aj2;
input ak1;
output ak2;
output al1;
output al2;
output al2w;
output am1;
output am2;
output am2w;
output an1;
output an1w;
input an2;
output ap1;
output ap1w;
output ap2;
inout reg ar1;
output ar2;
output as1;
output as2;
output at2;
output au1;
output au2;
inout reg av1;
output av1w;
output av2;
output av2w;
output b2;
inout reg ba1;
inout reg bb1;
output bc1;
input bd1;
output bd2;
input be1;
output be2;
input bf1;
output bf2;
input bh1;
output bh2;
input bj1;
output bj2;
output bk1;
output bk2;
output bl1;
input bl2;
output bm1;
inout reg bm2;
output bn1;
inout reg bn2;
inout reg bp1;
output bp2;
inout br1;
inout br2;
input bs1;
input bs2;
input bt2;
input bu1;
output bu2;
output bv1;
output bv2;
output c3;
output n15v;
output n_t_100x;
output n_t_104x;
input n_t_10x;
input n_t_11x;
input n_t_12x;
input n_t_16x;
inout n_t_1x;
output n_t_23x;
output n_t_2x;
output n_t_34x;
output n_t_37x;
output n_t_56x;
output n_t_5x;
output n_t_65x;
output n_t_7x;
inout n_t_9x;
output tck;
output tdo;

reg ar1_m;
reg av1_m;
reg ba1_m;
reg bb1_m;
reg bm2_m;
reg bn2_m;
reg bp1_m;
reg n_t_8x_m;

wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
wire tp_n;
always @(bf1, bj1, bf1, bj1, 1'b0)
  if (bf1 & ~bj1) begin
    bb1_m <= 1'b0;
  end else
  if (bf1 & bj1) begin
    bb1_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    bb1_m <= 1'b0;
  end
always @(bf1, bj1, bf1, bj1, bb1_m)
  if (bf1 & ~bj1) begin
    bb1 <= 1'b0;
  end else
  if (bf1 & bj1) begin
    bb1 <= 1'b1;
  end else
  if (1'b0) begin
    bb1 <= bb1_m;
  end
always @(bf1, bh1, bf1, bh1, 1'b0)
  if (bf1 & ~bh1) begin
    ar1_m <= 1'b0;
  end else
  if (bf1 & bh1) begin
    ar1_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    ar1_m <= 1'b0;
  end
always @(bf1, bh1, bf1, bh1, ar1_m)
  if (bf1 & ~bh1) begin
    ar1 <= 1'b0;
  end else
  if (bf1 & bh1) begin
    ar1 <= 1'b1;
  end else
  if (1'b0) begin
    ar1 <= ar1_m;
  end
always @(bf1, be1, bf1, be1, 1'b0)
  if (bf1 & ~be1) begin
    av1_m <= 1'b0;
  end else
  if (bf1 & be1) begin
    av1_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    av1_m <= 1'b0;
  end
always @(bf1, be1, bf1, be1, av1_m)
  if (bf1 & ~be1) begin
    av1 <= 1'b0;
  end else
  if (bf1 & be1) begin
    av1 <= 1'b1;
  end else
  if (1'b0) begin
    av1 <= av1_m;
  end
always @(bf1, bd1, bf1, bd1, 1'b0)
  if (bf1 & ~bd1) begin
    ba1_m <= 1'b0;
  end else
  if (bf1 & bd1) begin
    ba1_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    ba1_m <= 1'b0;
  end
always @(bf1, bd1, bf1, bd1, ba1_m)
  if (bf1 & ~bd1) begin
    ba1 <= 1'b0;
  end else
  if (bf1 & bd1) begin
    ba1 <= 1'b1;
  end else
  if (1'b0) begin
    ba1 <= ba1_m;
  end
assign bk1 = ~bb1;
assign as1 = ~ar1;
assign au1 = ~av1;
assign bf2 = ~ba1;
// e5: sn7420 
assign n_t_9x = ~(n_t_12x & bu1 & n_t_16x & n_t_10x);
assign n_t_42x = ~(n_t_12x & n_t_4x & n3v);
// e6: sn7486 
assign bp2 = n_t_4x
              ^ bs2;
assign n3v = bl2
              ^ n_t_3x;
assign br2 = br1
              ^ n_t_10x;
assign bu2 = bt2
              ^ n_t_9x;
// e8: sn7475 
always @(bs1, bt2, bs1, bt2, 1'b0)
  if (bs1 & ~bt2) begin
    bm2_m <= 1'b0;
  end else
  if (bs1 & bt2) begin
    bm2_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    bm2_m <= 1'b0;
  end
always @(bs1, bt2, bs1, bt2, bm2_m)
  if (bs1 & ~bt2) begin
    bm2 <= 1'b0;
  end else
  if (bs1 & bt2) begin
    bm2 <= 1'b1;
  end else
  if (1'b0) begin
    bm2 <= bm2_m;
  end
always @(bs1, bs2, bs1, bs2, 1'b0)
  if (bs1 & ~bs2) begin
    bn2_m <= 1'b0;
  end else
  if (bs1 & bs2) begin
    bn2_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    bn2_m <= 1'b0;
  end
always @(bs1, bs2, bs1, bs2, bn2_m)
  if (bs1 & ~bs2) begin
    bn2 <= 1'b0;
  end else
  if (bs1 & bs2) begin
    bn2 <= 1'b1;
  end else
  if (1'b0) begin
    bn2 <= bn2_m;
  end
always @(bs1, br2, bs1, br2, 1'b0)
  if (bs1 & ~br2) begin
    bp1_m <= 1'b0;
  end else
  if (bs1 & br2) begin
    bp1_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    bp1_m <= 1'b0;
  end
always @(bs1, br2, bs1, br2, bp1_m)
  if (bs1 & ~br2) begin
    bp1 <= 1'b0;
  end else
  if (bs1 & br2) begin
    bp1 <= 1'b1;
  end else
  if (1'b0) begin
    bp1 <= bp1_m;
  end
always @(bs1, n3v, bs1, n3v, 1'b0)
  if (bs1 & ~n3v) begin
    n_t_8x_m <= 1'b0;
  end else
  if (bs1 & n3v) begin
    n_t_8x_m <= 1'b1;
  end else
  if (~(1'b0)) begin
    n_t_8x_m <= 1'b0;
  end
always @(bs1, n3v, bs1, n3v, n_t_8x_m)
  if (bs1 & ~n3v) begin
    n_t_8x <= 1'b0;
  end else
  if (bs1 & n3v) begin
    n_t_8x <= 1'b1;
  end else
  if (1'b0) begin
    n_t_8x <= n_t_8x_m;
  end
assign bu2 = ~bm2;
assign bp2 = ~bn2;
assign br1 = ~bp1;
assign clockb_l = ~n_t_8x;
// ic1: sn7404 
assign 'b'0 = ~n_t_11x;
// r1: r_us_ 
// r2: r_us_ 
// r3: r_us_ 
// r4: r_us_ 
// r5: r_us_ 
// r6: r_us_ 
// r7: r_us_ 
// r8: r_us_ 
// open collector 'wire-or's 
assign n_t_1x = (ak1 & af1)? 1'b0: 1'bz;
assign n_t_2x = (n_t_1x & af1)? 1'b0: 1'bz;
assign n_t_3x = ~((bf1 & an2));
assign n_t_7x = ah1? ~ah1: 1'bz;
endmodule
