$JOB (F2GEN.BI)  GENERATE MAST FIELD  -2-	8-AUG-91

.DEL RXA1:*.BN

.SQ RXA1:/O

.PAL RXA1:TALLEY<RXA1:MSTPAR,TALLEY,F2COMM,LPTTXT,CRTTXT

.PAL RXA1:SAMPLE<RXA1:MSTPAR,SAMPLE,F2COMM,LPTTXT

.PAL RXA1:EORSUM<RXA1:MSTPAR,EORSUM,F2COMM,LPTTXT

.PAL RXA1:PRESF2<RXA1:MSTPAR,PRESF2,F2COMM,LPTTXT

.PAL RXA1:F2COMM<RXA1:MSTPAR,F2COMM,LPTTXT


.SUB SYS:F2SAV.BI/T


$END

