$JOB (F2SAV.BI)  GENERATE BINARY LIBRARY FOR MAST FIELD  -2-   8-AUG-91

.DEL RXA1:MSTF2.BN

.R PIP
*RXA1:MSTF2.BN<RXA1:TALLEY.BN,PRESF2.BN,SAMPLE.BN,EORSUM.BN,F2COMM.BN/B

.SQ RXA1:/O

.COPY SYS:<RXA1:MSTF2.BN

$END

