// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: c_us 
// c2: c_us 
// c3: c_us 
// c4: c_us 
// c5: c_us 
// c6: c_us 
// c7: c_us 
// c8: c_us 
// c9: c_us 
// c10: c_us 
// e1: sn7453 
// !l2 = !(sr_insert & right_shift
//        # ina0_l & enable_a
//        # inb0_l & enable_b
//        # n_t_10x & left_shift); 
// n_t_8x = l2; 
// e2: sn7453 
// l2 = !(n_t_8x & right_shift
//   # ina1_l & enable_a
//   # inb1_l & enable_b
//   # n_t_12x & left_shift); 
// !l2 = !l2; 
// e3: sn7474 
module m212b (clear_reg_l, clock, enable_a, enable_b, ina0_l, ina1_l, ina2_l, ina3_l, ina4_l, ina5_l, inb0_l, inb1_l, inb2_l, inb3_l, inb4_l, inb5_l, left_shift, n_t_10x, n_t_11x, n_t_12x, n_t_13x, n_t_14x, n_t_15x, n_t_16x, n_t_17x, n_t_18x, n_t_7x, n_t_8x, n_t_9x, right_shift, sl_insert, sr_insert);
input clear_reg_l;
input clock;
input enable_a;
input enable_b;
input ina0_l;
input ina1_l;
input ina2_l;
input ina3_l;
input ina4_l;
input ina5_l;
input inb0_l;
input inb1_l;
input inb2_l;
input inb3_l;
input inb4_l;
input inb5_l;
input left_shift;
inout n_t_10x;
inout reg n_t_11x;
inout n_t_12x;
inout reg n_t_13x;
inout n_t_14x;
inout reg n_t_15x;
inout n_t_16x;
inout reg n_t_17x;
inout n_t_18x;
inout reg n_t_7x;
inout n_t_8x;
inout reg n_t_9x;
input right_shift;
input sl_insert;
input sr_insert;

reg n_t_11x_m;
reg n_t_13x_m;
reg n_t_15x_m;
reg n_t_17x_m;
reg n_t_7x_m;
reg n_t_9x_m;

wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
wire v2;
always @(clock, clear_reg_l, l2)
  if (~clear_reg_l) begin
    n_t_7x_m <= 1'b1;
  end else
  if (~(clock)) begin
    n_t_7x_m <= ~l2;
  end
always @(clock, clear_reg_l, n_t_7x_m)
  if (~clear_reg_l) begin
    n_t_7x <= 1'b1;
  end else
  if (clock) begin
    n_t_7x <= n_t_7x_m;
  end
always @(clock, clear_reg_l, l2)
  if (~clear_reg_l) begin
    n_t_9x_m <= 1'b1;
  end else
  if (~(clock)) begin
    n_t_9x_m <= l2;
  end
always @(clock, clear_reg_l, n_t_9x_m)
  if (~clear_reg_l) begin
    n_t_9x <= 1'b1;
  end else
  if (clock) begin
    n_t_9x <= n_t_9x_m;
  end
assign n_t_10x = ~n_t_9x;
// e4: sn7453 
// n_t_25x = !(n_t_10x & right_shift
//        # ina2_l & enable_a
//        # inb2_l & enable_b
//        # n_t_14x & left_shift); 
// !n_t_25x = !n_t_25x; 
// e5: sn7453 
// !'b'1 = !(n_t_12x & right_shift
//        # ina3_l & enable_a
//        # inb3_l & enable_b
//        # n_t_16x & left_shift); 
// 'b'1 = 'b'1; 
// e6: sn7474 
always @(clock, clear_reg_l, n_t_25x)
  if (~clear_reg_l) begin
    n_t_11x_m <= 1'b1;
  end else
  if (~(clock)) begin
    n_t_11x_m <= n_t_25x;
  end
always @(clock, clear_reg_l, n_t_11x_m)
  if (~clear_reg_l) begin
    n_t_11x <= 1'b1;
  end else
  if (clock) begin
    n_t_11x <= n_t_11x_m;
  end
assign n_t_12x = ~n_t_11x;
always @(clock, clear_reg_l, 1'b0)
  if (~clear_reg_l) begin
    n_t_13x_m <= 1'b1;
  end else
  if (~(clock)) begin
    n_t_13x_m <= 1'b0;
  end
always @(clock, clear_reg_l, n_t_13x_m)
  if (~clear_reg_l) begin
    n_t_13x <= 1'b1;
  end else
  if (clock) begin
    n_t_13x <= n_t_13x_m;
  end
assign n_t_14x = ~n_t_13x;
// e7: sn7453 
// !l2 = !(n_t_14x & right_shift
//        # ina4_l & enable_a
//        # inb4_l & enable_b
//        # n_t_18x & left_shift); 
// l2 = l2; 
// e8: sn7453 
// n_t_119x = !(n_t_16x & right_shift
//         # ina5_l & enable_a
//         # inb5_l & enable_b
//         # sl_insert & left_shift); 
// !n_t_119x = !n_t_119x; 
// e9: sn7474 
always @(clock, clear_reg_l, l2)
  if (~clear_reg_l) begin
    n_t_15x_m <= 1'b1;
  end else
  if (~(clock)) begin
    n_t_15x_m <= ~l2;
  end
always @(clock, clear_reg_l, n_t_15x_m)
  if (~clear_reg_l) begin
    n_t_15x <= 1'b1;
  end else
  if (clock) begin
    n_t_15x <= n_t_15x_m;
  end
assign n_t_16x = ~n_t_15x;
always @(clock, clear_reg_l, n_t_119x)
  if (~clear_reg_l) begin
    n_t_17x_m <= 1'b1;
  end else
  if (~(clock)) begin
    n_t_17x_m <= n_t_119x;
  end
always @(clock, clear_reg_l, n_t_17x_m)
  if (~clear_reg_l) begin
    n_t_17x <= 1'b1;
  end else
  if (clock) begin
    n_t_17x <= n_t_17x_m;
  end
assign n_t_18x = ~n_t_17x;
// r1: r_us_ 
// open collector 'wire-or's 
assign l2 = ~((n_t_8x & right_shift
                | ina1_l & enable_a
                | inb1_l & enable_b
                | n_t_12x & left_shift));
assign n_t_119x = ~((n_t_16x & right_shift
                      | ina5_l & enable_a
                      | inb5_l & enable_b
                      | sl_insert & left_shift));
assign n_t_25x = ~((n_t_10x & right_shift
                     | ina2_l & enable_a
                     | inb2_l & enable_b
                     | n_t_14x & left_shift));
assign l2 = (sr_insert & right_shift
              | ina0_l & enable_a
              | inb0_l & enable_b
              | n_t_10x & left_shift)
             | (n_t_14x & right_shift
                | ina4_l & enable_a
                | inb4_l & enable_b
                | n_t_18x & left_shift);
assign 'b'1 = (n_t_12x & right_shift
                | ina3_l & enable_a
                | inb3_l & enable_b
                | n_t_16x & left_shift);
assign n_t_8x = ~l2? 1'b0: 1'bz;
endmodule
