;SIMH Configuration File for P?S/8 Version 8Z.
;
;Last Edit: 28-Aug-2015 cjl
;
;show configuration
;set lpt disable
set lpt enable
attach ptr ptrfile.txt
attach ptp ptpfile.txt
attach rk0 rka0&rkb0.rk05
attach rk1 rka1&rkb1.rk05
attach rk2 rka2&rkb2.rk05
attach rk3 rka3&rkb3.rk05
attach dt0 pqs8_tc08.tu56
;attach dt0 pqs8_tc08_05-Aug-2015.tu56
attach dt1 os8_dta1.tu56
attach dt2 pqs8_unit_2.tu56
attach dt3 pqs8_unit_3.tu56
attach dt4 pqs8_unit_4.tu56
attach dt5 pqs8_unit_5.tu56
attach dt6 pqs8_unit_6.tu56
attach dt7 SCRATCH7.tu56
attach lpt lptout.txt
set cpu idle
set console wru=005
set tti 7b
dep sr 0000
show configuration

bo dt0
