$JOB MULTI8 CONFIGURATION BATCH FOR CAMBRIDGE - ANATOMY
.DEL MULTI8.SV,SWPFIL.M8,SPOOL.LP
.PAL M,M<CMBRDG,M1,M2,M3,M4,M5(NEDG)
.R GLOBL
*MS.PA<SYMBLS.GS,M.LS
.PAL MS,MONDUM/L
.SAVE SYS MONDUM
/
.PAL BS<MS,BS.TK
.PAL CB<MS,CB.TK
.PAL OD<MS,OD.TK
.PAL CD<MS,CD.TK
.PAL MA<MS,MA.TK
.PAL PA<MS,PA.TK
.PAL DI<MS,DI.TK
.PAL LI<MS,LI.TK
.PAL IT<MS,IT.TK
.PAL BE<MS,BE.TK
.PAL ST<MS,ST.TK
.PAL TA<MS,TA.TK
.PAL DS<MS,DS.TK
.PAL LA<MS,LA.TK
.R MULTI8
*BS,CB,OD,CD,MA,PA,MA,PA,DI
*LI,IT,BE,ST,TA,DS,LA/N$
/
.PAL FE<MS,FE.TK
.PAL RX<MS,RX.TK
.R MULTI8
*FE,RX/N$
/
.PAL LE<MS,LE.TK
.PAL LP<MS,LP.TK
.R MULTI8
*LE,LP/N$
/
.PAL PP<MS,PP.TK
.PAL PE<MS,PE.TK
.PAL PR<MS,PR.TK
.PAL RE<MS,RE.TK
.R MULTI8
*PP,PE,PR,RE/N$
/
.R PIP
*SPOOL.LP</I=100$
$END
