$JOB MULTI8 SYSTEM GENERATION FOR POCKER
.DE
.AS DSK 2
.PAL M,M<CONFIG,M1,M2,M3,M4,M5(NDG)
*/N$
.RU D0:GLOBL
*MS.PA<D0:SYMBLS.GS,DSK:M.LS
.PAL MS,D0:MONDUM/L
.SAVE DSK:MONDUM
.DEL M.LS,MS.BN
.SQ DSK:/O
.AS D0 IN
.PAL MS-NB,IN:CD.TK
.PAL MS-NB,IN:OD.TK
.PAL MS-NB,IN:PA.TK
.PAL MS-NB,IN:MA.TK
.PAL MS-NB,IN:DI.TK
.PAL MS-NB,IN:LI.TK
.PAL MS-NB,IN:IT.TK
.PAL MS-NB,IN:BS.TK
.PAL MS-NB,IN:BE.TK
.AS D0
.AS D1 IN
.PAL MS-NB,IN:CB.TK
.PAL MS-NB,IN:ST.TK
.PAL MS-NB,IN:TA.TK
/.PAL MS-NB,IN:DS.TK
.R MULTI8
*CD,OD,PA,MA,DI,LI,IT,BS,CB
*BE,ST,TA/N$

.PAL MS-NB,IN:LP.TK
.PAL MS-NB,IN:LE.TK
.R MULTI8
*LP,LE/N$

/.PAL MS-NB,PP.TK
/.PAL MS-NB,PE.TK
/.R MULTI8
/*PP,PE/N$

/.PAL MS-NB,PR.TK
/.PAL MS-NB,RE.TK
/.R MULTI8
/*PR,RE/N$

/.PAL MS-NB,ME.TK
/.R MULTI8
/*ME/N$

PAL MS-NB,IN:PL.TK
.PAL MS-NB,IN:GE.TK
.R MULTI8
*PL,GE/N$

$END
