$JOB MULTI8 CONFIGURATION BATCH FOR Y.POCKER - CHEMISTRY
.DE
.DEL SYS:MULTI8.SV,MONDUM.SV,SWPFIL.M8,SPOOL.*
.AS DSK 0
.DEL M.*,MS.*,*.BN
.PAL M,M<POCKER,SYS:M1YP,DSK:M2,M3,M4,SYS:M5YP(NEDG)
*/N$
.R GLOBL
*MS.PA<SYMBLS.GS,M.LS
.PAL MS-NB,MONDUM/L
.SAVE SYS MONDUM
.COPY SYS:<MS.PA
/
.AS DSK 1
.DEL *.BN
.COPY DSK:<SYS:MS.PA
.PAL BS<MS,BS.TK
.PAL CB<MS,CB.TK
.PAL OD<MS,OD.TK
.PAL CD<MS,CD.TK
.PAL MA<MS,MA.TK
.PAL PA<MS,PA.TK
.PAL DI<MS,DI.TK
.PAL LI<MS,LI.TK
.PAL IT<MS,IT.TK
.PAL BE<MS,BE.TK
.PAL ST<MS,ST.TK
.PAL TA<MS,TA.TK
/.PAL DS<MS,DS.TK
.PAL EX<MS,EX.TK
.PAL LA<MS,LA.TK
.R MULTI8
*BS,CB,OD,CD,MA,PA,MA,PA,DI
*LI,IT,BE,ST,TA,EX,LA/N$
/
.PAL FE<MS,FE.TK
.PAL RX<MS,RX.TK
.R MULTI8
*FE,RX/N$
/
.PAL LE<MS,LE.TK
.PAL LP<MS,LP.TK
.R MULTI8
*LE,LP/N$
/
.PAL GE<MS,GE.TK
.PAL PL<MS,PL.TK
.R MULTI8
*GE,PL/N$
/
.R PIP
*SYS:MS.PA</D
*SYS:SPOOL.LP</I=100
*SYS:SPOOL.PL</I=100$
.DE
$END
