$JOB
.R F4
*PLTKIN/O/Q/L
*LAXIS,AXIS,PLOTX,PLOTL,MOVE,PLOTSY,RUNGKP/G
*TEMPVX.DA/5
*KINETE.DA/6$
$END
.R F4
*PLTKIN/O/Q/L
*AXIS,PLOTX,PLOTL,MOVE,PLOTSY,RUNGKP/G
*TEMPVX.DA/5
*KINETD.DA/6$
$END
.R F4
*PLT615/O/Q/L
*AXIS,PLOTX,PLOTL,MOVE,PLOTSY,RUNGDK/G
*TEMPVX.DA/5
*KINDK.DA/6$
.R LOAD
*PLTINS,AXIS,RSCALE,PLOTX,PLOTL,MOVE,PLOTSY/G
*TEMP.DA/5$
$END
