$JOB - THIS IS A DEMONSTRATION OF THE OS/8 BATCH SYSTEM
/
/PRINT THE DIRECTORY
.DIR/E=4
/RUN THE BASIC STANDALONE COMPILER
/
.R BCOMP
*TRIAL.BA/G
/
/NOW RUN THE FORTRAN II SYSTEM
/WE NEED TO CALL IT EXPLICITLY BECAUSE OTHERWISE CCL WILL DEFAULT
/TO FORTRAN IV
/
.R FORT
*TRIAL1.FT/G
/
/NOW THE FORTRAN IV SYSTEM
/
/FIRST COMPILE
.COMPILE TRIAL2.FT
/
/THEN LOAD AND RUN
.LOAD TRIAL2.RL/G
/
/CLEAN UP THE UNWANTED TEMPORARY FILES
.DEL TRIAL2.RL,TRIAL2.LD
/
/AND FINALLY PRINT THE DIRECTORY AGAIN
.DIR/E=4
/
/THAT'S ALL FOLKS
$END
