


INSTRUCTIONS FOR HANDLING BATCH INPUT TO TORQBI
INTERRUPT WITH SENSE SWITCH 5 AS USUAL
NOTE CAREFULLY THE JOB YOU ARE INTERRUPTING AND THE $JOB ENTRY AT THE TOP
OF THE OUTPUT.
(1)  IF THE JOB LOOKS LIKE THIS:
	$JOB
	.R FRTS2
	*TORQBI
	*ILPS4D.DA/5
	*FRCI4D.DA/6
	*FRCI4D.DA</7
	*SYS:ITRI4D.DA/2
	*SYS:ITRI4D.DA</1
	*$
THEN NO CHANGE IN THE INPUT FILE 5 IS REQUIRED.  IF THIS IS ALSO THE
FIRST JOB IN THE JOB.BI FILE, THE RESTART PROCEDURE IS SIMPLY
	.SUBMIT JOB
IF THE JOB IS NOT THE FIRST IN THE JOB.BI FILE ( .TYPE JOB.BI) THEN EDIT
JOB.BI, DELETING THE JOBS ABOVE IT AS IN (A) BELOW.
(2)  IF THE JOB LOOKS LIKE THIS:
	$JOB
	.R FRTS2
	*TORQBI
	*ILPS4C.DA/5
	*FRCI4C.DA</7
	*SYS:ITRI4C.DA</1
	*$
THEN TWO THINGS MUST BE DONE.
    (A) EDIT THE JOB.BI FILE TO LOOK LIKE #1 ABOVE.  THIS IS DONE WITH 
SCROLL BY .ED JOB.BI/B AND INSERTING THE NECESSARY LINES (* IS SHIFT 8
 AND $ IS SHIFT 4).  THE SCROLL MANUAL WILL HELP HERE.  (I WILL USE ! FOR
 THE ESC KEY AND ^ FOR THE CTRL KEY). YOU MUST MAKE SURE THAT THE $JOB
 SET YOU INTERRUPTED IS FIRST IN THE LIST.  IF IT IS NOT, DELETE THE 
LINES ABOVE IT WITH THE ^U COMMAND.
   (B) YOU ALSO HAVE TO EDIT THE DATA FILE # 5. TO DO THIS
TYPE .ED ILPS4%.DA/B  (% IS THE LETTER OF THE JOB). NOW ISSUE COMMAND
 !/!!  (I WILL USE ! FOR THE ESC KEY COMMANDS).  THIS GETS YOU TO THE 
END OF THE FILE.  HERE YOU SEE 3 LINES:
		N
		0,0,0
		1
DELETE THESE THREE LINES WITH ^U  (^ IS CTRL KEY).  NOW TYPE Y TO
REPLACE THE N YOU DELETED.  QUIT WITH THE !QUIT!! COMMAND.
   HAVING COMPLETED A AND B YOU NOW SIMPLY TYPE .SUBMIT JOB
IF YOU HAVE ANY TROUBLE MY PHONE NUMBER IS LA2-7863.
