// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: c_us 
// c2: c_us 
// c3: c_us 
// c4: c_us 
// c5: c_us 
// c6: c_us 
// c7: c_us 
// c8: cpol_use 
// c10: cpol_use 
// c11: cpol_use 
// e2: sn7404 
module m688b (erws_l, n_t_12x, n_t_13x, n_t_15x, n_t_26x, n_t_27x, n_t_3x, n_t_6x, n_t_8x, xrd0_l, xrd1_l, b1, b2, c0_l, c1, c1_l, d1, d2, data0_l, data10_l, data11_l, data1_l, data2_l, data3_l, data4_l, data5_l, data6_l, data7_l, data8_l, data9_l, e1, e2, f1, f2, h1, h2, initialize, int_rqst_l, internal_io_l, io_pause_l, j1, j2, k1, k2, l1, l2, m1, m2, md03_l, md04_l, md05_l, md06_l, md07_l, md08_l, md09_l, md10_l, md11_l, n1, n2, n_t_10x, n_t_11x, n_t_14x, n_t_16x, n_t_17x, n_t_19x, n_t_1x, n_t_20x, n_t_2x, n_t_5x, p1, p2, r1, r2, s1, s2, skip_l, t2, t2_l, tp3, u1, u2, v1, v2);
output erws_l;
output n_t_12x;
output n_t_13x;
inout n_t_15x;
output n_t_26x;
input n_t_27x;
output n_t_3x;
output n_t_6x;
output n_t_8x;
output xrd0_l;
output xrd1_l;
output b1;
output b2;
output c0_l;
output c1;
output c1_l;
output d1;
output d2;
output data0_l;
output data10_l;
output data11_l;
output data1_l;
output data2_l;
output data3_l;
output data4_l;
output data5_l;
output data6_l;
output data7_l;
output data8_l;
output data9_l;
output e1;
output e2;
output f1;
output f2;
output h1;
output h2;
output initialize;
output int_rqst_l;
output internal_io_l;
output io_pause_l;
output j1;
output j2;
output k1;
output k2;
output l1;
output l2;
output m1;
output m2;
output md03_l;
output md04_l;
output md05_l;
output md06_l;
output md07_l;
output md08_l;
output md09_l;
output md10_l;
output md11_l;
output n1;
output n2;
output n_t_10x;
output n_t_11x;
output n_t_14x;
input n_t_16x;
output n_t_17x;
output n_t_19x;
output n_t_1x;
output n_t_20x;
output n_t_2x;
output n_t_5x;
output p1;
output p2;
output r1;
output r2;
output s1;
output s2;
output skip_l;
output t2;
output t2_l;
output tp3;
output u1;
output u2;
output v1;
output v2;


wire ebot_l;
assign n_t_20x = 1'b0;
assign n_t_26x = ~n_t_27x;
assign n_t_19x = ~n_t_15x;
assign n_t_15x = ~n_t_16x;
// r1: r_us_ 
// r2: r_us_ 
// r3: r_us_ 
// r4: r_us_ 
// r5: r_us_ 
// r6: r_us_ 
// r7: r_us_ 
// r8: r_us_ 
// r9: r_us_ 
// r10: r_us_ 
// r11: r_us_ 
// r12: r_us_ 
// r13: r_us_ 
// r14: r_us_ 
// r15: r_us_ 
// r16: r_us_ 
// r17: r_us_ 
// r18: r_us_ 
// r19: r_us_ 
// r20: r_us_ 
// r21: r_us_ 
// r22: r_us_ 
// r23: r_us_ 
// r24: r_us_ 
// r25: r_us_ 
// r26: r_us_ 
// r27: r_us_ 
// open collector 'wire-or's 
endmodule
