#!/usr/bin/perl

$verilog = "$ENV{'HOME'}/Verilog/bin";
$eagle = "$ENV{'HOME'}/Eagle/projects/DEC/Mxxx";

opendir(DIR, ".") || die ".: $!";
foreach $d (readdir DIR) {
  next unless -d $d;
  next if $d =~ /^[.]/;
  next if $d =~ /^no/;
  $p = $d; $p =~ s/.$//;
  $f = "$eagle/$p/$d.sch";
# print "$verilog/pinlst $f\n";
  system "$verilog/pinlst $f";
}
