// this file is generated by topld.pl 
// please don't edit it. 
// input pins 
// output pins 
// internal nodes 
// code nodes 
// equations 
// c1: cpol_use 
// c2: cpol_use 
// c3: c_us 
// c4: c_us 
// e1: sn7400 
module m501b (n_t_11x, n_t_15x, a1, ab2, ac1, ad00h, ad01h, ad02h, ad03h, ad04h, ad05h, ad06h, ad07h, ad08h, ad09h, ad10h, ad11h, ad2, adoneh, adonel, ae1, af1, af2, aflagh, ainith, al1, al2, am1, am2, an2, ap1, ap2, ar2, areadyh, areadyl, as1, as2, astrobeh, astrobel, av1, bb1, bb2, bc1, bd00h, bd01h, bd02h, bd03h, bd04h, bd05h, bd06h, bd07h, bd08h, bd09h, bd10h, bd11h, bdoneh, bdonel, be1, bf1, bflagh, bh1, binith, bj1, bj2, bk1, bl1, bl2, bm1, bm2, bn1, bp2, br1, breadyh, breadyl, bs1, bstrobeh, bstrobel, bu1, c1, carry_in_l, d2, e, f, h2, j2, k, l, load_rwb, load_tac, load_tb, load_tbn, load_tmasu, m, n, n10v, n15v, n21v, n3v3, n_t_10x, n_t_12x, n_t_13x, n_t_14x, n_t_16x, n_t_17x, n_t_20x, n_t_26x, n_t_27x, n_t_28x, n_t_29x, n_t_31x, n_t_35x, n_t_38x, n_t_39x, n_t_3x, n_t_43x, n_t_49x, n_t_4x, n_t_50x, n_t_51x, n_t_5x, n_t_6x, p, phase, r, rwb_out, tac2_h, tac2_l, tac3_l, tape_bus2, tape_bus3, tb2_h, tb3_h, tbn2, tma2, tma3, tmasu2, tmasu3, u1, v2);
output n_t_11x;
output n_t_15x;
output a1;
output ab2;
output ac1;
output ad00h;
output ad01h;
output ad02h;
output ad03h;
output ad04h;
output ad05h;
output ad06h;
output ad07h;
output ad08h;
output ad09h;
output ad10h;
output ad11h;
output ad2;
output adoneh;
output adonel;
output ae1;
output af1;
output af2;
output aflagh;
output ainith;
output al1;
output al2;
output am1;
output am2;
output an2;
output ap1;
output ap2;
output ar2;
output areadyh;
output areadyl;
output as1;
output as2;
output astrobeh;
output astrobel;
output av1;
output bb1;
output bb2;
output bc1;
output bd00h;
output bd01h;
output bd02h;
output bd03h;
output bd04h;
output bd05h;
output bd06h;
output bd07h;
output bd08h;
output bd09h;
output bd10h;
output bd11h;
output bdoneh;
output bdonel;
output be1;
output bf1;
output bflagh;
output bh1;
output binith;
output bj1;
output bj2;
output bk1;
output bl1;
output bl2;
output bm1;
output bm2;
output bn1;
output bp2;
output br1;
output breadyh;
output breadyl;
output bs1;
output bstrobeh;
output bstrobel;
output bu1;
output c1;
output carry_in_l;
output d2;
output e;
inout f;
output h2;
output j2;
input k;
output l;
output load_rwb;
output load_tac;
output load_tb;
output load_tbn;
output load_tmasu;
output m;
output n;
output n10v;
output n15v;
output n21v;
output n3v3;
output n_t_10x;
output n_t_12x;
output n_t_13x;
output n_t_14x;
output n_t_16x;
output n_t_17x;
output n_t_20x;
output n_t_26x;
output n_t_27x;
output n_t_28x;
output n_t_29x;
output n_t_31x;
output n_t_35x;
output n_t_38x;
output n_t_39x;
output n_t_3x;
output n_t_43x;
output n_t_49x;
output n_t_4x;
output n_t_50x;
output n_t_51x;
output n_t_5x;
output n_t_6x;
output p;
output phase;
output r;
output rwb_out;
output tac2_h;
output tac2_l;
output tac3_l;
output tape_bus2;
output tape_bus3;
output tb2_h;
output tb3_h;
output tbn2;
output tma2;
output tma3;
output tmasu2;
output tmasu3;
output u1;
output v2;


wire n_t_8x;
assign e = ~f;
assign f = ~k;
// r1: r_us_ 
// r2: r_us_ 
// r3: r_us_ 
// r4: r_us_ 
// r5: r_us_ 
// r6: r_us_ 
// r7: r_us_ 
// r8: r_us_ 
// r9: r_us_ 
// r10: r_us_ 
// r11: r_us_ 
// r12: r_us_ 
// r13: r_us_ 
// r14: r_us_ 
// open collector 'wire-or's 
endmodule
