$JOB (F0GEN.BI)  ASSEMBLE MAST FIELD 0	29-MAY-90

.DEL RXA1:MSTF0.BN

.PAL RTS8<SYS:MSTPAR,RXA1:RTS8

.PAL CLOCK<SYS:MSTPAR,RXA1:CLOCK

.PAL PWRF<SYS:MSTPAR,RXA1:PWRF

.PAL MNULL<SYS:MSTPAR,RXA1:MNULL

.PAL MCR<SYS:MSTPAR,RXA1:MMCR,MSTNAM

.R PIP
*RXA1:MSTF0.BN<RTS8.BN,CLOCK.BN,PWRF.BN,MNULL.BN,MCR.BN/B

.DEL RTS8.BN,CLOCK.BN,PWRF.BN,MNULL.BN,MCR.BN

.COPY SYS:<RXA1:MSTF0.BN

$END
