$JOB (F1GEN.BI) ASSEMBLE MAST FIELD 1	29-MAY-90

.DEL RXA1:MSTF1.BN

.PAL SGATE<SYS:MSTPAR,RXA1:SGATE,F1COMM

.PAL RGATE<SYS:MSTPAR,RXA1:RGATE,F1COMM

.PAL PGATE<SYS:MSTPAR,RXA1:PGATE,F1COMM

.PAL DEF13<SYS:MSTPAR,RXA1:DEF13,F1COMM

.PAL DEF2<SYS:MSTPAR,RXA1:DEF2,F1COMM

.PAL MEMORY<SYS:MSTPAR,RXA1:MEMORY,F1COMM

.PAL TRAYCK<SYS:MSTPAR,RXA1:TRAYCK,F1COMM

.PAL BUILD<SYS:MSTPAR,RXA1:BUILD,F1COMM

.PAL DIGINP<SYS:MSTPAR,RXA1:DIGINP,F1COMM

.PAL F1COMM<SYS:MSTPAR,RXA1:F1COMM


.R PIP
*MSTF1.BN<SGATE.BN,RGATE.BN,PGATE.BN,DEF13.BN,DEF2.BN/B
*MSTF1.BN<MSTF1.BN,BUILD.BN,DIGINP.BN/B
*RXA1:MSTF1.BN<MSTF1.BN,MEMORY.BN,TRAYCK.BN,F1COMM.BN/B

.DEL MSTF1.BN,SGATE.BN,RGATE.BN,PGATE.BN,DEF13.BN
.DEL DEF2.BN,BUILD.BN,DIGINP.BN,MEMORY.BN,TRAYCK.BN
.DEL F1COMM.BN

.COPY SYS:<RXA1:MSTF1.BN

$END
