$JOB (F4GEN.BI) ASSEMBLE MAST FIELD 4	29-MAY-90

.DEL RXA1:MSTF4.BN

.PAL TTY<SYS:MSTPAR,RXA1:TTYCF,TTYM

.PAL TTYST<SYS:MSTPAR,RXA1:TTYST

.PAL LPT<SYS:MSTPAR,RXA1:LPT

.PAL RT01<SYS:MSTPAR,RXA1:RT01

.PAL CRT<SYS:MSTPAR,RXA1:CRT,CRTTXT

.PAL PRESF4<SYS:MSTPAR,RXA1:PRESF4,F4COMM,CRTTXT

.PAL STUFF1<SYS:MSTPAR,RXA1:STUFF1

.PAL MOPCMD<SYS:MSTPAR,RXA1:MOPCMD,F4COMM

.PAL USERCD<SYS:MSTPAR,RXA1:USERCD,F4COMM,CRTTXT

.PAL F4COMM<SYS:MSTPAR,RXA1:F4COMM


.R PIP
*MSTF4.BN<TTY.BN,TTYST.BN,LPT.BN,RT01.BN,CRT.BN,USERCD.BN/B
*RXA1:MSTF4.BN<MSTF4.BN,PRESF4.BN,STUFF1.BN,MOPCMD.BN,F4COMM.BN/B

.DEL TTY.BN,TTYST.BN,LPT.BN,RT01.BN,CRT.BN
.DEL USERCD.BN,PRESF4.BN,STUFF1.BN,MOPCMD.BN
.DEL F4COMM.BN,MSTF4.BN

.COPY SYS:<RXA1:MSTF4.BN

$END
