$JOB (F3SAV.BI)  CREATE BINARY LIBRARY FOR MAST FIELD  -3-   8-AUG-91

.DEL RXA1:MSTF3.BN

.R PIP
*RXA1:MSTF3.BN<RXA1:ROLLDT.BN,CRTCTR.BN,MARKER.BN,MISC1.BN/B
*RXA1:MSTF3.BN<RXA1:MSTF3.BN,PRESF3.BN,ENDROL.BN,F3COMM.BN/B

.SQ RXA1:/O

.COPY SYS:<RXA1:MSTF3.BN

$END

