//++
//Controller.v
//
//	PDP-8/V TIMING GENERATOR AND COMBINATORIAL CONTROL LOGIC
//  CONFIDENTIAL - CONTAINS TRADE SECRETS OF SPARE TIME GIZMOS, INC.
//   COPYRIGHT (C) 2007 BY SPARE TIME GIZMOS.  ALL RIGHTS RESERVED.
//
// DESCRIPTION:
//   The Controller implements a timing generator and a large (huge!) block
// of purely combinatorial control logic, which together direct the operation
// of the registers and functional units in the DataPaths section.  The timing
// generator is, of course, a state machine that uses the current state and
// the opcode to determine the next state.  In the PDP-8/V, as it is in the 8/A
// and 8/E as well, the total number of states is fairly limited - there's only
// about a dozen.
//
//   The control block is simply a large mass of "random" logic that takes the
// current state and the current instruction, as well as some external flags
// and inputs, and generates the control signals for the DataPaths.  This is
// essentially just a giant PLA and could, and probably would in real hardware,
// be implemented as a ROM.  But here we simply write out all the equations and
// conditions and let the synthesis tool figure out a way to minimize it.
//
//   And by the way, there's a very nice chart available from Spare Time Gizmos
// that shows all the states in the PDP-8/V along with the associated operations
// for each of the major instruction groups. It's really a lot easier to under-
// stand how all this works if you have one of those handy!
//
// REVISION HISTORY:
// 30-Jun-07  RLA  New file.
//  2-Jul-07  RLA  Forgot to implement the group 2 CLA (7600) opcode!
//  2-Jul-07  RLA  Select the MQ as the left source during group 3 instructions!
//  3-Jul-07  RLA  Add 8/E processor IOTs (CAF, ION, IOF, SGT, etc)
//		   Add DeviceClear (for CAF) output
//  4-Jul-07  RLA  Finish off the processor IOTs and add interrupt handling
//		   Fix spurious "EXECUTE WITH JMP" simulation errors 
//  7-Jul-07  RLA  Change to an asynchronous reset for compatibility with GSR.
//  8-Jul-07  RLA  Connect SR and FLAGS directly to the LeftMux 
//
// TODO:
//*** TODO NYI IMPORTANT *****
// the HALTED output should be generated by the LogicUnit, not the TG
// memory write, device write/read outputs should be synchronous????
// LoadSR is never used, because nobody implemented the WSR instruction...
// Implement a cycle stretching in TimingGenerator to stretch external memory
//   and device accesses
//--
//000000011111111112222222222333333333344444444445555555555666666666677777777778
//345678901234567890123456789012345678901234567890123456789012345678901234567890
`include "Parameters.v"		// global declarations for this project

//++
// Some random thoughts on synchronicity...
//
//   Some of the outputs from the control logic - e.g. MemoryWrite, DeviceRead
// and Write - are not synchronous in that they aren't registered and clocked.
// Instead they're derived by decoding the current state and the opcode, and
// this is potentially doubtful since it could lead to glitches on these outputs
// that could cause data corruption.
//
//   In real life this seems to work fairly well for two reasons, a) because
// the opcode is stable and unchanging from the end of state FETCH2, which is
// long before any of these outputs are generated, and b) because the current
// state is a "one hot" implementation so only a single bit is needed to
// decode the current state.  In the end the synthesis tool generates some
// logic to decode the IR and then ANDs the result with one bit from the state,
// and since the state bit changes synchronously the output of the AND is
// glitch free.
//
//  At least that's my story and I'll stick with it until it's proven wrong :-)
//
//  The "correct" way to fix this would be to make these outputs synchronous,
// but that's harder than it sounds.  Generating flip flops is easy, but the
// F-Fs would pipeline these signals and add a one clock cycle delay to them.
// And that means that the control logic would have to actually generate
// MemoryWrite, DeviceWrite, etc one state _earlier_, which would require some
// potentially tricky look ahead logic.
//
//   FWIW, this is even worse in the case of DeviceRead, since it's controlled
// not only by all the stuff I've already listed, but also by the external
// DeviceFunction signals.  Since the DeviceFunction is generated by the per-
// ipheral and is not necessarily synchronous with the CPU clock, any number
// of glitches could occur.  Bummer!
//--

//++
//   The interrupt logic is a little obscure, so here's a summary of the
// players to help get you started -
//
//   InterruptRequest - Input to KK8V module.
//			  Global, active high, interrupt request.
//
//   InterruptRequest - Input to Controller and DataPaths module.
//			  Inverted, not wire OR, version of the above.
//
//   InterruptEnable  - single bit F-F in the FlagsUnit in DataPaths.
//			  This bit is set and cleared by the program (e.g.
//			ION, IOF, RTF, etc).  It's cleared by an interrupt
//			grant cycle and a master reset.  Inhibits interrupts
//			when cleared.
//
//   InterruptInhibit - single bit F-F in the EMAUnit in DataPaths.
//			  This bit is set by a CIF instruction and is cleared
//			by the next JMP or JMS instruction.  It inhibits
//			interrupts while the IF != the IB.
//
//   InterruptDelay   - single bit F-F in the TimingGenerator module
//			  This bit is set by the ION instruction and cleared at
//			the end of the next FETCH1 state.  It serves to inhibit
//			interrupts for a single instruction after ION.
//
// Don't blame me - this is all pretty much a verbatim copy of the 8/E!
//--


module TimingGenerator (Clock, Reset, Opcode, MemoryData, AutoIndex,
	InterruptRequest, InterruptEnable, InterruptInhibit, SetInterruptDelay,
        START, LADDR, DEP, EXAM, CONT, STOP, SS, SI,
	State);

  //++
  //   This module sequences thru the states in instruction fetch and execution.
  // A real PDP-8/E or /A has three major states, FETCH, DEFER and EXECUTE,
  // and each of those is divided into four minor states, TS1-TS4.  The timing
  // is fairly fixed; each major state always goes thru all four minor states
  // regardless of the operation being executed, but the controller is able to
  // skip over either the DEFER or EXECUTE major state depending on the opcode.
  // Yes, that's right - it can skip EXECUTE.  Another oddity of the PDP-8 is
  // that many instructions (all OPRs, all IOTs, and direct JMPs) are executed
  // entirely within the TS3 and TS4 states of the FETCH cycle, so there's no
  // need for any EXECUTE state.  In fact, the EXECUTE state is really only
  // used for MRIs...
  //
  //   I couldn't resist cleaning things up a little bit.  We still have three
  // major states and each is divided into minor states, however in this
  // implementation the number of minor states used varies depending on what's
  // being executed.  Also, the PDP-8 DEFER state is split into two separate
  // major states here - AUTOINDEX, which is for auto indexed indirect add-
  // ressing, and DEFER, which is used for indirect addresses only.  DEFER
  // requires only one state where s AUTOINDEX requires three, because the
  // latter has to both increment and restore to memory.  The real PDP-8 took
  // four states for either, which was a huge waste in the case of the DEFER
  // only case.
  //
  //   The actual state machine decoding depends on both the current state (e.g.
  // EXECUTE_1) and the opcode (e.g. TAD), so there is not a separate state for
  // every opcode flow.  This may seem a little odd, but it's close enough to a
  // real PDP-8 that the OMNIBUS interface module can derive compatible timing
  // signals. 
  //--
  input Clock, Reset, AutoIndex;  input [`DATA_WIDTH] Opcode, MemoryData;
  input InterruptRequest, InterruptEnable, InterruptInhibit, SetInterruptDelay;
  output reg [`STATE_CODE_WIDTH] State = `FETCH_1;
  input START, LADDR, DEP, EXAM, CONT, STOP, SS, SI;
  reg [`STATE_CODE_WIDTH] NextState;  reg InterruptDelay = 1'b0;
  reg [`STATE_CODE_WIDTH] ResumeState;

  //   This is the register part of the state machine and synthesizes the flip
  // flops that hold the current state code, and it's as trivial as can be.
  // Notice that a global reset always starts us out in the FETCH1 state.
  always @(posedge Clock or posedge Reset) begin
    if (Reset)
      State = `FETCH_1;
    else
      State = NextState;
    //$strobe("OldState=%o, New state = %o", State, NextState);
  end

  //   The InterruptDelay flip flop is used to inhibit interrupts for exactly
  // one instruction after ION, RTF and similar instructions.  It's set by the
  // LogicUnit via the SetInterruptDelay signal, and it's automatically cleared
  // at the end of each FETCH_1 state...
  always @(posedge Clock or posedge Reset) begin
    if (Reset)
      InterruptDelay = 1'b0;
    else if (State == `FETCH_1)
      InterruptDelay = 1'b0;
    else if (SetInterruptDelay)
      InterruptDelay = 1'b1;
  end

  // And this is the combinatorial block that decodes the next state ...
  always @(State or Opcode or AutoIndex or MemoryData or InterruptRequest
	or InterruptEnable or InterruptInhibit or InterruptDelay) begin
    //   This shouldn't be necessary (all the case options should be covered)
    // but just in case make sure that there's always an assignment to
    // NextState.  Otherwise the synthesis tool may try to make extra F-Fs!
    NextState = `HALTED_1;

    casex (State)
      //   FETCH has either two or three minor states. FETCH_1 and FETCH_2
      // always occur, but FETCH_3 is only used in the case of MRIs.  IOT
      // and OPR instructions go directly from FETCH_2 to EXECUTE_1.  Note
      // that FETCH_1 also checks for an external interrupt request and, if
      // if finds one, then we go to an interrupt acknowledge state and
      // FETCH_2 and all subsequent states for this instruction are aborted.
      //
      //   Another word of warning - it's not possible to use the current
      // Opcode bits until state FETCH_3 or later.  That's because the IR
      // register isn't actually loaded until the end of FETCH_2, and the
      // Opcode bits aren't valid before then. This is a problem for state
      // FETCH_2, which needs to figure out whether the opcode is an IOT or
      // OPR, and it has to look at the actual MemoryData bus. This is a bit
      // kludgey, but for what it's worth, a real PDP-8 does the same thing :-)
      `FETCH_1X: NextState = (InterruptRequest & InterruptEnable
	  & ~(InterruptInhibit | InterruptDelay)) ? `INTERRUPT_1 : `FETCH_2;
      `FETCH_2X: NextState = (MemoryData[0:1]==2'b11) ? `EXECUTE_1 : `FETCH_3;

      //   The FETCH_3 state only occurs for MRIs, and the next state should be
      // either DEFER_1, AUTOINDEX_1 or EXECUTE_1 depending on the addressing
      // mode used.  The sole exception is JMP direct, which is actually exec-
      // uted in the FETCH_3 state (the PC is loaded with the EA and we're
      // done!), so in that specifc case the next state is back to FETCH_1.
      `FETCH_3X: begin
	if (Opcode[0:3] == `OP_JMPD) begin
	  NextState = `FETCH_1;
	end else if (Opcode[3])
	  NextState = AutoIndex ? `AUTOINDEX_1 : `DEFER_1;
	else
	  NextState = `EXECUTE_1;
      end

      //   DEFER always takes only a single cycle for an extra memory read
      // and the next state is always EXECUTE_1, unless the opcode is a JMP.
      // In the sole case of a JMP the PC is actually updated in this state
      // and the next state should be FETCH_1 again.
      `DEFER_1X: NextState = (Opcode[0:2]==`OP_JMP) ? `FETCH_1 : `EXECUTE_1;

      //   Auto index always requires three states - a memory read and inc-
      // rement, a memory write, and a cycle to update the address.  The next
      // state after AUTOINDEX_3 would normally be EXECUTE_1, except in the
      // special case of a JMP. That instruction actually updates the PC in
      // the AUTOINDEX_3 state and the next state would be FETCH_1 again...
      `AUTOINDEX_1X:  NextState = `AUTOINDEX_2;
      `AUTOINDEX_2X:  NextState = `AUTOINDEX_3;
      `AUTOINDEX_3X:  NextState = (Opcode[0:2]==`OP_JMP) ? `FETCH_1 : `EXECUTE_1;

      //   The EXECUTE major state has either one or two cycles.  The AND, TAD,
      // OPR1 and OPR3 instructions finish in one cycle, but ISZ, DCA, JMS, 
      // IOT and OPR2 instructions take two.  Notice that there's also a small
      // kludge in the EXECUTE_2 phase - if the Opcode contains a HLT micro
      // instruction, then the next state is HALTED, not FETCH_1.  
      `EXECUTE_1X: NextState = (
		      (Opcode[0:2]==`OP_ISZ) | ( Opcode[0:2]==`OP_DCA)
		    | (Opcode[0:2]==`OP_JMS) | ( Opcode[0:2]==`OP_IOT)
		    | ((Opcode[0:2]==`OP_OPR) & Opcode[3] & ~Opcode[11])
		  ) ? `EXECUTE_2 : `FETCH_1;
      `EXECUTE_2X: NextState = (
		   (Opcode[0:2]==`OP_OPR) & Opcode[3] & Opcode[10] & ~Opcode[11]
		  ) ? `HALTED_1 : `FETCH_1;

      //   Once we get to the HALTED state, we simply stay there forever.  For
      // the moment, at least, there's no way out.  This useful for testing
      // with the simulator, but for the real CPU we'll want something else.
      `HALTED_1X: begin
        if (START) 
                NextState = `START_1;
        else if (LADDR) 
                NextState = `LADDR_1;
        else if (DEP) 
                NextState = `DEP_1;
        else if (EXAM) 
                NextState = `EXAM_1;
        else if (CONT) 
                NextState = ResumeState;
	//$display("CPU HALTED ...");  $stop;
      end
      
      //   The CAF major state does the CLEAR operation expected during 
      // the operation of the START key, then proceeds to FETCH_1 state,
      // disregarding ResumeState (effectively aborting any incomplete 
      // instruction).
      `START_1X: NextState = `FETCH_1;
      
      //   The LADDR_1 state loads the PC from SR, loads DF and IF from 
      // SDF and SIF, then returns to halted state.
      `LADDR_1X: NextState = `HALTED_1;
      
      // The DEP key loads MB from SR, stores MB, then does and EXAMine.
      `DEP_1X:  NextState = `DEP_2;
      `DEP_2X:  NextState = `EXAM_1;
      
      // The EXAMine operation loads MA from PC and reads memory, 
      // then increments PC.
      `EXAM_1X: NextState = `EXAM_2;
      `EXAM_2X: begin
        NextState = `HALTED_1;
        ResumeState = `FETCH_1;
      end

      //   Interrupts execute a single special cycle, INTERRUPT_1, to clear
      // the interrupt enable, save the IF/DF and clear the current IF/DF,
      // etc.  This cycle also forces a "JMS" into the IR and sets up the EA
      // to zero.  We go to the EXECUTE_1 and 2 states next, which will finish
      // up executing the imaginary JMS 0 instruction...
      `INTERRUPT_1X: NextState = `EXECUTE_1;

      // Trap any unknown conditions for debugging ...
      default: begin
	//$display("UNKNOWN STATE %o", State);  $stop;
	NextState = `HALTED_1;
        ResumeState = `HALTED_1; // ...and stay halted
      end
    endcase
    // SS, SI, and STOP over-ride the NextState as calculated above.
    if (SS | ((STOP | SI) & (NextState == `FETCH_1)))
    begin
        ResumeState = NextState;
        NextState = `HALTED_1;
    end
  end
endmodule


module LogicUnit (State, Opcode, 
  MemoryWrite, DeviceWrite, DeviceRead, DeviceSkip, DeviceControl,
  AC_Minus, AC_Zero, LinkBit, MB_Zero, LoadAC, LoadLink, LoadPC,
  LoadIR, LoadMA, LoadMB, LoadMQ, ClearMQ, LoadSR,
  LeftSelect, ALU_Function, AC_Function, RotateFunction,
  SetInterruptEnable, ClearInterruptEnable, SetInterruptDelay,
  InterruptRequest, InterruptEnable, LoadFlags, DeviceClear, LoadJMS);

  //++
  //   This module implements all the random logic that tells the DataPaths
  // module what to do in every cycle of every instruction.  It's not really
  // all that hard, but it is long and messy because there are many, many
  // different cases to be dealt with.  Despite its complexity, this module
  // is purely combinatorial logic - no flip flops are, or should be, generated
  // here!
  //
  //   In real life (or at least in real hardware) this would be better
  // implemented as a PLA or ROM.  We could do that in Verilog too, but then
  // we need some way to come up with the PLA or ROM programming, which would
  // require more tools and another source file.  It's more convenient just to
  // spell it all out right here ...
  //--
  input [`STATE_CODE_WIDTH] State;  input [`DATA_WIDTH] Opcode;
  output reg MemoryWrite, DeviceWrite, DeviceRead, DeviceClear, LoadJMS;
  input DeviceSkip, AC_Minus, AC_Zero, LinkBit, MB_Zero;
  input InterruptRequest, InterruptEnable;
  input [0:1] DeviceControl;
  output reg LoadAC, LoadLink, LoadPC, LoadIR, LoadMA;
  output reg ClearMQ, LoadSR, LoadMB, LoadMQ, LoadFlags;
  output reg SetInterruptEnable, ClearInterruptEnable, SetInterruptDelay;
  output reg [`LEFT_SOURCE_WIDTH] LeftSelect;
  output reg [`ALU_FUNCTION_WIDTH] ALU_Function;
  output reg [`AC_FUNCTION_WIDTH] AC_Function;
  output reg [`ROTATE_FUNCTION_WIDTH] RotateFunction;

  always @(State or Opcode or DeviceSkip or DeviceControl or InterruptEnable
	or InterruptRequest or AC_Minus or AC_Zero or LinkBit or MB_Zero) begin

    //   If a signal is assigned a value anywhere in this block, then we have
    // to ensure that the same signal is always assigned some value for every
    // possible case.  If we don't, then Verilog with synthesize flip flops to
    // retain the state of that signal, which is exactly what we DON'T want to
    // happen!  The easiest way to make sure this condition is met is to assign
    // a default value to everything right here - this can always be overridden
    // later in specific cases... 
    LoadAC=1'b0; LoadLink =1'b0; LoadPC=1'b0; LoadMQ=1'b0; LoadIR=1'b0;
    LoadSR=1'b0; LoadMA=1'b0; LoadMB=1'b0; ClearMQ=1'b0;
    DeviceWrite=1'b0; DeviceRead=1'b0; MemoryWrite=1'b0;  LoadJMS=1'b0;
    LeftSelect=`LEFT_UNUSED; ALU_Function=`ALU_LEFT; DeviceClear=1'b0;
    AC_Function=4'b0; RotateFunction=3'b0; LoadFlags=1'b0;
    SetInterruptEnable=1'b0; ClearInterruptEnable=1'b0; SetInterruptDelay=1'b0;

    casex ({State, Opcode})

      //   States FETCH1 and 2 don't depend on the current opcode, and in fact,
      // it's never safe to depend on the opcode before FETCH3 because the IR
      // isn't loaded until the end of FETCH2 ...
      {`FETCH_1X, `OPX_ANY}: begin
	// MA <= PC;
	LoadMA=1'b1;  LeftSelect=`LEFT_PC;  ALU_Function=`ALU_LEFT;
      end
      {`FETCH_2X, `OPX_ANY}: begin
	// PC <= PC + 1;  IR <= MD;
	//   Check the DataPaths and notice that the IR is loaded directly from
	// the MemoryData bus and not from the ALU/ROTATE Sum bus.  Otherwise
	// it'd be impossible to combine both these assignments into one cycle.
	LoadPC=1'b1; LeftSelect=`LEFT_PC; ALU_Function=`ALU_LEFT_PLUS_ONE;
	LoadIR=1'b1;
      end

      //   FETCH3 only occurs for MRIs - OPRs and IOTs are in EXECUTE1 by now.
      // Also notice that a direct JMP opcode can be completely executed in this
      // state by loading the operand address into the PC rather than the MA ...
      {`FETCH_3X, `OPX_JMPD}: begin
	// PC <= EA; /* a direct JMP */
	LoadPC=1'b1;  LeftSelect=`LEFT_EA;  ALU_Function=`ALU_LEFT;
      end
      {`FETCH_3X, `OPX_ANY}: begin
	// MA <= EA; /* any other MRI */
	LoadMA=1'b1;  LeftSelect=`LEFT_EA;  ALU_Function=`ALU_LEFT;
      end

      //   In the case of the PDP-8/V (and unlike the 8/A and 8/E) DEFER is
      // used only for indirect and never for autoindex, so we know that only
      // one extra memory cycle will be required to fetch the actual operand
      // address.  Once again, in the case of a JMP we can load the address
      // directly into the PC rather than the MA and skip any EXECUTE state.
      {`DEFER_1X, `OPX_JMP}: begin
	// PC <= MD; /* an indirect JMP */
	LoadPC=1'b1;  LeftSelect=`LEFT_MD;  ALU_Function=`ALU_LEFT;
      end
      {`DEFER_1X, `OPX_ANY}: begin
	// MA <= MD; /* any other indirect MRI */
	LoadMA=1'b1;  LeftSelect=`LEFT_MD;  ALU_Function=`ALU_LEFT;
      end

      //   Autoindex mode always requires three extra states - read the index
      // register and increment it; write the new value back to memory, and
      // and transfer the pointer to the MA or PC.  Just as before, in the
      // case of a JMP ocopde we save a state by transferring the destination
      // address directly into the PC instead of the MA.
      {`AUTOINDEX_1X, `OPX_ANY}: begin
	// MB <= MD + 1;
	LoadMB=1'b1;  LeftSelect=`LEFT_MD;  ALU_Function=`ALU_LEFT_PLUS_ONE;
      end
      {`AUTOINDEX_2X, `OPX_ANY}: begin
	// MEMORY_WRITE();
	MemoryWrite=1'b1;
      end
      {`AUTOINDEX_3X, `OPX_JMP}: begin
	// PC <= MB;  /* an autoindexed JMP */
	LoadPC=1'b1;  LeftSelect=`LEFT_MB;  ALU_Function=`ALU_LEFT;
      end
      {`AUTOINDEX_3X, `OPX_ANY}: begin
	// MA <= MB;  /* any other autoindexed MRI */
	LoadMA=1'b1;  LeftSelect=`LEFT_MB;  ALU_Function=`ALU_LEFT;
      end

      //   AND and TAD are both nearly identical, fairly trivial, and complete
      // in a single cycle.  The only differences are the ALU function and that
      // TAD also updates the LINK where as AND doesn't.  In either case the
      // operand has already been addressed and is currently sitting on the MD
      // bus waiting for us to use it...
      {`EXECUTE_1X, `OPX_AND}: begin
	// AC <= AC AND MD
	LoadAC=1'b1;  LeftSelect=`LEFT_MD;  ALU_Function=`ALU_LEFT_AND_RIGHT;
      end
      {`EXECUTE_1X, `OPX_TAD}: begin
	// AC <= AC + MD;  IF (carry) LINK <= ~ LINK
	LoadAC=1'b1;  LeftSelect=`LEFT_MD;  ALU_Function=`ALU_LEFT_PLUS_RIGHT;
	LoadLink=1'b1;
      end

      //   ISZ requires two execute cycles - the first one increments the memory
      // data and stores the result in the MB, and the second cycle writes the
      // new count back to memory.  In the second cycle the PC is also given an
      // extra increment (for a skip) if the memory buffer contains zero.
      {`EXECUTE_1X, `OPX_ISZ}: begin
	// MB <= MD + 1
	LoadMB=1'b1;  LeftSelect=`LEFT_MD;  ALU_Function=`ALU_LEFT_PLUS_ONE;
      end
      {`EXECUTE_2X, `OPX_ISZ}: begin
	// MEMORY_WRITE();  IF (MB == 0) PC <= PC + 1;
	MemoryWrite=1'b1; LeftSelect=`LEFT_PC; ALU_Function=`ALU_LEFT_PLUS_ONE;
	//   Notice that the ALU always computes PC+1 regardless of the MB -
	// it's only the loading of the PC that's enabled if MB==0.
	if (MB_Zero) LoadPC=1'b1;
      end

      //   DCA requires two cycles as well - the first one copies the AC data to
      // the memory buffer, and the second cycle does a memory write and clears
      // the AC.
      {`EXECUTE_1X, `OPX_DCA}: begin
	// MB <= AC
	LoadMB=1'b1;  ALU_Function=`ALU_RIGHT;
      end
      {`EXECUTE_2X, `OPX_DCA}: begin
	// MEMORY_WRITE();  AC <= 0;
	MemoryWrite=1'b1;
	LoadAC=1'b1;  ALU_Function=`ALU_RIGHT; AC_Function=`CLEAR_AC;
      end

      //   JMS is a little like DCA and requires two cycles.  The first cycle
      // copies the PC to the memory buffer, and the second does a memory write
      // to save the return address in memory.  The second cycle also computes
      // PC <= MA + 1 so that we'll jump to the next instruction after the
      // return address.
      {`EXECUTE_1X, `OPX_JMS}: begin
	// MB <= PC
	LoadMB=1'b1;  LeftSelect=`LEFT_PC;  ALU_Function=`ALU_LEFT;
      end
      {`EXECUTE_2X, `OPX_JMS}: begin
	// MEMORY_WRITE();  PC <= MA + 1
	MemoryWrite=1'b1;
	LoadPC=1'b1;  LeftSelect=`LEFT_MA;  ALU_Function=`ALU_LEFT_PLUS_ONE;
      end

      //   Amazingly, for all it's options and permutations, OPR1 instructions
      // need only one cycle to execute.  That's because the DataPaths provide
      // all of an AC functions unit (for CLA/CMA/CLL/CML), an ALU (for IAC)
      // and a rotate unit (RxR/RxL/BSW/R3L) in the proper order.  All we have
      // to do is setup the right function codes and it'll happen.
      {`EXECUTE_1X, `OPX_OPR1}: begin
	AC_Function = Opcode[4:7];  RotateFunction = Opcode[8:10];
	ALU_Function = Opcode[11] ? `ALU_RIGHT_PLUS_ONE : `ALU_RIGHT;
	LoadAC = 1'b1;  LoadLink = 1'b1;
      end

      //   OPR2 micro instructions take two cycles - the first one handles the
      // skipping, computing PC <= PC + 1 if the condition is satisfied, and
      // the second state handles CLA and OSR.  Note that neither state handles
      // HLT - that's taken care of by the timing generator module, which will
      // force the next state to be HALTED rather than FETCH if HLT is set.
      //
      //   For reference, the actual truth table for the skip instructions goes
      // something like this -
      //
      //  BITS
      //  5678      CONDITION TESTED
      //  ----    ------------------------------
      //  0000	  Never				// NOP
      //  0001	  Always 			// SKP
      //  0010	  LinkBit			// SNL
      //  0011	 ~LinkBit			// SZL
      //  0100	  AC_Zero			// SZA
      //  0101	 ~AC_Zero			// SNA
      //  0110	  AC_Zero  | LinkBit		// SZA or SNL
      //  0111	~(AC_Zero  | LinkBit)		// SNA and SZL
      //  1000	  AC_Minus			// SMA
      //  1001	 ~AC_Minus			// SPA
      //  1010	  AC_Minus | LinkBit		// SMA or SNL
      //  1011	~(AC_Minus | LinkBit)		// SPA and SZL
      //  1100	  AC_Minus | AC_Zero		// SMA or SZA
      //  1101	~(AC_Minus | AC_Zero)		// SPA or SNA 
      //  1110	  AC_Minus | AC_Zero | LinkBit	// SMA or SZA or SNL
      //  1111	~(AC_Minus | AC_Zero | LinkBit	// SPA or SNA or SZL 
      //
      //   I suppose it comes as no suprise to find out that all this can be
      // implemented fairly trivially with just a few gates :-)
      {`EXECUTE_1X, `OPX_OPR2}: begin
	// IF (condition) PC <= PC + 1
	LeftSelect = `LEFT_PC;  ALU_Function = `ALU_LEFT_PLUS_ONE;
	LoadPC = Opcode[8] ^
	    ((Opcode[5]&AC_Minus) | (Opcode[6]&AC_Zero) | (Opcode[7]&LinkBit));
      end
      {`EXECUTE_2X, `OPX_OPR2}: begin
	//  An OPR2 micro instruction always puts the switch register on the IO
        // bus, even if the OSR bit isn't actually set. This should be harmless.
	LeftSelect = `LEFT_SR;
	// Set the AC Function unit according to the CLA bit...
	if (Opcode[4]) AC_Function = `CLEAR_AC;
	// And set the ALU function according to the OSR bit...
	ALU_Function = Opcode[9] ? `ALU_LEFT_OR_RIGHT : `ALU_RIGHT;
	// And the AC will be loaded if either CLA or OSR is set.
	if (Opcode[9] | Opcode[4]) LoadAC = 1'b1;
      end

      //   The group 3 micro instructions, like group 1, require only a single
      // cycle to execute.  That's possible only because the MQ is loaded
      // directly from the AC, rather than from the ALU/ROTATE bus as the other
      // registers are.  This makes it possible to exchange the MQ and the AC
      // in a single clock cycle, without needing to use any temporary register.
      //
      //   Here's the table of the outputs required to implement the various
      // combinations of the group 3 operate functions -
      //
      //  Opcode Bit Load Load   AC         ALU       Clear
      //         457  AC   MQ  Function   Function     MQ
      //         --- ---- ---- -------- ------------- -----
      // NOP     000   N    N  CLEAR_AC     RIGHT       N
      // MQL     001   Y    Y  CLEAR_AC     RIGHT       N
      // MQA     010   Y    N     ~     LEFT_OR_RIGHT   N
      // SWP     011   Y    Y  CLEAR_AC LEFT_OR_RIGHT   N
      // CLA     100   Y    N  CLEAR_AC     RIGHT       N
      // CAM     101   Y    Y  CLEAR_AC     RIGHT       Y
      // ACL     110   Y    N  CLEAR_AC LEFT_OR_RIGHT   N
      // CLA SWP 111   Y    Y  CLEAR_AC LEFT_OR_RIGHT   Y
      //
      //   Some of these are superfluous (e.g. setting LoadMQ when ClearMQ is
      // also set, or using ALU Function LEFT OR RIGHT with CLEAR_AC to get the
      // equivalent of ALU_LEFT) but they make it fairly simple to derive the
      // outputs from the opcode bits...
      {`EXECUTE_1X, `OPX_OPR3}: begin
	// LeftSelect can always be set to MQ, no matter what else happens ..
	LeftSelect=`LEFT_MQ;
	// LoadAC is TRUE for anything but NOP ...
	LoadAC = {Opcode[4:5],Opcode[7]} != 3'b000;
 	// LoadMQ is TRUE for any MQL function ...
	LoadMQ = Opcode[7];
	// The AC is cleared for all but MQA ...
	AC_Function = ({Opcode[4:5],Opcode[7]} == 3'b010) ? 4'b0 : `CLEAR_AC;
	// LEFT_OR_RIGHT for anything that transfers the MQ to the AC ...
	ALU_Function = Opcode[5] ? `ALU_LEFT_OR_RIGHT : `ALU_RIGHT;
	// And ClearMQ is TRUE for CAM and CLA SWP ...
	ClearMQ = (Opcode[4]==1'b1) & (Opcode[7]==1'b1);
      end

      //   The processor IOTs (e.g. SKON, GTF, RTF, etc) are trapped here and
      // executed as if they were "real" instructions rather than IOTs.  None
      // of them will assert either DeviceWrite or DeviceRead, and none of them
      // pay any attention to the DeviceControl or DeviceSkip inputs.
      {`EXECUTE_1X, `OP_CAF}: begin
	//   CAF clears the AC and the LINK and asserts DeviceClear for one
	// cycle.  It also clears the interrupt enable flag.
	LoadAC = 1'b1;  ALU_Function = `ALU_RIGHT;
	LoadLink = 1'b1;  AC_Function = `CLEAR_AC | `CLEAR_LINK;
	DeviceClear = 1'b1;  ClearInterruptEnable = 1'b1;
      end
      {`EXECUTE_1X, `OP_ION}: begin
        // Set the interrupt enable, but inhibit interrupts for one instruction...
	SetInterruptEnable = 1'b1;  SetInterruptDelay = 1'b1;
      end
      {`EXECUTE_1X, `OP_SKON}: begin
	//   SKON skips if the interrupt enable is currently set, and then it
	// turns the interrupt system off exactly the same way as IOF ...
	ClearInterruptEnable = 1'b1;
	LeftSelect = `LEFT_PC;  ALU_Function = `ALU_LEFT_PLUS_ONE;
	if (InterruptEnable) LoadPC = 1'b1;
      end
      {`EXECUTE_1X, `OP_IOF}: begin
        // Clear the interrupt enable flag...
	ClearInterruptEnable = 1'b1;
      end
      {`EXECUTE_1X, `OP_SRQ}: begin
        //   Skip if the interrupt request line is active.  Note that this only
	// tests the external interrupt input to the CPU - it doesn't consider
	// InterruptEnable, InterruptInhibit or InterruptDelay ...
	LeftSelect = `LEFT_PC;  ALU_Function = `ALU_LEFT_PLUS_ONE;
	if (InterruptRequest) LoadPC = 1'b1;
      end
      {`EXECUTE_1X, `OP_GTF}: begin
	// GTF reads the flag register into the AC ...
	LoadAC = 1'b1;  LeftSelect = `LEFT_FLAGS;  ALU_Function = `ALU_LEFT;
      end
      {`EXECUTE_1X, `OP_RTF}: begin
	// RTF sets the flags from the AC _and_ enables interrupts ...
	LoadFlags=1'b1; SetInterruptEnable=1'b1; SetInterruptDelay=1'b1;
      end
      {`EXECUTE_1X, `OP_SGT}: begin
        //   SGT is not yet implemented (that'll have to wait for the EAE!).
	// It executes as a no-op...
      end
      {`EXECUTE_1X, `OP_WSR}: begin
	//   The WSR instruction loads the switch register from the AC.
	// Strictly speaking, this is a HD6120 only IOT (the real PDP-8/E
	// never had a programmable switch register!) but it our case it's
	// the only switch register that we've got, so the WSR instruction
	// is always present.
        LoadSR = 1'b1;
      end
      //   All the processor IOTs execute in a single cycle, but the timing
      // generator doesn't know this and still generates EXECUTE_2 just as it
      // would for a real IOT.  Trap that combination and make it a no-op...
      {`EXECUTE_2X, 12'O600x}, {`EXECUTE_2X, `OP_WSR}: /* nothing to do! */ ;      

      //   The first cycle of any IOT drives the DeviceData bus (aka the I/O
      // bus) with the contents of the AC and asserts DeviceWrite.  If this
      // IOT is an output instruction the selected device should use the
      // trailing edge of DeviceWrite to latch new data from the AC.  It's
      // also in this cycle that the DeviceSkip input is sampled and, if this
      // is a skip IOT, the ALU can be used to increment the PC.
      {`EXECUTE_1X, `OPX_IOT}: begin
	DeviceWrite = 1'b1;
	LeftSelect = `LEFT_PC;  ALU_Function = `ALU_LEFT_PLUS_ONE;
	if (DeviceSkip) LoadPC = 1'b1;
      end

      //   The second cycle of any IOT samples the DeviceControl inputs to see
      // if the AC should be cleared, the device data OR'ed with the AC, or
      // both.  DeviceRead is asserted during this time which both signals that
      // the selected device should drive the DeviceControl bus and also that
      // it's OK for the device to drive the DeviceData bus if required.
      {`EXECUTE_2X, `OPX_IOT}: begin
	DeviceRead = 1'b1;  LeftSelect = `LEFT_IO;
	// If C0 is set, then the AC is cleared on way or another...
	AC_Function = DeviceControl[0] ? `CLEAR_AC : 0;
	// If C1 is set, then device data is read; else the I/O bus is ignored.
	ALU_Function = DeviceControl[1] ? `ALU_LEFT_OR_RIGHT : `ALU_RIGHT;
	// And the AC has to be reloaded if either bit is set
	if (DeviceControl[0] | DeviceControl[1]) LoadAC = 1'b1;
      end

      //   The INTERRUPT acknowledge state clears the interrupt enable flag
      // and executes the equivalent of a "JMS 0" instruction.  This code
      // dummies that up a bit by forcing a JMS opcode into the IR and loading
      // MA with zero.  The TimingGenerator will schedule EXECUTE_1 and 2
      // states after this, which will store the current PC in location zero
      // and load the PC with 1.  Couldn't be easier :-)
      {`INTERRUPT_1X, `OPX_ANY}: begin
	LoadJMS = 1'b1;  ClearInterruptEnable = 1'b1;
	LoadMA = 1'b1;  AC_Function = `CLEAR_AC;  ALU_Function = `ALU_RIGHT;  
      end

      // And don't do anything in the HALT state...
      {`HALTED_1X, `OPX_ANY}: begin
        /* do nothing */
      end
      
      // Pressing start essentially mimics CAF.
      {`START_1X, `OPX_ANY}: begin
	LoadAC = 1'b1;  ALU_Function = `ALU_RIGHT;
	LoadLink = 1'b1;  AC_Function = `CLEAR_AC | `CLEAR_LINK;
	DeviceClear = 1'b1;  ClearInterruptEnable = 1'b1;
      end
      
      {`LADDR_1X, `OPX_ANY}: begin
        // BUGBUG: Need LADDR_2 to implement DF, IF load!
        // PC <= SR
	LoadPC=1'b1;  LeftSelect = `LEFT_SR; ALU_Function=`ALU_LEFT;
      end

      // This mimics the memory read phase, FETCH_1.
      {`EXAM_1X, `OPX_ANY}: begin
	// MA <= PC;
	LoadMA=1'b1;  LeftSelect= `LEFT_PC;  ALU_Function=`ALU_LEFT;
      end
      {`EXAM_2X, `OPX_ANY}: begin
	// PC <= PC + 1;
	LoadPC=1'b1; LeftSelect= `LEFT_PC; ALU_Function=`ALU_LEFT_PLUS_ONE;
      end

      //   DEP requires two cycles as well - the first one copies the SR data to
      // the memory buffer, and the second cycle does a memory write.
      {`DEP_1X, `OPX_ANY}: begin
	// MB <= SR
	LoadMB=1'b1; LeftSelect = `LEFT_SR; ALU_Function=`ALU_LEFT;
      end
      {`DEP_2X, `OPX_ANY}: begin
	// MEMORY_WRITE();
	MemoryWrite=1'b1; ALU_Function=`ALU_RIGHT;
      end

      //   Originally these next two cases were used in simulation to help
      // track down sequencing errors, but they turn out to be more trouble
      // than they're worth.  The problem is both the State and Opcode change
      // on the same clock edge and and occasionally a situation will arise
      // where this always block is executed with an invalid state/opcode
      // combination, and this situation leads to spurious errors.  There
      // didn't seem to be any good way to fix it, so I just punted on the
      // whole concept.  The timing generator works pretty well, anyway :-)
      // ever have an EXECUTE state. They're always completed during fetch.
      //{`EXECUTE_1X, `OPX_JMP}, {`EXECUTE_2X, `OPX_JMP}: begin
      //$display("EXECUTE STATE WITH JMP"); $stop;
      //end
      default: begin
	//$display("UNKNOWN STATE/OPCODE COMBINATION ...");  $stop;
      end

    endcase
  end
endmodule


module Controller (Clock, Reset, Opcode, MemoryData,
  MemoryWrite, DeviceWrite, DeviceRead, DeviceSkip, DeviceControl,
  InterruptRequest, InterruptGrant, Halted,
  AC_Zero, AC_Minus, LinkBit, MB_Zero, AutoIndex,
  LoadPC, LoadIR, LoadMA, LoadMB, LoadMQ, ClearMQ,
  LoadSR, LoadAC, LoadLink, LoadJMS,
  LeftSelect, ALU_Function, AC_Function, RotateFunction,
  InterruptEnable, SetInterruptEnable, ClearInterruptEnable,
  S3_SSER_N, S3_SCK, S3_SCL_N, SR_Bus,
  InterruptInhibit, LoadFlags, DeviceClear);

  //++
  //   This module implements all the control logic for the PDP-8/V which, at
  // the moment, consists only of the timing generator and the control logic.
  // The rest is just a matter of wiring up all the necessary inputs and
  // outputs.
  //--
  // Global signals ...
  input	 Clock;			// master clock for all operations
  input	 Reset;			// TRUE to synchronously reset all registers
  // Memory and I/O control signals ...
  input [`DATA_WIDTH]MemoryData;// current memory data (MD) bus
  output MemoryWrite;		// TRUE to drive the MB onto the MD bus
  output DeviceWrite;		//   "	 "   "	  "  AC onto the IO bus
  output DeviceRead;		// DEVICE => AC strobe for external devices
  input	 DeviceSkip;		// TRUE during DeviceWrite if the IOT skips
  input	 [0:1] DeviceControl;	// IOT function (the Cx lines!)
  output DeviceClear;		// initialize all I/O devices (CAF)
  output Halted;		// TRUE if a HLT instruction is executed
  // Status inputs ...
  input	 [`DATA_WIDTH] Opcode;	// current instruction being executed (IR)
  input	 AC_Zero;		// TRUE if the AC is zero
  input	 AC_Minus;		// TRUE if the AC is < 0 (AC[0] != 0)
  input	 LinkBit;		// current state of the LINK bit
  input	 MB_Zero;		// TRUE if MB is zero
  input	 AutoIndex;		// TRUE if MA == 12'O001x
  // Interrupt system flag bits ...
  input InterruptRequest;	// state of the external interrupt request line
  output ClearInterruptEnable;	// TRUE to clear the interrupt enable F-F
  output SetInterruptEnable;	//   "   " set    "    "    "    "     "
  input  InterruptEnable;	// current state of the interrupt enable flag
  input  InterruptInhibit;	//  "   "   "  "     "   "     "  inhibit  "
  output InterruptGrant;	// TRUE while an interrupt cycle is executed
  // DataPaths control outputs ...
  output LoadAC;		// TRUE to load the AC register this cycle
  output LoadLink;		//   "	 "   "	 "  link bit	  "	 "
  output LoadPC;		//   "	 "   "	 "  PC register	  "	 "
  output LoadMQ;		//   "	 "   "	 "  MQ	 "   "	  "	 "
  output LoadIR;		//   "	 "   "	 "  instruction register "
  output LoadSR;		//   "	 "   "	 "  switch register	 "
  output LoadMA;		//   "	 "   "	 "  memory address "	 "
  output LoadMB;		//   "	 "   "	 "  memory buffer  "	 "
  output ClearMQ;		// TRUE to load MQ with zero this cycle
  output LoadFlags;		// TRUE to load the FLAGS from the AC
  output LoadJMS;		// TRUE to load 4000 (JMS) into the IR
  output [`LEFT_SOURCE_WIDTH] LeftSelect;	// ALU left input select
  output [`ALU_FUNCTION_WIDTH] ALU_Function;	// ALU function code
  output [`AC_FUNCTION_WIDTH] AC_Function;	// AC function code
  output [`ROTATE_FUNCTION_WIDTH]RotateFunction;// rotate function code
  output S3_SCK, S3_SCL_N;
  input S3_SSER_N;
  output [`DATA_WIDTH] SR_Bus;

  // Local signals ...
  wire [`STATE_CODE_WIDTH] State;
  wire SetInterruptDelay;

  TimingGenerator TG (
    .Clock(Clock), .Reset(Reset), .State(State), .Opcode(Opcode),
    .MemoryData(MemoryData), .AutoIndex(AutoIndex),
    .InterruptRequest(InterruptRequest), .InterruptEnable(InterruptEnable),
    .START(START), .LADDR(LADDR), .DEP(DEP), .EXAM(EXAM), .CONT(CONT),
    .STOP(STOP), .SS(SS), .SI(SI),
    .InterruptInhibit(InterruptInhibit), .SetInterruptDelay(SetInterruptDelay)
  );

  LogicUnit LU (
    .State(State), .Opcode(Opcode), .MemoryWrite(MemoryWrite),
    .DeviceWrite(DeviceWrite), .DeviceRead(DeviceRead), .DeviceSkip(DeviceSkip),
    .DeviceControl(DeviceControl), .AC_Minus(AC_Minus), .AC_Zero(AC_Zero),
    .LinkBit(LinkBit), .MB_Zero(MB_Zero),
    .LoadAC(LoadAC), .LoadLink(LoadLink), .LoadPC(LoadPC), .LoadIR(LoadIR),
    .LoadMA(LoadMA), .LoadMB(LoadMB), .LoadMQ(LoadMQ), .ClearMQ(ClearMQ),
    .LoadSR(LoadSR), .LoadJMS(LoadJMS),
    .LeftSelect(LeftSelect), .ALU_Function(ALU_Function),
    .AC_Function(AC_Function), .RotateFunction(RotateFunction),
    .ClearInterruptEnable(ClearInterruptEnable), 
    .SetInterruptEnable(SetInterruptEnable),
    .SetInterruptDelay(SetInterruptDelay),
    .LoadFlags(LoadFlags), .DeviceClear(DeviceClear),
    .InterruptRequest(InterruptRequest), .InterruptEnable(InterruptEnable)
  );

  wire [0:2] SDF, SIF;
  wire [0:5] CONF;
  // The switch panel  controls things, mostly while Halted ...
  switchesDeMux switches (
      .clk(Clock),
      .reset(Reset),
      .S3_SSER_N(S3_SSER_N),
      .S3_SCK(S3_SCK),
      .S3_SCL_N(S3_SCL_N),
      .SDF(SDF),
      .SIF(SIF),
      .SR(SR_Bus),
      .START(START),
      .LADDR(LADDR),
      .DEP(DEP),
      .EXAM(EXAM),
      .CONT(CONT),
      .STOP(STOP),
      .SS(SS),
      .SI(SI),
      .CONF(CONF)
  );

  // These should probably be moved to LogicUnit ...         
  assign Halted = State == `HALTED_1;
  assign InterruptGrant = State == `INTERRUPT_1;
  //assign Halted = (State & `HALTED_1) != 0;
  //assign InterruptGrant = (State & `INTERRUPT_1) != 0;
endmodule
